### ISSUE TITLE
[BUG] Mango binary only supports amd64

### ISSUE THREAD

**Issue by trinsic** [swizzin/swizzin#1017]
### What happened?

Steps to reproduce:

1. Install package
Mango
3. Error 
sh: 1: /opt/mango/mango: Exec format error

Expected results:
Mango does not have an armhf/arm64 binary and requires docker to use on arm. The binary files provided on Github are not executable, just object files.

### Swizzin commit

c943adc

### What OS are you using?

Debian 11 (Bullseye)

### What architecture is your OS?

arm64

**Comment by liaralabs** [comment]
We only ship the binaries released directly by mango. If the arm binaries aren't functional, then it would be best to report that to mango, not to us.

**Comment by trinsic** [comment]
The ARM .o files they release are to be used with Docker.

The reason there is no ARM binary is the Crystal compiler they use doesn't support static builds on ARM- https://github.com/crystal-lang/crystal/issues/5467

Best if support it just removed.

**Comment by flying-sausages** [comment]
Yeah let's handle this gracefully and remove the support

**Comment by flying-sausages** [comment]
ah https://github.com/swizzin/swizzin/pull/916/files well look at that :p

**Comment by flying-sausages** [comment]
phixed
