### ISSUE TITLE
[BUG] OMBI mobile not work

### ISSUE THREAD

**Issue by gandalf764** [swizzin/swizzin#1019]
### What happened?

ombi installs fine with your script, but there is a problem configuring the mobile app.
By installing the mobile app it is not possible to configure the ombi url because it is unknown.
Installing ombi normally (without swizzin) this problem doesn't exist.

### Swizzin commit

c943adc

### What OS are you using?

Debian 11 (Bullseye)

### What architecture is your OS?

amd64

**Comment by liaralabs** [comment]
This is a paid application and one which I don't own (and unlikely to purchase just to troubleshoot this issue). Can you provide additional information or context that could help?

We simply proxy the application through nginx at the base url of /ombi. We don't use basic authentication on this endpoint, so there shouldn't be anything obstructing the application's ability to communicate with the server, as long as its being pointed to the correct location.

**Comment by gandalf764** [comment]
the thing is strange because the app only asks for the url (the credentials are requested later)
but when i enter the url correctly, i get a message that the url is not recognized.
my ombi is here: https://176.57.150.64/ombi and it can be reached without problems. I attach an image of the app
![image](https://github.com/swizzin/swizzin/assets/41706025/4ce8c139-334d-437d-b8b9-ee7cfda9437c)

**Comment by gandalf764** [comment]
I used the stable version..
I noticed the only difference is that in the url with swizzin I have https while installing normally I have http.
Could it be that the app doesn't support https?

**Comment by liaralabs** [comment]
That may be a question for the app developer. It's a good thought though actually -- the more likely reason is that the application doesn't support the concept of an invalid/self-signed ssl certificate and doesn't seem to have any tickboxes that would allow you to disable ssl verification for your attempts.

The work around for this would be a fully qualified domain name with a valid ssl certificate (i.e. through the let's encrypt flow), but would require you to have a DNS entry pointing at your IP to be able to test

**Comment by gandalf764** [comment]
The ombi app works with the https domain, but it must have a valid certificate.
In my case I registered a domain on register.it and installed a certificate with letsencrypt (installing it with box install letsencrypt)
Everything works perfectly. Thanks for the prompt assistance.
