### ISSUE TITLE
[BUG] Unable to connect through app to Jellyfin

### ISSUE THREAD

**Issue by ptzetaa** [swizzin/swizzin#1022]
### What happened?

Steps to reproduce:

1. Install package 'Jellyfin'
2. Go to 'Android/IOS/Android TV Jellyfin official app'
3. Error 'Unable to access server xxx.xxx.x.xxx:xxxx'

I'm not using HTTPS only HTTP
I`m able to connect trough web

### Swizzin commit

c943adc

### What OS are you using?

Ubuntu 22.04 (Jammy)

### What architecture is your OS?

amd64

**Comment by brettpetch** [comment]
check ufw config. not something we support but something that does ship on jammy by default.
