### ISSUE TITLE
[BUG] sonarr cannot mount SMB, other packages can

### ISSUE THREAD

**Issue by Stooovie** [swizzin/swizzin#1024]
### What happened?

Steps to reproduce:

1. install Swizzin
2. install Sonarr
3. Go to Settings/Media Management
4. Add root folder.
5. It won't get saved

Expected results: root folder is saved.  No other Swizzin app has this issue. Prowlarr, Radarr and others can see, mount and use the same root folder without any issues.

### Swizzin commit

u2714

### What OS are you using?

Debian 11 (Bullseye)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
root@swizzin:/media/Public# sudo systemctl status sonarr
* sonarr.service - Sonarr Daemon
     Loaded: loaded (/etc/systemd/system/sonarr.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2023-06-10 13:59:28 UTC; 25min ago
   Main PID: 12721 (mono)
      Tasks: 11 (limit: 19005)
     Memory: 169.7M
        CPU: 7.730s
     CGroup: /system.slice/sonarr.service
             `-12721 /usr/bin/mono --debug /opt/Sonarr/Sonarr.exe -nobrowser -data=/home/stooovie/.>

Jun 10 13:59:32 swizzin mono[12721]: [Info] QualityProfileService: Setting up default quality profi>
Jun 10 13:59:33 swizzin mono[12721]: [Info] LanguageProfileService: Setting up default language pro>
Jun 10 14:14:33 swizzin mono[12721]: [Info] RssSyncService: Starting RSS Sync
Jun 10 14:14:33 swizzin mono[12721]: [Warn] FetchAndParseRssService: No available indexers. check y>
Jun 10 14:14:33 swizzin mono[12721]: [Info] DownloadDecisionMaker: No results found
Jun 10 14:14:33 swizzin mono[12721]: [Info] RssSyncService: RSS Sync Completed. Reports found: 0, R>
Jun 10 14:18:09 swizzin mono[12721]: [Warn] SonarrErrorPipeline: Invalid request Validation failed:
Jun 10 14:18:09 swizzin mono[12721]:  -- Path: Folder is not writable by user stooovie
Jun 10 14:18:47 swizzin mono[12721]: [Warn] SonarrErrorPipeline: Invalid request Validation failed:
Jun 10 14:18:47 swizzin mono[12721]:  -- Path: Folder is not writable by user stooovie
```

**Comment by liaralabs** [comment]
Your error is quite clearly stated in the log output you provided:

The user running sonarr doesn't have proper permissions it needs to RWX on your root directory.

It should be running as your master user but a `systemctl cat sonarr` should verify this

**Comment by Stooovie** [comment]
`systemctl cat stooovie `

returns 

```
oot@swizzin:~# systemctl cat sonarr
# /etc/systemd/system/sonarr.service
[Unit]
Description=Sonarr Daemon
After=network.target

[Service]
User=stooovie
Group=stooovie
UMask=0002

Type=simple
ExecStart=/usr/bin/mono --debug /opt/Sonarr/Sonarr.exe -nobrowser -data=/home/s>
TimeoutStopSec=20
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target
lines 1-18/18 (END)
```

I literally use the same way of mounting the NAS share in all my LXCs and VMs (I run Swizzin in a LXC container in Proxmox). and this is the only issue I have. I can see the share mounted in /media and write to it. Just Sonarr can't. What else can I try? Thanks!

**Comment by Stooovie** [comment]
It was indeed a permissions issue. I was able to mount the SMB share (and not use the Proxmox binding).
