### ISSUE TITLE
[BUG] upgrading/installing rtorrent

### ISSUE THREAD

**Issue by csy7550** [swizzin/swizzin#1042]
### What happened?

Steps to reproduce:

1. box update
2. box upgrade/install rtorrent
3. build fails, rtorrent gone.

Tried every build (0.9.8, 0.9.7, 0.9.6), they all fail. Had to install repo version to get everything running again.

Expected results:

upgrading rtorrent

### Swizzin commit

0acf022

### What OS are you using?

Ubuntu 22.04 (Jammy)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
/bin/bash ../libtool  --tag=CXX   --mode=link g++  -w -O2 -flto=12     -o rtorrent main.o libsub_root.a ui/libsub_ui.a core/libsub_core.a display/libsub_display.a input/libsub_input.a rpc/libsub_rpc.a utils/libsub_utils.a  -lncursesw -l>
libtool: link: g++ -w -O2 -flto=12 -o rtorrent main.o  libsub_root.a ui/libsub_ui.a core/libsub_core.a display/libsub_display.a input/libsub_input.a rpc/libsub_rpc.a utils/libsub_utils.a -lncursesw -ltinfo -lcppunit -L/usr/local/lib /us>
lto1: fatal error: bytecode stream in file '/usr/local/lib/libcurl.a' generated with LTO version 11.3 instead of the expected 12.0
compilation terminated.
lto-wrapper: fatal error: g++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:563: rtorrent] Error 1
make[3]: Leaving directory '/tmp/rtorrent/src'
make[2]: *** [Makefile:634: all-recursive] Error 1
make[2]: Leaving directory '/tmp/rtorrent/src'
make[1]: *** [Makefile:453: all-recursive] Error 1
make[1]: Leaving directory '/tmp/rtorrent'
make: *** [Makefile:385: all] Error 2
^[[2m[Mon Jul 17 22:46:58]^[(B^[[m ^[[31m^[[1mERROR     Something went wrong while making rtorrent^[(B^[[m
^[[2m[Mon Jul 17 22:46:58]^[(B^[[m ^[[31m^[[3m  Please consult the above and/or check the log (less -R +G /root/logs/swizzin.log)^[(B^[[m
```

**Comment by liaralabs** [comment]
Can you please

```
sudo rm /usr/local/lib/libcurl.a
```

And try upgrading again. I suspect this is due to our recent change to build curl as a shared library. The libcurl.a file is now cruft and probably requires a manual clean-up from our end

**Comment by csy7550** [comment]
I will try, but any special precautions since I'm now running the repo version? In the back of my mind I think I have read there is?

**Comment by liaralabs** [comment]
It's safe to remove this file now and just re-run the upgrade script - the .a file needs to be linked during compile time and is otherwise just a compiled object which isn't actively linked since it gets pulled in at compile time

**Comment by csy7550** [comment]
ar cru libsub_root.a command_download.o command_dynamic.o command_events.o command_file.o command_ip.o command_helpers.o command_groups.o command_local.o command_logging.o command_network.o command_peer.o command_throttle.o command_trac>
ar: `u' modifier ignored since `D' is the default (see `U')
ranlib libsub_root.a
/bin/bash ../libtool  --tag=CXX   --mode=link g++  -w -O2 -flto=12     -o rtorrent main.o libsub_root.a ui/libsub_ui.a core/libsub_core.a display/libsub_display.a input/libsub_input.a rpc/libsub_rpc.a utils/libsub_utils.a  -lncursesw -l>
libtool: link: g++ -w -O2 -flto=12 -o rtorrent main.o  libsub_root.a ui/libsub_ui.a core/libsub_core.a display/libsub_display.a input/libsub_input.a rpc/libsub_rpc.a utils/libsub_utils.a -lncursesw -ltinfo -lcppunit -L/usr/local/lib /us>
/usr/bin/ld: cannot find /usr/local/lib/libcurl.a: No such file or directory
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:568: rtorrent] Error 1
make[3]: Leaving directory '/tmp/rtorrent/src'
make[2]: *** [Makefile:639: all-recursive] Error 1
make[2]: Leaving directory '/tmp/rtorrent/src'
make[1]: *** [Makefile:458: all-recursive] Error 1
make[1]: Leaving directory '/tmp/rtorrent'
make: *** [Makefile:390: all] Error 2
^[[2m[Wed Jul 19 21:52:02]^[(B^[[m ^[[31m^[[1mERROR     Something went wrong while making rtorrent^[(B^[[m
^[[2m[Wed Jul 19 21:52:02]^[(B^[[m ^[[31m^[[3m  Please consult the above and/or check the log (less -R +G /root/logs/swizzin.log)^[(B^[[m

**Comment by liaralabs** [comment]
Can you share the contents of:

```
cat /usr/local/lib/pkgconfig/libcurl.pc
```

And a

```
ls -la /usr/local/lib
```

**Comment by csy7550** [comment]
libcurl.pc:

> prefix=/usr/local
> exec_prefix=${prefix}
> libdir=/usr/local/lib
> includedir=${prefix}/include
> supported_protocols="DICT FILE FTP FTPS GOPHER GOPHERS HTTP HTTPS IMAP IMAPS LDAP LDAPS MQTT POP3 POP3S RTSP SCP SFTP SMB SMBS SMTP SMTPS TELNET TFTP WS WSS"
> supported_features="SSL IPv6 unixsockets libz brotli zstd AsynchDNS IDN Largefile alt-svc HSTS NTLM HTTP2 HTTPS-proxy threadsafe PSL"
> 
> Name: libcurl
> URL: https://curl.se/
> Description: Library to transfer files with ftp, http, etc.
> Version: 7.88.1
> Libs: -L${libdir} -lcurl
> Libs.private:  -lgcc -lgcc_s -lc -lgcc -lgcc_s -lidn2 -llber -lldap /usr/local/lib/libcares.so /usr/lib/x86_64-linux-gnu/libssl.so /usr/lib/x86_64-linux-gnu/libcrypto.so /usr/lib/x86_64-linux-gnu/libnghttp2.so /usr/lib/x86_64-linux-gnu/libz.so /usr/lib/x86_64-linux-gnu/libbrotlicommon.so /usr/lib/x86_64-linux-gnu/libbrotlidec.so /usr/lib/x86_64-linux-gnu/libzstd.so /usr/lib/x86_64-linux-gnu/libpsl.so /usr/lib/x86_64-linux-gnu/libssh2.so
> Cflags: -I${includedir}

/usr/local/lib:

> 
> drwxr-xr-x  4 root root   4096 Jul 17 21:26 cmake
> lrwxrwxrwx  1 root root     13 Jul 17 21:25 libcares.so -> libcares.so.2
> lrwxrwxrwx  1 root root     17 Jul 17 21:25 libcares.so.2 -> libcares.so.2.6.1
> -rw-r--r--  1 root root 120360 Jul 19 21:49 libcares.so.2.6.1
> -rw-r--r--  1 root root 867312 Jul 19 21:49 libcares_static.a
> -rwxr-xr-x  1 root root    996 May  9 10:36 libcurl.la
> lrwxrwxrwx  1 root root     12 Jul 17 21:26 libcurl.so -> libcurl.so.4
> lrwxrwxrwx  1 root root     16 Jul 17 21:26 libcurl.so.4 -> libcurl.so.4.8.0
> -rw-r--r--  1 root root 853920 Jul 19 21:50 libcurl.so.4.8.0
> drwxr-xr-x  2 root root   4096 Jul 19 21:50 pkgconfig
> drwxr-xr-x  3 root root   4096 Feb 17 18:23 python3.10

**Comment by stickz** [comment]
This looks like a gcc issue. Can you share the output of `gcc --version` and `g++ --version`.

**Comment by stickz** [comment]
You need to do `sudo rm /usr/local/lib/libcurl.la`. Afterwards, it will be safe to run `box upgrade curl`. Please share output of `ls -la /usr/local/lib` again finally. Then try `box upgrade rtorrent` again. 

We need to cleanup `libcurl.la` when building `curl`.  The user had GCC upgraded and still had old linker data from GCC 11.

**Comment by csy7550** [comment]
gcc --version:

> gcc (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
> Copyright (C) 2022 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

g++ --version:

> g++ (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
> Copyright (C) 2022 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

output of /usr/local/lib after rm libcurl.la and box upgrade curl:

> drwxr-xr-x  5 root root   4096 Jul 20 19:08 .
> drwxr-xr-x 10 root root   4096 Feb 17 18:19 ..
> drwxr-xr-x  4 root root   4096 Jul 17 21:26 cmake
> lrwxrwxrwx  1 root root     13 Jul 17 21:25 libcares.so -> libcares.so.2
> lrwxrwxrwx  1 root root     17 Jul 17 21:25 libcares.so.2 -> libcares.so.2.6.1
> -rw-r--r--  1 root root 120360 Jul 20 19:07 libcares.so.2.6.1
> -rw-r--r--  1 root root 867184 Jul 20 19:07 libcares_static.a
> lrwxrwxrwx  1 root root     12 Jul 17 21:26 libcurl.so -> libcurl.so.4
> lrwxrwxrwx  1 root root     16 Jul 17 21:26 libcurl.so.4 -> libcurl.so.4.8.0
> -rw-r--r--  1 root root 853920 Jul 20 19:08 libcurl.so.4.8.0
> drwxr-xr-x  2 root root   4096 Jul 20 19:08 pkgconfig
> drwxr-xr-x  3 root root   4096 Feb 17 18:23 python3.10

box upgrade rtorrent:

> ...     Building rtorrent from source ...
>         ✔   Done

Working!

**Comment by GitHub-BumBleBee** [comment]
ERROR:Something went wrong while making rtorrent
	Please consult the above and/or check the log (less -R +G 
	/root/logs/swizzin.log

**Comment by GitHub-BumBleBee** [comment]
Mine is like that. LOG is in the clouds..

https://mega.nz/file/m5UgHK4J#KK8wrsPdaxiQ5uFNH-uxzXo_vSxbSQclM3KoSo40xs8

**Comment by GitHub-BumBleBee** [comment]
@stickz ............. I followed your steps and it worked here, but it stayed in version v4.1.6..

**Comment by stickz** [comment]
> @stickz ............. I followed your steps and it worked here, but it stayed in version v4.1.6..

`box remove rutorrent` then `box install rutorrent` be prepared to lose any saved settings and RSS feeds. Torrents will remain unaffected.

**Comment by GitHub-BumBleBee** [comment]
@stickz ........ I did that and it went back to default settings, but still v4.1.6

**Comment by GitHub-BumBleBee** [comment]
@stickz ... When I try to update, it just stays like this.

box update
...	Updating swizzin local repository
	✔   Local repository updated using: master
INFO	HEAD is now set to 0acf022
...	Setting correct permissions on swizzin files
	✔   Permissions set
...	Updating config for PHP 8.1
	✔   Done
...	Updating fancyindex theme
	✔   Done
...	Updating fancyindex footer
	✔   Done
...	Fixing nginx for recursive configs
	✔   Done
...	Restarting php-fpm and nginx
	✔   Done
...	Downloading latest panel commits
	✔   Commits pulled
...	Checking pip for new panel dependencies
	✔   Depends up-to-date
...	Restarting Panel
	✔   Done!

**Comment by GitHub-BumBleBee** [comment]
@stickz ......... When will I do what you asked with rutorrrent.


bumblebee@bumblebee-Latitude-5280:~$ sudo -s
[sudo] senha para bumblebee: 
root@bumblebee-Latitude-5280:/home/bumblebee# box remove rutorrent
INFO	Removing rutorrent
SUCCESS	rutorrent removed
...	Cleaning up apt clutter
	✔   Apt autoremove complete
root@bumblebee-Latitude-5280:/home/bumblebee# box install rutorrent
INFO	Installing rutorrent
DOCS	Further reference: 
	https://swizzin.ltd/applications/rutorrent
...	Cloning ruTorrent
	✔   ruTorrent cloned
...	Cloning some popular themes and plugins
	✔   Plugins downloaded
...	Reloading nginx
	✔   Done
...	Installing ffmpeg for ruTorrent
SUCCESS	ruTorrent installed

**Comment by GitHub-BumBleBee** [comment]
Now he has updated the version, but he is not getting my IP.

https://i.postimg.cc/fbWw8rm9/ERRO-IP.png
