### ISSUE TITLE
Can't log in to panel

### ISSUE THREAD

**Issue by darkalchemy** [swizzin/swizzin#1050]
### What happened?

Steps to reproduce:

1. Fresh install on debian 12
2. Go to local user@ip
3. try to login

Expected results:
log in

I created 2 users, passwords are correct and neither can log in to panel. First attempt you get the login page, then goes to a pop up log in. After a few tries, you get throttled.

### Swizzin commit

0acf022

### What OS are you using?

Debian 12 (Bookworm)

### What architecture is your OS?

amd64

**Comment by liaralabs** [comment]
This is frequently caused by things like very specific special characters in your password (i.e. spaces, dollar signs and single/double quotes).

Can you verify if any special characters are in use? If so, please test with an alphanumeric-only password

**Comment by darkalchemy** [comment]
It's just letters and numbers.

**Comment by darkalchemy** [comment]
I just reset the passwords to 's!mple' and it still would not log in.

**Comment by liaralabs** [comment]
Can you disable forms login as per the panel settings? https://swizzin.ltd/applications/panel#configuration-options

Alternatively, try an incognito session and ensure ***no extensions or plugins*** are enabled. Certain extensions have been known to interfere with the hacks that the swizzin dash uses for the forms authentication

**Comment by darkalchemy** [comment]
i disabled forms login, restart panel and it goes straight to the popup login. I disabled all extensions in a private window and same result. If I go straight to rutorrent, the log in works.

**Comment by liaralabs** [comment]
>  it goes straight to the popup login. I disabled all extensions in a private window and same result

Sorry do you mean to say the pop up appears, you enter the details and the popup appears again?

Can you provide any of the logging output from the bottom of `journalctl -u panel`?

**Comment by darkalchemy** [comment]
```
Sorry do you mean to say the pop up appears, you enter the details and the popup appears again?
```
yes

```
Jul 31 15:45:32 rTorrent systemd[1]: Stopping panel.service - swizzin panel service...
Jul 31 15:45:32 rTorrent systemd[1]: panel.service: Deactivated successfully.
Jul 31 15:45:32 rTorrent systemd[1]: Stopped panel.service - swizzin panel service.
Jul 31 15:45:32 rTorrent systemd[1]: panel.service: Consumed 1.246s CPU time.
Jul 31 15:45:32 rTorrent systemd[1]: Started panel.service - swizzin panel service.
Jul 31 15:45:34 rTorrent python[20002]: /opt/.venv/swizzin/lib/python3.11/site-packages/flask_limiter/extension.py:293: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified>
Jul 31 15:45:34 rTorrent python[20002]:   warnings.warn(
Jul 31 15:45:40 rTorrent python[20002]: WARNING:core.htpasswd:Invalid login from jonnyboy at 10.0.0.48
Jul 31 15:45:57 rTorrent python[20002]: WARNING:core.htpasswd:Invalid login from jonnyboy at 10.0.0.48
```

**Comment by darkalchemy** [comment]
I just re-enabled forms login and the login worked. I changed the password back and still works. I don't know what fixed it, but it appears fixed.

Thanks

**Comment by darkalchemy** [comment]
I re-installed and the same error once more. I think that I found the issue. When the installation completes, it points to the url for that user, https://jonnyboy@10.0.0.160 that doesn't work, login fails every time. But, remove the 'jonnyboy@' and login works as you would expect.

So, maybe just need to update the url provided after install completes and when add user?

Thanks

**Comment by Siyuan-Zheng** [comment]
I encountered the same problem. After the installation was completed, I opening user@ip in the browser and finish log in, but a secondary login pop-up window appeared. In this pop-up window, the login failed using the username and password whitch install shell created. But when i use the `sudo systemctl restart panel` command to restart the panel service and log in again, the secondary login pop-up window will not appear again.

**Comment by liaralabs** [comment]
This is unfortunately a somewhat recent change in how browsers handle these basic auth URLs. This used to not cause issues but now does. You are correct that we should likely remove the user@ip notation.

We used to supply the user:password@ip notation which most browsers also stopped accepting as valid :roll_eyes:
