### ISSUE TITLE
[BUG] Calibreweb Nginx configuration doesn't work for IPv6

### ISSUE THREAD

**Issue by Irishsmurf** [swizzin/swizzin#1071]
#### Steps to reproduce:

1. Install nginx.
   * `box install nginx`
2. Install CalibreWeb
    * `box install calibreweb`  
3. Attempt to load `https://<website>/calibreweb` from an IPv6 Address
5. `500 Internal Error`
    * From Nginx Error logs: 
    * ```
       2023/09/08 16:45:16 [crit] 2382422#2382422: *490 bind(<IPv6 IP ADDRESS>) failed (97: Address family not supported by 
       protocol) while connecting to upstream, client: <IPv6 IP ADDRESS>, server: <SERVER HOSTNAME>, 
       request: "GET /calibreweb HTTP/2.0", upstream: "http://127.0.0.1:8083/calibreweb", host: "<SERVER HOSTNAME>", referrer: 
       "https://<SERVER HOSTNAME>/"
       ```

#### Expected results:

Page loads.

#### Results occur:

CalibreWeb is inaccessible if the client is using IPv6.

---

I fixed this by modifying the nginx configuration in `calibreweb.conf` to:

```conf
location /calibreweb {
        proxy_pass              http://127.0.0.1:8083;
        proxy_set_header        Host $proxy_host;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Host $host;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_http_version      1.1;
        proxy_set_header        Upgrade $http_upgrade;
        proxy_set_header        Connection $http_connection;

        proxy_set_header        X-Scheme        $scheme;
        proxy_set_header        X-Script-Name   /calibreweb;  # IMPORTANT: path has NO trailing slash
}
```

### Swizzin commit

9dc0c50

### What OS are you using?

Debian 10 (Buster)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
2023/09/08 16:45:16 [crit] 2382422#2382422: *490 bind(<IPv6 IP ADDRESS>) failed (97: Address family not supported by 
       protocol) while connecting to upstream, client: <IPv6 IP ADDRESS>, server: <SERVER HOSTNAME>, 
       request: "GET /calibreweb HTTP/2.0", upstream: "http://127.0.0.1:8083/calibreweb", host: "<SERVER HOSTNAME>", referrer: 
       "https://<SERVER HOSTNAME>/"
```

**Comment by liaralabs** [comment]
```
        proxy_set_header        Upgrade $http_upgrade;
        proxy_set_header        Connection $http_connection;
```

Shouldn't be necessary -- these are for websocket upgrades, which I don't think calibre web makes use of.

It looks like the magic happens in translating
```
proxy_set_header        Host            $http_host;
```
to 
```
proxy_set_header        Host $proxy_host;
```
And potentially adding the X-Forwarded-Host (though that mostly depends on whether calbre web even cares about this header)

**Comment by Irishsmurf** [comment]
Turns out it's not the Host header - http_host/proxy_host are essentially the same. \
It's the `proxy_bind` bit - where with IPv6, Nginx binds to `$server_addr`, which will be an IPv6 address - and then attempts to talk to the upstream address on `127.0.0.1` - which is IPv4.

This doesn't work, and it fails.
