### ISSUE TITLE
[BUG] Can't change the timeout Nginx configuration

### ISSUE THREAD

**Issue by Jewem** [swizzin/swizzin#1094]
### What happened?

I'm using Sonarr and since Flaresolver is installed, my requests on Sonarr doesn't works.
I have a bug for time out request.

Unable to load results for this episode search. Try again later.

How can i  change the timeout setting in swizzin Nginx ?

No problms with Radarr.

### Swizzin commit

5253f36

### What OS are you using?

Debian 12 (Bookworm)

### What architecture is your OS?

amd64

**Comment by brettpetch** [comment]
This is not a bug and flaresolverr is not an application we support.
