### ISSUE TITLE
[BUG] sudoers update script fails because of users in htaccess

### ISSUE THREAD

**Issue by EdTheLoon** [swizzin/swizzin#1097]
### What happened?

Steps to reproduce:

1. Use `sudo htpasswd /etc/htpasswd testuser` to add a password hash for 'testuser'
2. Run `sudo box update`

Expected results:
Updates with no errors.

Actual results:
Updates but produces errors to do with sudoers. It is trying to read the sudo file of a non-existent user. 

Of course I could just remove the user from the htaccess file or use different htaccess files for my purposes but I shouldn't have to.

This is the script causing the errors: [update/sudoers.sh](https://github.com/swizzin/swizzin/blob/master/scripts/update/sudoers.sh)

### Swizzin commit

5253f36

### What OS are you using?

Ubuntu 22.04 (Jammy)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
$ box update
tput: unknown terminfo capability 'ZH'
tput: unknown terminfo capability 'ZR'
...     Updating swizzin local repository
        ✔   Local repository updated using: master
INFO    HEAD is now set to 5253f36
tput: unknown terminfo capability 'ZH'
tput: unknown terminfo capability 'ZR'
...     Setting correct permissions on swizzin files
        ✔   Permissions set
...     Performing installation of 1 apt packages
        (php-opcache)
        ✔   Apt install complete
...     Updating config for PHP 8.1
        ✔   Done
...     Updating fancyindex theme
        ✔   Done
...     Updating fancyindex footer
        ✔   Done
...     Fixing nginx for recursive configs
        ✔   Done
...     Restarting php-fpm and nginx
        ✔   Done
...     Downloading latest panel commits
        ✔   Commits pulled
...     Checking pip for new panel dependencies
        ✔   Depends up-to-date
...     Restarting Panel
        ✔   Done!
grep: /etc/sudoers.d/testuser: No such file or directory
grep: /etc/sudoers.d/testuser: No such file or directory
INFO    Adding flood sudo permissions for testuser
sed: can't read /etc/sudoers.d/testuser: No such file or directory
```

**Comment by liaralabs** [comment]
Not likely a fix forthcoming here. I would suggest you manage your own htaccess file under a different file name if you have unique needs for user access -- one that isn't parsed by the update scripts and used as a source of truth for the swizzin-managed users.

You will run into other issues as well as applications like deluge use the remote user to determine which port to send traffic to. Without an actual user backing this web user, more things will break

**Comment by EdTheLoon** [comment]
Noted your response. Thank you for the further insight. Closing.
