### ISSUE TITLE
Unable to authenticate to Panel through Public IP[BUG] 

### ISSUE THREAD

**Issue by edsanchez07** [swizzin/swizzin#1107]
### What happened?

Steps to reproduce:

1. Install package 'Latest'
2. Go to 'Panel'
3. Error 'If I try to access the panel through my public IP or DNS I can't pass the authentication page, after providing the credentials it keeps asking for the same'

Expected results: Should be able to login like I do with local IP

### Swizzin commit

5253f36

### What OS are you using?

Ubuntu 22.04 (Jammy)

### What architecture is your OS?

amd64

**Comment by liaralabs** [comment]
Did you also post in Discord and have a port forward on your router that isn't the standard 443 port?

**Comment by liaralabs** [comment]
This port forward is likely the source of the issue. The forms login method is extremely hacky and only works on port 443.

You can try disabling the forms auth in the panel options and fall back to the true basic auth.

Otherwise, if you can temporarily use port 443 as a port forward in your firewall as a point of debugging, you can get a clear image for yourself if the port forward is indeed the source of your issues (but I assume it likely is)

**Comment by edsanchez07** [comment]
> This port forward is likely the source of the issue. The forms login method is extremely hacky and only works on port 443.
> 
> You can try disabling the forms auth in the panel options and fall back to the true basic auth.
> 
> Otherwise, if you can temporarily use port 443 as a port forward in your firewall as a point of debugging, you can get a clear image for yourself if the port forward is indeed the source of your issues (but I assume it likely is)

Yes, it looks like it works with the 443. So, I tried your recommendation about disabling the Forms Auth, but it's not working, not sure if I am using the correct variable: 

FORMS_LOGIN = 'False'

It's that the right format? 

Thanks for the help!

**Comment by liaralabs** [comment]
Give it a try without the quotes. You've turned false into a string by using quotes and it should be a boolean if unquoted.

**Comment by edsanchez07** [comment]
> Give it a try without the quotes. You've turned false into a string by using quotes and it should be a boolean if unquoted.

Oh well that solved the issue! Thanks for the quick help and response!!
