### ISSUE TITLE
[BUG] QBittorrent installation fails

### ISSUE THREAD

**Issue by hdecx** [swizzin/swizzin#1108]
### What happened?

Steps to reproduce:

1. On Ubuntu 20.04 and 22.04; choose to install qBittorrent either via installer script or command `box`.
2. Installation fails with following log message.

```
/etc/swizzin/sources/functions/qbittorrent: line 440: fpm: command not found
dpkg: error: cannot access archive '/root/dist/libtorrent-rasterbar_1.2.19.deb': No such file or directory
[Sat Dec 16 04:18:24]^O ERROR   Libtorrent could not be installed. Setup will not proceed^O
[Sat Dec 16 04:18:24]^O         Please consult the above and/or check the log (less -R +G /root/logs/swizzin.log)^O
[Sat Dec 16 04:18:24]^O INFO    Package installation took 8 minutes and 3 seconds^O
[Sat Dec 16 04:18:24]^O SUCCESS Swizzin installation complete!^O
```

fpm was not configured properly and command not found. Running the following installs fpm correctly.

```
sudo gem i fpm -f
```

After this, installation is successful.

```
INFO    Installing qbittorrent
...     Building libtorrent-rasterbar
        ✔   Build completed
...     Installing latest qt6-swizzin
        ✔   qt6-swizzin installed
...     Building qBittorrent
...     Performing installation of 10 apt packages
        (libgeoip-dev libicu6* libicu-dev libiconv-hook-dev libdouble-conversion3 libdouble-conversion-dev libmd4c0 libmd4c-dev libmd4c-html0 libmd4c-html0-dev)
        ✔   Apt install complete
        ✔   Done
...     Enabling qbittorrent for nerd
        ✔   Started qbt for nerd
...     Configuring nginx
        ✔   Done
```

### Swizzin commit

5253f36

### What OS are you using?

Ubuntu 22.04 (Jammy)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
﻿
```

**Comment by siedenburg2** [comment]
For general Information:
I bumped libtorrent-rasterbar in the 4.6 script to 1.2.19 because it's listed on the qbit site
>libtorrent-rasterbar | 1.2.19+gitfda40ea66b / 2.0.9+git9c18976452

That could have broken the install on your device, on my Debian test setup everything is working, that's one thing that could be checked by others (or me if I have time)

**Comment by siedenburg2** [comment]
Tested it with an up to date Ubuntu 22-04 and couln't replicate your problem, but found that the main download site for boost in the libtorrent install is offline

**Comment by DogFoxX** [comment]
I had a similar issue where the terminal would just close at `Building libtorrent-rasterbar` with no error displayed. @hdecx 's solution seemed to work.

**Comment by liaralabs** [comment]
Please re-open this issue if you're still facing it. I do not believe new installs are currently facing this bug.
