### ISSUE TITLE
RSS [BUG] 

### ISSUE THREAD

**Issue by MoBit65** [swizzin/swizzin#1151]
### What happened?

Hi
I mistakenly deleted RSS from the box.
When I try to install again, this message is displayed.
please guide me.

INFO    Installing rss
svn: E170013: Unable to connect to a repository at URL 'https://github.com/Novik/ruTorrent.git/tags/v4.2.10/plugins/rss'
svn: E160013: '/Novik/ruTorrent.git/tags/v4.2.10/plugins/rss' path not found

### Swizzin commit

9a23fc3

### What OS are you using?

Ubuntu 22.04 (Jammy)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
INFO    Installing rss
svn: E170013: Unable to connect to a repository at URL 'https://github.com/Novik/ruTorrent.git/tags/v4.2.10/plugins/rss'
svn: E160013: '/Novik/ruTorrent.git/tags/v4.2.10/plugins/rss' path not found
```

**Comment by stickz** [comment]
`box remove rutorrent` then `box install rutorrent`. This is the only way right now. `box rtx` doesn't work properly at this time.

**Comment by MoBit65** [comment]
Thank you stickz
Problem solved
