### ISSUE TITLE
[BUG] Letsencrypt (SSL PROBLEM)

### ISSUE THREAD

**Issue by gandalf764** [swizzin/swizzin#1167]
### What happened?

 I wanted to inform you that I've successfully registered a CSSL certificate using Let's Encrypt, and the process went smoothly. However, I've encountered an issue regarding the validity of the certificate on different services.

When I access the domain, the Swizzin panel opens with a valid certificate, indicating that the SSL certificate is functioning correctly. Yet, when I attempt to access Tautulli afterward, the certificate remains valid. However, when trying to access Plex, it presents an error indicating an expired certificate. It seems like Plex is using an outdated certificate.

Could you please assist me in resolving this issue with Plex? I've checked the configurations, and everything seems to be in order, but the problem persists. Any guidance or support you could provide in resolving this discrepancy would be greatly appreciated.

Thank you for your attention to this matter.

### Swizzin commit

953e4c7

### What OS are you using?

Debian 11 (Bullseye)

### What architecture is your OS?

amd64

**Comment by liaralabs** [comment]
Duplicate #793
