### ISSUE TITLE
[BUG]  Password did not pass cracklib check.

### ISSUE THREAD

**Issue by titis14** [swizzin/swizzin#1181]
### What happened?

Steps to reproduce:

hello,
I installed Debian then started the installation with the command "bash <(wget -qO - s5n.sh) && . ~/.bashrc" but impossible to put a password.
I tried several passwords of 20 characters, with uppercase, lowercase, numbers and 5 special characters I always have the message "Password did not pass cracklib check. Reason: "" "
I even generated a code by leaving the field empty still the same.
Thanks for your help.

### Swizzin commit

no installed

### What OS are you using?

Debian 12 (Bookworm)

### What architecture is your OS?

amd64

**Comment by liaralabs** [comment]
[Please see the note in the readme](https://github.com/swizzin/swizzin?tab=readme-ov-file#you-cant-tell-me-how-to-su-su-vs-su--)

**Comment by titis14** [comment]
Thanks it's OK with "su -". ​​Sorry I did some research but I didn't find this link.
