### ISSUE TITLE
Jellyfin doesn't work with intel gpu transcoding via vaapi

### ISSUE THREAD

**Issue by aflameinfinity** [swizzin/swizzin#365]
## Bug description
Using jellyfin for hardware transcode doesn't work.

## Reproduction steps
Use builtin intel graphics(this is my server hardware).

1. `box install jellyfin`
1. enable vaapi decoding.
1. play a file

## Expected behavior
It should use gpu to encode.

Problem is the script here installs the latest ffmpeg(4.3), and they change some parameters for hardware transcode.
Jellyfin had to adopt to this first but it doesn't work at the moment.

Options:
* Use distro ffmpeg, most distro have ffmpeg version up to 4.2, which base on my testing works.
* Use the their [repository](https://jellyfin.org/docs/general/administration/installing.html#ubuntu-repository), they also package their own ffmpeg. This is what I ended up doing since I hope they test the compatibility before packaging it.

**Comment by flying-sausages** [comment]
https://github.com/liaralabs/swizzin/blob/master/scripts/install/ffmpeg.sh

We already only install distribution-supplied `ffmpeg`. If you'd fill the issue template we could troubleshoot this further.

**Comment by aflameinfinity** [comment]
@flying-sausages there's this as well: https://github.com/liaralabs/swizzin/blob/master/scripts/install/jellyfin.sh#L59

But you are right, I can also just change the ffmpeg to use the distro one.

Sorry if I didn't fill the full issue template, I thought the issue was simple enough, I'll keep that in mind in the future.

**Comment by liaralabs** [comment]
Jellyfin needs to be reworked to use `jellyfin-ffmpeg` and potentially to simply use the debian/ubuntu repos which are already available and ship `jellyfin-ffmpeg`. The main issue (as already noted) is that the statically compiled version that was pulled in during the installer doesn't support HW offloading.

In the interim, the distro version of ffmpeg should work as well.

**Comment by userdocs** [comment]
The issue as i understand it, based on the info provided here is that version 4.3 has updated api call that need to be implemented in jellyfin but version 4.2 works fine.

There are older versions available allowing the selection 4.2

https://www.johnvansickle.com/ffmpeg/old-releases/

You should test this version:

https://www.johnvansickle.com/ffmpeg/old-releases/ffmpeg-4.2.2-amd64-static.tar.xz

**Comment by flying-sausages** [comment]
Should be fixed in the PR above. When it gets merged, this should close automatically
