### ISSUE TITLE
Nextcloud 20.0.0 to 20.0.1 update fails (stable channel)

### ISSUE THREAD

**Issue by servingworlds** [swizzin/swizzin#444]
##Bug description
Update fails when attempting to use internal updater to Nextcloud.

##Reproduction steps

Clicking Update inside Nextcloud app located at /nextcloud/settings/admin/overview#

##Expected behavior
Installation script will display process in window until complete

##Server Info
-OS Debian 10 Buster
-vanilla install from Hetzner of Buster
-ran install script for swizzin from https://swizzin.ltd/getting-started

##Is Swizzin up to date?
Box update performed.
Reports:
Already on 'master'
Your branch is up to date with 'origin/master'.
From https://github.com/liaralabs/swizzin

branch master -> FETCH_HEAD
HEAD is now at 3b0d696 Redirect noisy panel upgrade outputs
INFO HEAD is now set to 3b0d696
✔ Local repository updated
Warning: apt-key output should not be parsed (stdout is not a terminal)
A236C58F409091A18ACA53CBEBFF6B99D9B78493
... Updating panel to latest version
... Pulling new commits
✔ Commits pulled
... Checking pip for new depends
✔ Depends up-to-date
... Restarting Panel
✔ Done!
✔ Done

##Additional context
Error occurs when attempting app-recommended update from Version 20.0.0 to 20.0.1

When update attempted:

Initializing
Current version is 20.0.0.
Update to Nextcloud 20.0.1 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-20.0.1.zip

Error fails as follows:

Retry update
Check for expected files
The following extra files have been found:
-assets

## Reproduction steps
1. Follow guide to perform update inside Nextcloud app 
2. Initialize update process
3. See error

## Installed applications through swizzin
Nextcloud
Filebrowser
Jellyfin
Syncthing
Console

## Expected behavior

Access Updater
Initialize Process
Update file is downloaded
Check for write permissions
Create backup
Downloading
Verifying integrity
Extracting
Enable maintenance mode
Replace entry points
Delete old files
Move new files in place
Disable maintenance mode
'Done' message displays

## Server Info
**(please complete the following information):**
 - OS: (e.g. Debian 10, Ubuntu 20.04)
 - Image Source: (e.g. "Vanilla download" or "Installscript from specific provider")

**Comment by liaralabs** [comment]
Sorry you're having issues with the autobot -- typically you must leave all the headers completely intact without touching/removing any entries to not have your issue auto-closed.

That said, this issue isn't likely with swizzin directly. Most reports state that you should be able to just remove the offending directory and the update will continue:

https://help.nextcloud.com/t/the-following-extra-files-have-been-found-assets/21026

`/srv/nextcloud` is the nextcloud base where this folder will be located. You can move/back it up rather than deleting it to make sure that it's not required so you have it in the even that something messes up.

**Comment by servingworlds** [comment]
Thank you! I feel a lot more secure with my family's stuff on swizzin after you reached out :)

The update did continue after I removed the offending file, but at the next step there's a permissions error for a series of folders

Do I need to do this from box or...?

Again, thank you so much. I'm happy to try again to file a ticket but as a user apparently I'm missing some strictures in my training :)

Check for write permissions
The following places can not be written to:
* /srv/nextcloud/updater/../COPYING
* /srv/nextcloud/updater/../.htaccess
* /srv/nextcloud/updater/../index.html
* /srv/nextcloud/updater/../.user.ini
* /srv/nextcloud/updater/../AUTHORS
* /srv/nextcloud/updater/../version.php
* /srv/nextcloud/updater/../console.php
* /srv/nextcloud/updater/../public.php
* /srv/nextcloud/updater/../status.php
* /srv/nextcloud/updater/../remote.php
* /srv/nextcloud/updater/../index.php
* /srv/nextcloud/updater/../occ
* /srv/nextcloud/updater/../robots.txt
* /srv/nextcloud/updater/../cron.php

Nov 2, 2020 12:37:08 PM liaralabs <notifications@github.com>:

**Comment by liaralabs** [comment]
Interesting -- not sure if any permissions have been changed from the original nextcloud install performed by swizzin

Can you do an `ls -la` of `/srv/nextcloud` and post the results?

`/srv/nextcloud` and all it's contents and sub-dirs should be owned by `www-data`

**Comment by servingworlds** [comment]
Sure, and thanks again for helping.

/srv/nextcloud$ ls -la                                                                                          
total 168                                                                                                                 
drwxr-x--- 14 root     www-data  4096 Nov  2 18:55 .
drwxr-xr-x  5 root     root      4096 Nov  2 18:55 ..
drwxr-x--- 41 root     www-data  4096 Oct  2 18:51 3rdparty
drwxr-x--- 62 www-data www-data  4096 Oct 28 15:56 apps
-rw-r-----  1 root     www-data 17234 Oct  2 18:49 AUTHORS                                                                
drwxr-x---  2 www-data www-data  4096 Oct  8 16:52 config
-rw-r-----  1 root     www-data  3967 Oct  2 18:49 console.php                                                            
-rw-r-----  1 root     www-data 34520 Oct  2 18:49 COPYING                                                                
drwxr-x--- 22 root     www-data  4096 Oct  2 18:51 core
-rw-r-----  1 root     www-data  5140 Oct  2 18:49 cron.php                                                               
drwxr-x--- 11 www-data www-data  4096 Oct 30 14:32 data
-rw-r--r--  1 root     www-data  3032 Oct  2 18:49 .htaccess                                                              
-rw-r-----  1 root     www-data   156 Oct  2 18:49 index.html                                                             
-rw-r-----  1 root     www-data  2960 Oct  2 18:49 index.php                                                              
drwxr-x---  6 root     www-data  4096 Oct  2 18:49 lib
-rwxr-x--x  1 root     www-data   283 Oct  2 18:49 occ
drwxr-x---  2 root     www-data  4096 Oct  2 18:49 ocm-provider
drwxr-x---  2 root     www-data  4096 Oct  2 18:49 ocs
drwxr-x---  2 root     www-data  4096 Oct  2 18:49 ocs-provider
-rw-r-----  1 root     www-data  3102 Oct  2 18:49 public.php                                                             
-rw-r-----  1 root     www-data  5332 Oct  2 18:49 remote.php                                                             
drwxr-x---  4 root     www-data  4096 Oct  2 18:49 resources
-rw-r-----  1 root     www-data    26 Oct  2 18:49 robots.txt                                                             
drwxr-x---  3 www-data www-data  4096 Oct  2 18:49 themes.php                                                             
                                                                                                                          
drwxr-x---  2 www-data www-data  4096 Oct  2 18:50 updater
-rw-r-----  1 root     www-data   362 Oct  2 18:51 version.php

**Comment by liaralabs** [comment]
For future reference if you enclose code blocks within three \`\`\`  (one on each end) you can format the code nicely in markdown.

It's been a while since I wrote the nextcloud install script, but it looks like the permissions in NC have been set according to their "secure" permissions preferences.

You can issue:

```
sudo chown -R www-data: /srv/nextcloud
```

Which should allow you to perform the update. If you want to revert to the recommended secure permissions after updating, you can rerun the snippet here from the install script:

```
ocpath='/srv/nextcloud'
htuser='www-data'
htgroup='www-data'
rootuser='root'

mkdir -p $ocpath/data
mkdir -p $ocpath/updater
find ${ocpath}/ -type f -print0 | xargs -0 chmod 0640
find ${ocpath}/ -type d -print0 | xargs -0 chmod 0750
chown -R ${rootuser}:${htgroup} ${ocpath}/
chown -R ${htuser}:${htgroup} ${ocpath}/apps/
chown -R ${htuser}:${htgroup} ${ocpath}/config/
chown -R ${htuser}:${htgroup} ${ocpath}/data/
chown -R ${htuser}:${htgroup} ${ocpath}/themes/
chown -R ${htuser}:${htgroup} ${ocpath}/updater/
chmod +x ${ocpath}/occ
```

Looks like this info could do well to either be put into the docs or perhaps an upgrade script for NC is in order

**Comment by servingworlds** [comment]
This worked! I am really grateful you helped even though I couldn't get the darn template right 👍 
So.... permissions have changed, huh? Just relieved. 
Thanks again, very, very much. I'm back in business!

**Comment by flying-sausages** [comment]
Did you at any point run something like `sudo php /srv/nextcloud/occ` ?

**Comment by servingworlds** [comment]
No, the box was installed, updated, upgraded, sudo user created and then I let the box do it's thing :)

Nov 2, 2020 6:15:22 PM flying-sausages <notifications@github.com>:
