### ISSUE TITLE
Organizr, Subsonic Do Not work - nzbhydra requires additional pre step

### ISSUE THREAD

**Issue by Viper911** [swizzin/swizzin#447]
## Bug description
Fresh install with Organizr and Subsonic.  One panel comes up and click on those apps

For Organizr I get:
403 Forbidden

For Subsonic, I get:
HTTP ERROR: 503
SERVICE_UNAVAILABLE
RequestURI=/subsonic

Also I figured out nzbhydra.  I had to manually install Java 15 fbefore Swizzin.  Based on issue on git for nzbhydra this is a known issue.  This also allowed Webmin and Pyload to work that did not after a clean install.  Although Webmin shows disabled and if enabled will just flip back.

## Reproduction steps
Clean install.  Nothing more.

## Installed applications through swizzin
All except Java 15

## Expected behavior
Web page for Subsonic and Organizr to work and Webmin show enabled.

## Server Info
Ubuntu 20.04
Vanilla download

## Is Swizzin up to date?
Ran update and still update (from fresh install

**Comment by flying-sausages** [comment]
Please re-open two separate issues with the appropriate logs in each.
I'm aware of the Organizr one and I need to make a fix for that soon. I'll self-assign that as soon as you make the issue.
Subsonic is something else I don't know anything about, so someone else will pick up that specific issue.
