### ISSUE TITLE
Oranizr Issue - 403 Forbidden

### ISSUE THREAD

**Issue by Viper911** [swizzin/swizzin#451]
## Bug description
Error 403 after fresh install and go to Organizr

## Reproduction steps
Fresh install of Swizzin

## Installed applications through swizzin
All, but specifically Organizer with no SSL

## Expected behavior
It works

## Server Info
Ubuntu 20.04
Vanilla download

## Is Swizzin up to date?
Yes

## Additional context
^[[2m[Sat Nov 14 17:13:16]^[(B^[[m ^[[2m...     Cloning the Organizr Repo^[(B^[[m
Cloning into '/srv/organizr'...
^[[2m[Sat Nov 14 17:13:19]^[(B^[[m      ^[[32m^[[2m:heavy_check_mark:   ^[[3mOrganizr cloned^[(B^[[m
^[[2m[Sat Nov 14 17:13:19]^[(B^[[m ^[[2m...     Configuring nginx^[(B^[[m
^[[2m[Sat Nov 14 17:13:19]^[(B^[[m      ^[[32m^[[2m:heavy_check_mark:   ^[[3mDone^[(B^[[m
^[[2m[Sat Nov 14 17:13:19]^[(B^[[m ^[[2m...     Setting up the organizr database^[(B^[[m
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
^[[2m[Sat Nov 14 17:13:21]^[(B^[[m ^[[36mLOG    Reloading OPcache^[(B^[[m
^[[2m[Sat Nov 14 17:13:21]^[(B^[[m      ^[[32m^[[2m:heavy_check_mark:   ^[[3mOrganizr database set up and configured^[(B^[[m
^[[2m[Sat Nov 14 17:13:21]^[(B^[[m ^[[33m^[[1mWARN      Remember to manually create accounts for the user(s) in Organizr!^[(B^[[m

**Comment by flying-sausages** [comment]
Organizr installs are currently broken since organizr intorudced api v2. I'm in Africa right now and will get back to this when I'm back to Europe again.
