### ISSUE TITLE
Webmin - Shows Disabled but is running

### ISSUE THREAD

**Issue by Viper911** [swizzin/swizzin#453]
##  Bug description
Fresh install of webmin.  Can get to login screen, etc, but panel shows disabled

## Reproduction steps
Do a fresh install on a fresh OS

## Expected behavior
Should show enabled

## Server Info
Ubuntu 20.04)
Vanilla download

## Is Swizzin up to date?
Yes

## Additional context
^[[2m[Sun Nov 15 13:29:40]^[(B^[[m ^[[36mLOG    Apt check returned succesfully^[(B^[[m
^[[2m[Sun Nov 15 13:29:40]^[(B^[[m ^[[36mLOG    Apt log age = 1, update is forced= ^[(B^[[m
^[[2m[Sun Nov 15 13:29:40]^[(B^[[m ^[[36mLOG     Apt sufficiently up to date, skipping^[(B^[[m
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libauthen-pam-perl libio-pty-perl
The following NEW packages will be installed:
  libauthen-pam-perl libio-pty-perl webmin
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Inst libauthen-pam-perl (0.16-3build7 Ubuntu:20.04/focal [amd64])
Inst libio-pty-perl (1:1.12-1 Ubuntu:20.04/focal [amd64])
Inst webmin (1.962 Webmin:3.1/stable [all])
Conf libauthen-pam-perl (0.16-3build7 Ubuntu:20.04/focal [amd64])
Conf libio-pty-perl (1:1.12-1 Ubuntu:20.04/focal [amd64])
Conf webmin (1.962 Webmin:3.1/stable [all])
^[[2m[Sun Nov 15 13:29:40]^[(B^[[m ^[[36mLOG    Simulation completed succesfully^[(B^[[m
^[[2m[Sun Nov 15 13:29:40]^[(B^[[m ^[[2m...     Performing installation of 1 apt packages
(webmin)^[(B^[[m
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libauthen-pam-perl libio-pty-perl
The following NEW packages will be installed:
  libauthen-pam-perl libio-pty-perl webmin
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 29.4 MB of archives.
After this operation, 309 MB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 libauthen-pam-perl amd64 0.16-3build7 [24.3 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu focal/main amd64 libio-pty-perl amd64 1:1.12-1 [32.4 kB]
Get:3 https://download.webmin.com/download/repository sarge/contrib amd64 webmin all 1.962 [29.3 MB]
Get:3 https://download.webmin.com/download/repository sarge/contrib amd64 webmin all 1.962 [29.3 MB]
Fetched 29.4 MB in 33s (890 kB/s)
Selecting previously unselected package libauthen-pam-perl.
(Reading database ... ^M(Reading database ... 5%^M(Reading database ... 10%^M(Reading database ... 15%^M(Reading database ... 20%^M(Reading database ... 25%^M(Reading>
Preparing to unpack .../libauthen-pam-perl_0.16-3build7_amd64.deb ...
Unpacking libauthen-pam-perl (0.16-3build7) ...
Selecting previously unselected package libio-pty-perl.
Preparing to unpack .../libio-pty-perl_1%3a1.12-1_amd64.deb ...
Unpacking libio-pty-perl (1:1.12-1) ...
Selecting previously unselected package webmin.
Preparing to unpack .../archives/webmin_1.962_all.deb ...
Unpacking webmin (1.962) ...
Setting up libio-pty-perl (1:1.12-1) ...
Setting up libauthen-pam-perl (0.16-3build7) ...
Setting up webmin (1.962) ...
Webmin install complete. You can now login to https://swizz:10000/
as root with your root password, or as any user who can use sudo
to run commands as root.

-- Logs begin at Fri 2020-11-13 20:39:54 UTC, end at Sun 2020-11-15 13:48:34 UTC. --
Nov 15 13:22:22 swizz systemd[1]: Started swizzin panel service.
Nov 15 13:30:58 swizz systemd[1]: Stopping swizzin panel service...
Nov 15 13:30:58 swizz systemd[1]: panel.service: Succeeded.
Nov 15 13:30:58 swizz systemd[1]: Stopped swizzin panel service.
-- Reboot --
Nov 15 13:31:11 swizz systemd[1]: Started swizzin panel service.
Nov 15 13:31:34 swizz python[993]: [2020-11-15 13:31:34,945] ERROR in app: Exception on /stats/vnstat [GET]
Nov 15 13:31:34 swizz python[993]: Traceback (most recent call last):
Nov 15 13:31:34 swizz python[993]:   File "/opt/swizzin/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
Nov 15 13:31:34 swizz python[993]:     response = self.full_dispatch_request()
Nov 15 13:31:34 swizz python[993]:   File "/opt/swizzin/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
Nov 15 13:31:34 swizz python[993]:     rv = self.handle_user_exception(e)
Nov 15 13:31:34 swizz python[993]:   File "/opt/swizzin/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
Nov 15 13:31:34 swizz python[993]:     reraise(exc_type, exc_value, tb)
Nov 15 13:31:34 swizz python[993]:   File "/opt/swizzin/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
Nov 15 13:31:34 swizz python[993]:     raise value
Nov 15 13:31:34 swizz python[993]:   File "/opt/swizzin/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
Nov 15 13:31:34 swizz python[993]:     rv = self.dispatch_request()
Nov 15 13:31:34 swizz python[993]:   File "/opt/swizzin/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
Nov 15 13:31:34 swizz python[993]:     return self.view_functions[rule.endpoint](**req.view_args)
Nov 15 13:31:34 swizz python[993]:   File "/opt/swizzin/swizzin/core/htpasswd.py", line 208, in decorated
Nov 15 13:31:34 swizz python[993]:     return func(*args, **kwargs)
Nov 15 13:31:34 swizz python[993]:   File "swizzin.py", line 290, in vnstat
Nov 15 13:31:34 swizz python[993]:     lasthour = vnstat_info['interfaces'][0]['traffic']['hour'][-2]["id"]
Nov 15 13:31:34 swizz python[993]: IndexError: list index out of range
Nov 15 13:36:40 swizz python[2262]: Job for wg-quick@wg1000.service failed because the control process exited with error code.
Nov 15 13:36:40 swizz python[2262]: See "systemctl status wg-quick@wg1000.service" and "journalctl -xe" for details.

**Comment by flying-sausages** [comment]
Dupe of issue in panel repo.
