### ISSUE TITLE
Nzbhydra Error 502

### ISSUE THREAD

**Issue by Viper911** [swizzin/swizzin#455]
##  Bug description
Fresh install of apps doesn't work

## Reproduction steps
Do a fresh install on a fresh OS

## Expected behavior
Should work

## Server Info
Ubuntu 20.04)
Vanilla download

## Is Swizzin up to date?
Yes

## Additional context
Running this ahead of Swizzin install seems to fix it
sudo add-apt-repository ppa:linuxuprising/java
sudo apt update
sudo apt install oracle-java15-installer
sudo apt install python3-pip

With this after Install
sudo update-alternatives --config java   ----  set to v8

Looking on issues on git for nzbhydra, seems there is an issue with parsing the version of java.  

Archive:  nzbhydra2.zip
   creating: lib/
  inflating: changelog.md
  inflating: lib/core-3.4.3-exec.jar
   creating: rc.d/
  inflating: LICENSE
  inflating: readme.md
   creating: systemd/
   creating: sysv/
  inflating: nzbhydra2wrapper.py
   creating: upstart/
  inflating: nzbhydra2wrapperPy3.py
  inflating: nzbhydra2
  inflating: rc.d/nzbhydra2
  inflating: systemd/nzbhydra2.service
  inflating: sysv/sysv
  inflating: upstart/defaults
  inflating: upstart/init.ubuntu
^[[2m[Sun Nov 15 13:24:29]^[(B^[[m      ^[[32m^[[2m✔   ^[[3mDone^[(B^[[m
^[[2m[Sun Nov 15 13:24:29]^[(B^[[m ^[[2m...     Installing systemd service^[(B^[[m
^[[2m[Sun Nov 15 13:24:30]^[(B^[[m      ^[[32m^[[2m✔   ^[[3mService installed and nzbhydra started^[(B^[[m
^[[2m[Sun Nov 15 13:24:30]^[(B^[[m ^[[2m...     Configuring nginx^[(B^[[m
^[[2m[Sun Nov 15 13:24:45]^[(B^[[m      ^[[32m^[[2m✔   ^[[3mNginx configured^[(B^[[m
^[[2m[Sun Nov 15 13:24:45]^[(B^[[m ^[[32m^[[1mSUCCESS   Nzbhydra installed^[(B^[[m

**Comment by liaralabs** [comment]
Upstream bug, not related to swizzin
