### ISSUE TITLE
Autodl does not install correctly - No such file or directory

### ISSUE THREAD

**Issue by Viper911** [swizzin/swizzin#456]
During install I get.  The folder its trying to use does not exist and doesn;t get created

INFO	Installing autodl
DOCS	Further reference: https://swizzin.ltd/applications/autodl
...	Performing installation of 10 apt packages
	(irssi screen unzip libarchive-zip-perl libnet-ssleay-perl libhtml-parser-perl libxml-libxml-perl libjson-perl libjson-xs-perl 
	libxml-libxslt-perl)
	✔   Apt install complete
...	configuring autodl for htpc
	✔   Done
grep: /srv/rutorrent/conf/users/htpc/config.php: No such file or directory
sed: can't read /srv/rutorrent/conf/users/htpc/config.php: No such file or directory
sed: can't read /srv/rutorrent/conf/users/htpc/config.php: No such file or directory
/usr/local/bin/swizzin/nginx/autodl.sh: line 24: /srv/rutorrent/conf/users/htpc/config.php: No such file or directory
/usr/local/bin/swizzin/nginx/autodl.sh: line 25: /srv/rutorrent/conf/users/htpc/config.php: No such file or directory
/usr/local/bin/swizzin/nginx/autodl.sh: line 26: /srv/rutorrent/conf/users/htpc/config.php: No such file or directory
...	Creating systemd service
	✔   Done

## Bug description
INFO	Installing autodl
DOCS	Further reference: https://swizzin.ltd/applications/autodl
...	Performing installation of 10 apt packages
	(irssi screen unzip libarchive-zip-perl libnet-ssleay-perl libhtml-parser-perl libxml-libxml-perl libjson-perl libjson-xs-perl 
	libxml-libxslt-perl)
	✔   Apt install complete
...	configuring autodl for htpc
	✔   Done
grep: /srv/rutorrent/conf/users/htpc/config.php: No such file or directory
sed: can't read /srv/rutorrent/conf/users/htpc/config.php: No such file or directory
sed: can't read /srv/rutorrent/conf/users/htpc/config.php: No such file or directory
/usr/local/bin/swizzin/nginx/autodl.sh: line 24: /srv/rutorrent/conf/users/htpc/config.php: No such file or directory
/usr/local/bin/swizzin/nginx/autodl.sh: line 25: /srv/rutorrent/conf/users/htpc/config.php: No such file or directory
/usr/local/bin/swizzin/nginx/autodl.sh: line 26: /srv/rutorrent/conf/users/htpc/config.php: No such file or directory
...	Creating systemd service
	✔   Done

## Reproduction steps
1. Install package '...'
2. Go to '....'
3. Error '...'

## Installed applications through swizzin
(e.g. Nginx, ffmpeg, panel)

## Expected behavior
(A clear and concise description of what you expected to happen.)

## Server Info
**(please complete the following information):**
 - OS: (e.g. Debian 10, Ubuntu 20.04)
 - Image Source: (e.g. "Vanilla download" or "Installscript from specific provider")

## Is Swizzin up to date?
(Please run `box update`, and report whether that was succesful. Please try to reproduce your issue) again. mention the commit hash you are seeing)

**Comment by liaralabs** [comment]
I know you are opening a lot of issues, but leaving out info and ignoring the bug report headers is not helpful.

autodl is looking for ruTorrent. It's technically a dependency since the GUI requires ruTorrent. You did not fill out steps to reproduce or installed applications, so I do not know if you do not have ruTorrent installed; however, your symptoms indicate this. If you are not planning on using the ruTorrent plugin, autodl will likely still function as is.

**Comment by Viper911** [comment]
I installed Ubuntu 20.04 Server fresh + update/upgrade

[htpc.zip](https://github.com/swizzin/swizzin/files/5542933/htpc.zip)

I run Swizzin and select the following, but a bunch don't work.  Not doing anything fancy, just seems like a bunch of these don't work or haven't been tested in a while on a fresh install.  In any case to reproduce this all you need to do is grab Ubuntu Server files from there site, load it into a VM and try installing Swizzin with these components.  You will see  errors along the way in some cases, in other cases it looks like they install ok, but the pages wont come up via panel.

Sorry for opening so many, but 8 of the ones I tried have one issue or another.  I've done another fresh install OS and Swizzin.  Attached the logs I know of.

Panel
Autodl - No such file or directory during install
Filebrowser
Jackett
Lidarr
Netdata
nzbGet
nzbhydra - Java error.  Seems like a know error in their install, but would be good if you guys check for it.
Ombi
Plex
pyLoad
Radarr 
rTorrent - I connect to rutorent, but it says it can not connect to rtorrent
Sonarr v3
Subsonic - Not sure if a java issue or pip3, but again page doesn't come up
Tautulli
The Lounge
librrespeed
Webadmin - Seems to load, but he panel shows disabled
Wireguard - Was installing yesterday ok, but now it wont.  Seems it installs ok, but wont start
fmmpeg - usually installs but got an error about the cert to download once.  
Organizer - Web page doesn;t load after install

In any case, with so many issues, I'm not sure where to start in sending logs, etc., but literally a fresh OS install and the one liner provided by Swizzin.  It doesn't get any cleaner than that.

![image](https://user-images.githubusercontent.com/3239145/99194237-d08b1500-2743-11eb-9db8-6c65a2ed80e0.png)

**Comment by Viper911** [comment]
BTW looks like a new install for nzbhydra was pushed out, so that is working now.  Here are the others

Optimizr
![image](https://user-images.githubusercontent.com/3239145/99194298-2fe92500-2744-11eb-8d4a-3664c72dcf2a.png)

rtorrent (via rutorrent)
![image](https://user-images.githubusercontent.com/3239145/99194311-48f1d600-2744-11eb-92c4-ad7278c856fb.png)

subsonic
![image](https://user-images.githubusercontent.com/3239145/99194331-59a24c00-2744-11eb-83a4-0949d9effa14.png)

webmin and wireguard (I can go to webmin page just fine just issue with panel, and wireguard wont start, not sure what to check on this one)
![image](https://user-images.githubusercontent.com/3239145/99194349-6de64900-2744-11eb-9cc3-4a3e7de49563.png)

**Comment by liaralabs** [comment]
Please stay on topic of the *original bug report* -- these issue reports are not a place to receive basic troubleshooting help and assistance, they are a place to provide concise reports to potentially reproducible issues so that they can be fixed upstream. The discussion forums here on github or discord are the appropriate channels for tech support.

If you need help providing logs, please read the troubleshooting here: https://swizzin.ltd/guides/troubleshooting/

On the subject of autodl, it appears you have indeed installed ruTorrent though. Can you walk through your steps to install autodl, rTorrent and ruTorrent?

Relevant logs are in `/root/logs/install.log` (the initial setup) and `/root/logs/swizzin.log` (for items installed after setup)

Regarding your issue with webmin, that is a duplicate issue: https://github.com/liaralabs/swizzin_dashboard/issues/9

**Comment by Viper911** [comment]
Everything you pointed out can be found in the htpc.zip noted in the prior post.  All available logs and output.  For this issue and the others that did not work.  In terms of steps, I have noted what I have done which is just an out of the box install with the components noted above.  Nothing more and nothing less.  Not sure what other steps your thinking I may be leaving out.  Its a clean OS and Swizzin install with no other changes.

**Comment by flying-sausages** [comment]
The zip file does not contain the actual `/root/logs/install.log` or /root/logs/swizzin.log`. Please isolate the logs for the specific issue at hand, that being `autodl`.

**Comment by Viper911** [comment]
I have no file  /root/logs/swizzin.log - no such file

Also looking at the error during install I see there is never a folder created for htpc.  Seems if I create it manually, and run the install for autodl 2 more times (seems the first is then able to create the config.php, but still errrors and the second run it runs without error).  In any case, seems related to creating the user htpc and having the path build for it to wrtie to or something.

here is a snip of the area around autodl in install.log.  Not much to it..  https://pastebin.com/0AKzWwG1
pasetebin limits the chr without a pro account.  If you want me to upload the install.log file I can, but I ant copy the whole thing into pastebin.

[2m[Sun Nov 15 18:46:59](B[m [2m...	configuring autodl for htpc(B[m
Archive:  autodl-irssi.zip
 extracting: autodl-irssi.pl         
 extracting: AutodlIrssi/ActiveConnections.pm  
 extracting: AutodlIrssi/AnnounceParser.pm
...bunch of files...
 extracting: AutodlIrssi/trackers/x264.tracker  
 extracting: AutodlIrssi/trackers/XSpeeds.tracker  
[2m[Sun Nov 15 18:47:01](B[m 	[32m[2m✔   [3mDone(B[m
[2m[Sun Nov 15 18:47:01](B[m [2m...	Creating systemd service(B[m
[2m[Sun Nov 15 18:47:02](B[m 	[32m[2m✔   [3mDone(B[m
[2m[Sun Nov 15 18:47:02](B[m [32m[1mSUCCESS	autodl installed(B[m


Installing rtorrent
...     Performing installation of 6 apt packages
        (screen zip unzip bc mediainfo curl)
        ✔   Apt install complete
...     Performing installation of 2 apt packages
        (rar unrar)
        ✔   Apt install complete
INFO    Installing rtorrent with apt-get
...     Performing installation of 1 apt packages
        (rtorrent)
        ✔   Apt install complete
...     Making htpc directory structure
        ✔   Done
...     setting up rtorrent.rc
        ✔   Done
SUCCESS rTorrent installed
Installing rutorrent
...     Performing installation of 4 apt packages
        (sox geoip-database python2.7-dev python-setuptools)
        ✔   Apt install complete
...     Installing pip
        ✔   Pip installed
...     Reloading nginx
        ✔   Done
SUCCESS ruTorrent installed
Installing autodl
...     Performing installation of 10 apt packages
        (irssi screen unzip libarchive-zip-perl libnet-ssleay-perl libhtml-parser-perl libxml-libxml-perl libjson-perl
        libjson-xs-perl libxml-libxslt-perl)
        ✔   Apt install complete
...     configuring autodl for htpc
        ✔   Done
grep: /srv/rutorrent/conf/users/htpc/config.php: No such file or directory
sed: can't read /srv/rutorrent/conf/users/htpc/config.php: No such file or directory
sed: can't read /srv/rutorrent/conf/users/htpc/config.php: No such file or directory
/usr/local/bin/swizzin/nginx/autodl.sh: line 24: /srv/rutorrent/conf/users/htpc/config.php: No such file or directory
/usr/local/bin/swizzin/nginx/autodl.sh: line 25: /srv/rutorrent/conf/users/htpc/config.php: No such file or directory
/usr/local/bin/swizzin/nginx/autodl.sh: line 26: /srv/rutorrent/conf/users/htpc/config.php: No such file or directory
...     Creating systemd service
        ✔   Done
SUCCESS autodl installed

**Comment by flying-sausages** [comment]
Just to cross-confirm so I can try reproducing this.

- 20.04 vanilla, not from a provider
- You choose `nginx`, `autodl`, `rutorrent` and `rtorrent` (0.9.8/repo) in the installer

**Comment by flying-sausages** [comment]
I cannot reproduce this on current `master` branch.

```
root@primary:~# dev=true bash /Users/me/Git/Fun/swizzin/setup.sh
DEVVEOVEOVEOVOOEOOEVEEEEEOOOOOEEEEEOOOOO hi
Updating system and grabbing core dependencies.
Enabling required repos
Performing a system upgrade
Installing dependencies
Cloning swizzin repo to localhost
INFO	WELCOME TO THE WORLD OF THE SWIZ YOUNG PADAWAN
	Instead of cloning from upstream, the directory where the setup script
	is located is symlinked to /etc/swizzin
INFO	That directory is relative to your pwd  =
	/Users/me/Git/Fun/swizzin
WARN	Best of luck and please follow the contribution guidelines cheerio
Creating new user htpc ...
Adding password for user htpc
Adding password for user htpc
Installing nginx
...	Performing installation of 16 apt packages
	(nginx libnginx-mod-http-fancyindex subversion ssl-cert php-fpm
	libfcgi0ldbl php-cli php-dev php-xml php-curl php-xmlrpc php-json
	php-mbstring php-opcache php-geoip php-xml)
	✔   Apt install complete
...	Making adjustments to PHP
	✔   PHP config modified
INFO	Using php7.4-fpm in the nginx config
...	Creating default nginx site config and certificates
	✔   Config installed
...	Installing fancyindex
	✔   Fancyindex installed
...	Restarting nginx
	✔   Nginx restared
SUCCESS	Nginx installed
Installing rtorrent
...	Performing installation of 6 apt packages
	(screen zip unzip bc mediainfo curl)
	✔   Apt install complete
...	Performing installation of 2 apt packages
	(rar unrar)
	✔   Apt install complete
INFO	Installing rtorrent with apt-get
...	Performing installation of 1 apt packages
	(rtorrent)
	✔   Apt install complete
...	Making htpc directory structure
	✔   Done
...	setting up rtorrent.rc
	✔   Done
SUCCESS	rTorrent installed
Installing rutorrent
...	Performing installation of 4 apt packages
	(sox geoip-database python2.7-dev python-setuptools)
	✔   Apt install complete
...	Installing pip
	✔   Pip installed
...	Reloading nginx
	✔   Done
SUCCESS	ruTorrent installed
Installing autodl
...	Performing installation of 10 apt packages
	(irssi screen unzip libarchive-zip-perl libnet-ssleay-perl libhtml-parser-perl libxml-libxml-perl libjson-perl libjson-xs-perl libxml-libxslt-perl)
	✔   Apt install complete
...	configuring autodl for htpc
	✔   Done
...	Creating systemd service
	✔   Done
SUCCESS	autodl installed
Package install took 8 minutes and 11 seconds
Installation complete!

You may now login with the following info: htpc:asdasd

Seedbox can be accessed at https://htpc:asdasd@192.168.118.5

Please note, certain functions may not be fully functional until your server is rebooted or you log out and back in. However you may issue the command 'source /root/.bashrc' to begin using box and related functions now
```

Please let me know how I can reproduce it, step by step, itemised. Thanks in advance!

**Comment by Viper911** [comment]
per your questions

-  20.04 vanilla, not from a provider - Yes, server edition NOT desktop
-  You choose nginx, autodl, rutorrent and rtorrent (0.9.8/repo) in the installer - yes in addition to the 10 or so other ones I noted before.  Not sure if that matters (i.e. perhaps one of those are interfering?)

I noticed you used this to kick it off 
dev=true bash /Users/me/Git/Fun/swizzin/setup.sh

I used this per the website
bash <(curl -sL https://git.io/swizzin-setup)

Are these one and the same?

I will try running it with ONLY those selected and see what I get using ---- bash <(curl -sL https://git.io/swizzin-setup)

**Comment by liaralabs** [comment]
I'm still curious as you completely ignored my question. What is the order you chose to install autodl, rTorrent and ruTorrent?

ruTorrent needs to be installed before AutoDL, so if you don't choose rTorrent/ruTorrent on the first page of the installer, then autodl will actually get installed first, which could create this scenario you are facing.

**Comment by flying-sausages** [comment]
The two commands are essentially the same.

I noticed there were some commands which are relative to the current working directory, which means that if you were originally in a directory which is either not accessible or not accessible to some sub-process, that could fail it. I've made a PR.


> What is the order

Given the absence of `swizzin.log` I'm assuming it is from the installer.

**Comment by liaralabs** [comment]
You can still install things out of order in the installer, as I outlined in my comment above.

1. Don't choose rTorrent on page 1.
2. rTorrent gui doesn't pop up
3. All apps are now listed on page 3, free to select anything in any order you like and apps which have been carefully selected to be installed in alphabetical order

**Comment by Viper911** [comment]
I am picking each if the first screen they appear in.

**Comment by liaralabs** [comment]
The full install log would be very helpful. You can use something like termbin to dump it without limits:

```
cat /root/logs/install.log | nc termbin.com 9999
```

**Comment by Viper911** [comment]
Clean install now with whatever you may have changed + only selecting those apps (nginx, autodl, rutorrent and rtorrent (0.9.8/repo) ).  I am going to refresh my OS (VM) and try running again with all the apps noted in the original list.

If it errors, I'll send in the install.log noted.

**Comment by Viper911** [comment]
MUCH CLEANER!  As it relates to r/utorretn and autodl, all is well now..  The only remaining issues I have are organizr, subsonic and the panel shows webmin disabled being tracked under different issues.  In any case, seems we are good on this one..  Closing..

**Comment by flying-sausages** [comment]
Good to hear, thanks!
