### ISSUE TITLE
Jellyfin update - migration issues - please read if you have problems

### ISSUE THREAD

**Issue by userdocs** [swizzin/swizzin#471]
## Bug description

I ran and `box update` and jellyfin was updated.

Now i have some errors in jellyfin

-  i can't see my library
-  I can't add new libraries.
-  log issues about `/home/username/.confg/Jellyfin/root/default/...`
-  I cannot update / rescan my libraries

## Reproduction steps

`box update`

## Installed applications through swizzin

jellyfin

## Expected behaviour

Jellyfin to add libraries, update libraries, see my files

## Server Info
**(please complete the following information):**
 - OS: any supported
 - Image Source: Vanilla download

## Is Swizzin up to date?

yes

## Additional context

n/a

**(Please paste your code into code blocks using the codeblock format like below)**

(For logs of 50+ lines, please rehost to a paste hoster like 0bin)

 ```
n/a
 ```

## Cause and Solutions:

Jellyfin has been migrated from a local user install to a apt-get install using official package repos.

**Issue:** I cannot see or load my library files, or add new libraries from the mount

For gdrive mounts and similar.

**Solution:** Jellyfin now runs as the user `jellyfin` and not your swizzin user. The perms of your mount may need to reflect this change.

**Issue:** You cannot update your libraries and have log issues about `/home/username/.confg/Jellyfin/root/default/...` log errors

**Solution:** Unfortunately there was a small oversight in the migrations which require this fix - related fix https://github.com/swizzin/swizzin/pull/470

You have two options.

**1:** if you have a **small library** and re-scanning is no issue for you, you can simply remove the libraries and re add them to fix this.

**2:** If you have a large library and prefer not to remove/rescan you need this option

This will backup you `library.db` and edit it based on the existing library folders to complete the migrations.

```bash
#! /usr/bin/env bash
#
. /etc/swizzin/sources/functions/apt
. /etc/swizzin/sources/functions/color_echo
. /etc/swizzin/sources/functions/utils
# Get our main user credentials using a util function.
username="$(_get_master_username)"
# Stop the service
systemctl stop jellyfin.service
# We need this to edit the library.db
apt_update #forces apt refresh
apt_install sqlite3
# Backup our libraries
cp -f /var/lib/jellyfin/data/library.db /var/lib/jellyfin/data/library.db.bak
# Get our array of copied directories
readarray -d '' jelly_array < <(find "/var/lib/jellyfin/root/default/" -maxdepth 1 -mindepth 1 -type d -print0)
#
for fml in "${jelly_array[@]}"; do
    sqlite3 /var/lib/jellyfin/data/library.db "UPDATE TypedBaseItems SET Path=REPLACE(Path, \"/home/${username}/.config/Jellyfin/root/default/${fml##*/}\", \"${fml}\");"
    sqlite3 /var/lib/jellyfin/data/library.db "UPDATE TypedBaseItems SET Data=REPLACE(Data, \"/home/${username}/.config/Jellyfin/root/default/${fml##*/}\", \"${fml}\");"
done
#
chown jellyfin:jellyfin /var/lib/jellyfin/data/library.db
# systemctl start jellyfin.service
echo "        all done"
systemctl start jellyfin.service
exit
```

**Comment by flying-sausages** [comment]
Please open separate issues in case you are experiencing other Jellyfin bugs, thanks!
