### ISSUE TITLE
qBittorrent service not gracefully stopped, causing data loss

### ISSUE THREAD

**Issue by an0n666** [swizzin/swizzin#503]
## Bug description

The title says it all.
Had 1170 torrents and lost 300+ because of this.

## Reproduction steps
1. Install package qbit
2. disable/stop service
3. Enjoy, your torrents are gone because someone forgot to add a graceful kill signal to the systemd script!

## Installed applications through swizzin
Does it matter? -_-

## Expected behavior

Send a graceful termination signal to a process by using ExecStop=

## Server Info

Ubuntu 20.04
This doesn't matter though.

## Is Swizzin up to date?

Yes yes..your amazing script is up to date...latest and greatest.

## Additional context
Yeah I know how to quit qBt from the WebUI. But who knew that stopping the service will just kill the process right away?

**Comment by liaralabs** [comment]
There's no `ExecStop` in qBittorrent's own wiki page. Perhaps you'd like to update this page so we can all benefit from your endless wisdom?

https://github.com/qbittorrent/qBittorrent/wiki/Running-qBittorrent-without-X-server-(WebUI-only---systemd-service-setup,-Ubuntu-15.04-or-newer)

**Comment by flying-sausages** [comment]
@an0n666 Fix your attitude please. Everyone can see the revisions.

**Comment by an0n666** [comment]
I'm sorry about the behavior. I had to manually add 300+ torrents back because of this..
The issue is reproducible though..as in stopping the service just insta kills the qBt process.
If it was not mentioned in the wiki then ig it's not your fault after all.

**Comment by flying-sausages** [comment]
Alright, no worries. I can understand it. FYI next time this happens, feel free to pop into the discord. I think your manual re-adding could have been done programmatically.

Please let the upstream maintainer know about your issues here https://github.com/qbittorrent/qBittorrent/issues/13921

**Comment by an0n666** [comment]
The issue was caused by this:
```
Type=forking
ExecStart=/usr/bin/qbittorrent-nox -d
```
It should be 
```
Type=simple
ExecStart=/usr/bin/qbittorrent-nox
```
according to qBt wiki page.

**Comment by liaralabs** [comment]
As of 75f178a619a93bd6e4909d51c56e6b63c1a80c16 we are no longer daemonizing the service.
