### ISSUE TITLE
Ombi not installing when using box install

### ISSUE THREAD

**Issue by nichlashansen** [swizzin/swizzin#507]
## Bug description
When using "Box install Ombi" I'm getting E: The repository 'http://repo.ombi.turd.me/stable jessie InRelease' is not signed.
and can't install the app

## Reproduction steps
1. use box install Ombi
2. error "E: The repository 'http://repo.ombi.turd.me/stable jessie InRelease' is not signed."

## Installed applications through swizzin
Nginx, qbittorent, Radarr

## Expected behavior
I expected the package to install, but it didn't

## Server Info
**(please complete the following information):**
 - OS: Ubuntu 20.04
 - Image Source: install script from Hetzner

## Is Swizzin up to date?
(Please run `box update`, and report whether that was succesful. Please try to reproduce your issue) again. mention the commit hash you are seeing)

Was successful, seeing "HEAD is now set to 6d1d44a"

## Additional context
(Add any other context about the problem here. Logs, terminal output, etc.)

(Good sources for log output could be the following: (only if they have relevant information))
- `cat /root/logs/install.log`
- `cat /root/logs/swizzin.log`
- `cat /var/logs/nginx/error.log`
- `systemctl status <app>@<(user)>`
- `journalctl -xe`

**(Please paste your code into code blocks using the codeblock format like below)**

(For logs of 50+ lines, please rehost to a paste hoster like 0bin)

 ```
 ... logs ...
 ```

**Comment by flying-sausages** [comment]
Hey Nic, thanks for the issue. We made some changes recently but haven't seen this. I know the ombi repo can be a bit flaky, can you try it one or two more times later?

If that still fails, can you please post the logs in `/root/logs/swizzin.log`? Cheers

**Comment by nichlashansen** [comment]
Hi Sausage,
been trying a couple of times.. maybe I'm just a newb. Tried adding the keys to sign the package but didn't work.
Log is here: https://termbin.com/xodyx

**Comment by userdocs** [comment]
Does this fix it?

```
apt-key adv --recv-keys --keyserver  https://roxedus.github.io/apt-test/pub.key
apt update
```

Then try to upgrade again

**Comment by nichlashansen** [comment]
just tried. 
Unfortunately it didn't fix it, still getting this:
INFO	Dumping apt log errors
E: The repository 'http://repo.ombi.turd.me/stable jessie InRelease' is not signed.
E: The repository 'https://apt.sonarr.tv/ubuntu focal InRelease' is not signed.
ERROR	Apt failed.
Please consult the above and/or check the log (less -R +G /root/logs/swizzin.log)

Tried rebooting after, without it making any difference.

(tried installing Sonarr and it gives me same error, all other packages I installed didn't cause any problems) 

For good measure I posted a new log here: https://termbin.com/0hss

**Comment by userdocs** [comment]
Neither of those repos are for ombi v4. It appears you have a larger issue at play that needs to be resolved.

**Comment by userdocs** [comment]
```
apt-get update
apt-get install gnupg2
apt-key adv --recv-keys --keyserver keyserver.ubuntu.com
```

try again?

**Comment by nichlashansen** [comment]
Appreciate the help userdocs!

tried running the commands and rebooting. now it's only giving errors about Sonarr as far as I can tell, new log file: https://termbin.com/s57a

**Comment by userdocs** [comment]
Try this?

```
apt-key adv --recv-keys --keyserver https://apt.sonarr.tv/ubuntu
```

**Comment by nichlashansen** [comment]
used the keys from the Sonarr github and looks like that solved the Sonarr issues.

getting this for Ombi: N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://repo.ombi.turd.me/stable jessie InRelease' doesn't support architecture 'i386'

**Comment by nichlashansen** [comment]
Managed to get it installed.
had to run box upgrade Ombi and then run box install again.
successfully installed it now

Appreciate the huge help!

**Comment by userdocs** [comment]
You should try to understand what happened to your keys and why you needed to update them.

**Comment by nichlashansen** [comment]
I'll try and understand, really appreciate the help.
as far as I understand the keys needed updating because it wasn't an officially repo and the other error was caused by trying to install an unsupported version on the os, that's why I had to use the v4 and not earlier versions.

correct me if I'm wrong, can only get better

**Comment by userdocs** [comment]
I'm not sure, maybe related to this https://superuser.com/questions/1331936/how-can-i-get-past-a-repository-is-not-signed-message-when-attempting-to-upgr

Leave the issue open for now, until the others can look over the messages.

**Comment by flying-sausages** [comment]
> Neither of those repos are for ombi v4. It appears you have a larger issue at play that needs to be resolved.

v3 is still installed by default FYI, so I'm not sure what other error you're referring to. I wouldn't be surprised if the v3 repo got either switched off or went unmaintained.

>  E: The repository 'https://apt.sonarr.tv/ubuntu focal InRelease' is not signed.

Sonarr repos are very often flaky too. Might be good to check the keys on that though.

>  as far as I understand the keys needed updating because it wasn't an officially repo and the other error was caused by trying to install an unsupported version on the os, that's why I had to use the v4 and not earlier versions.

This is swizzin's responsibility to handle indeed. Last time i checked things worked but I'll take a look at this when i have the human bandwidth available

FYI feel free to join the Discord if that's up your jam, often we can discuss this things less async if we're around, which is between early European hours to late americas hours

**Comment by flying-sausages** [comment]
- [ ] Check Ombiv3 keys
- [ ] Check Sonarr keys
- [ ] Check sonarrv3 keys

**Comment by liaralabs** [comment]
I've heard some potential edge cases where GPG isn't getting installed, maybe this is the root of this?

**Comment by nichlashansen** [comment]
I'll look into joining the discord, and appreciate the help.
I have experienced issues on other providers before, in my experience it's because some of the install images they use has been customized in some way or the other, reckon that could be a factor here too.

**Comment by flying-sausages** [comment]
No updates for 12 days, sounds like gpg deps fixed it
