### ISSUE TITLE
Radarr v3 - Could not connect to SignalR, UI won't update when auth.basic enabled

### ISSUE THREAD

**Issue by gelato** [swizzin/swizzin#508]
## Bug description
In Radarr's UI:
```
Could not connect to SignalR, UI won't update
```
In nginx's error log:
```
2020/12/05 22:00:20 [error] 16225#16225: *959 upstream prematurely closed connection while reading upstream, client: 192.168.1.13, server: _, request: "GET /radarr/signalr/messages?access_token=493934a9f1b24f94977d9fadc75ade26&id=Yx0sMaJa5q5CBC772pSNeQ HTTP/1.1", upstream: "http://127.0.0.1:7878/radarr/signalr/messages?access_token=493934a9f1b24f94977d9fadc75ade26&id=Yx0sMaJa5q5CBC772pSNeQ", host: "192.168.1.57", referrer: "https://192.168.1.57/radarr/system/backup"
2020/12/05 22:00:20 [warn] 17723#17723: "ssl_stapling" ignored, issuer certificate not found for certificate "/etc/ssl/certs/ssl-cert-snakeoil.pem"
2020/12/05 22:00:20 [notice] 17723#17723: signal process started
2020/12/05 22:00:21 [error] 17726#17726: *1035 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.13, server: _, request: "POST /radarr/signalr/messages?access_token=493934a9f1b24f94977d9fadc75ade26&id=Yx0sMaJa5q5CBC772pSNeQ HTTP/1.1", upstream: "http://127.0.0.1:7878/radarr/signalr/messages?access_token=493934a9f1b24f94977d9fadc75ade26&id=Yx0sMaJa5q5CBC772pSNeQ", host: "192.168.1.57", referrer: "https://192.168.1.57/radarr/"
```

## Reproduction steps
1. box install radarr
2. Go to UI and wait a minute
3. Error - Could not connect to SignalR, UI won't update

## Installed applications through swizzin
panel, radarr, sonarr, librespeed, mango, netdata, jackett, nzbget, plex

## Expected behavior
No errors

## Server Info
**(please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - Image Source: "Vanilla download"

## Is Swizzin up to date?
HEAD is now set to 6d1d44a

## Additional context
(Add any other context about the problem here. Logs, terminal output, etc.)
Issue disappears if auth.basic options are commented out in nginx:
```
location /radarr {
  proxy_pass        http://127.0.0.1:7878/radarr;
  proxy_set_header Host $proxy_host;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_redirect off;
  #auth_basic "What's the password?";
  #auth_basic_user_file /etc/htpasswd.d/htpasswd.user;

  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection $http_connection;
}
```

**Comment by flying-sausages** [comment]
Can you let me know what other modifications you did to the radarr settings afterwards? I'll try reproduce this sometime this weekend

**Comment by flying-sausages** [comment]
I've got the same on a standard install so the issue there is not going to come from the `auth_basic`. I'm gonna investigate this further.

**Comment by trackermb** [comment]
hi having the same issue, standard install but getting SignalR issue.  Radarr version 3.0.1.4259 ubuntu 18.4.4

**Comment by flying-sausages** [comment]
This went away for me with the last couple radarr updates. Please switch your nginx config back to the default, update it to the latest version, and let me know if it doesn't work then.
