### ISSUE TITLE
Cant type "box command" after install

### ISSUE THREAD

**Issue by ilhamepri** [swizzin/swizzin#510]
## Bug description
After install i cant accest box command

## Installed applications through swizzin
qbittorent,nginx,rtorrent,file browser

## Expected behavior
I can run box command

## Server Info
**(please complete the following information):**
 - OS: Ubuntu 18.04

## Is Swizzin up to date?
cant accest box command

(e.g. HEAD is now at d4d151b)

**Comment by flying-sausages** [comment]
`Please note, certain functions may not be fully functional until your server is rebooted or you log out and back in. However you may issue the command 'source /root/.bashrc' to begin using box and related functions now`

Did you do this? it's the last line the installer prints

**Comment by ilhamepri** [comment]
> `Please note, certain functions may not be fully functional until your server is rebooted or you log out and back in. However you may issue the command 'source /root/.bashrc' to begin using box and related functions now`
> 
> Did you do this? it's the last line the installer prints

i guess not yet, gonna try that asap
thanks for replying

**Comment by flying-sausages** [comment]
I'm assuming this is fixed, let us know with a new issue or in discord if it's not
