### ISSUE TITLE
Internet Speeds and IOWait are BLANK in Panel

### ISSUE THREAD

**Issue by Telestosatt** [swizzin/swizzin#521]
## Bug description
In my Panel, Internet Speeds and IOWait are Blank

## Reproduction steps
1. Install package `sudo -H su -c 'bash <(wget -qO - git.io/swizzin) && . ~/.bashrc`
2. Go to IP pf your server
3. Error is "Speeds are blank in panel"

## Installed applications through swizzin
Nginx, Panel, Rutorrent

## Expected behavior
Speeds should be visible in panel

## Server Info
**(please complete the following information):**
  - OS: Ubuntu 18.04
 - Image Source: Installscript from Panel/Dashboard of my server provider

## Is Swizzin up to date?
Yes. I ran `sudo box update` to make sure its up-to-date

## Additional context
I did these things
A. Got my dedi delivered.
B. Ran command (with "-H") to install swizzin
C. Selected "Nginx", "Panel", "Rutorrent" for installation
D. Found out "MY speeds and IOWait are not visible in panel. BUT Total Usage is fine". Refer below pic for more info
[![image.png](https://i.postimg.cc/26hhmmWV/image.png)](https://postimg.cc/XGNpcRQb)
E. Restarted panel using `sudo systemctl restart panel` command. Still the same
F. Uninstalled and reinstalled panel. Still the same.

But `vnstat -l` is working fine. Here is a pic
[![image.png](https://i.postimg.cc/X7HZRXPs/image.png)](https://postimg.cc/1fF56RsF)

(Good sources for log output could be the following: (only if they have relevant information))
- `cat /root/logs/install.log`
- `cat /root/logs/swizzin.log`
- `cat /var/logs/nginx/error.log`
- `systemctl status <app>@<(user)>`
- `journalctl -xe`

Provided  `cat /root/logs/swizzin.log`

https://0bin.net/paste/vlPYdMzF#CcIyLaHKX-WDJOEvrqjyjQ/r/hUAXB8jpt6RH3rFUJX

**Comment by liaralabs** [comment]
@Telestosatt Thanks for the report.

I was able to track down this issue due to an upgrade in the socket.io backend and the panel still using the old socket.io javascript client.

I've upgraded the required components and you should find this issue fixed after a `box update`

**Comment by Telestosatt** [comment]
Yesss. It worked. 
Thank You so much
