### ISSUE TITLE
Nzbh2's API endpoint is basic-authed and it's hard to get past when not on local network

### ISSUE THREAD

**Issue by flying-sausages** [swizzin/swizzin#546]
## Bug description
(A clear and concise description of what the bug is.)

## Reproduction steps
1. Install nzbh2
2. Install sonarr v3
3. Can't add the API point as it wants to auth via API and no fields for basic auth

## Installed applications through swizzin
nzbh2 sonarrv3

## Expected behavior
Accessible non-nginx-authed api block

## Server Info
**(please complete the following information):**
 - OS: (e.g. Debian 10, Ubuntu 20.04) ???
 - Image Source: (e.g. "Vanilla download" or "Installscript from specific provider") ???

## Additional context
@Tunes0710's fix
```nginx
  location /nzbhydra/api {
    include /etc/nginx/snippets/proxy.conf;
    proxy_pass        http://127.0.0.1:5076/nzbhydra/api;
    auth_basic "off";
}
  location /nzbhydra/torznab/api {
    include /etc/nginx/snippets/proxy.conf;
    proxy_pass        http://127.0.0.1:5076/nzbhydra/torznab/api;
    auth_basic "off";
}
```
<img width="702" alt="image" src="https://user-images.githubusercontent.com/23618693/102728116-34e45a00-432a-11eb-8cfd-04690690dbda.png">

**Comment by bakerboy448** [comment]
applies to  AT LEAST the following as well:
- Radarr
- Lidarr
- Readarr
- Sonarr

**Comment by tunes0710** [comment]
This is happening when 'arrs/etc are located on an external server to NZBH and only way of connecting is via nginx. Obviously if local on same machine/lan then local ips/ports can be used to avoid this

**Comment by bakerboy448** [comment]
Just tested with my install and lunasea and confirmed it works as expected
The ARRs, Sab, Hydra, and Tautulli need the block added.

**Comment by flying-sausages** [comment]
I thought about this for a good while and I'm going to call this a `wontfix`, seeing as this is only necessary when you are connecting to programs running _outside_ the machine and there's little reason for them not to support basic auth headers (LunaSea does, for example).

The instructions in here are clear enough for anyone to follow on their own if they want to reproduce this, but at this time we will not be "opening" the security up for this as it would require project-wide security changes and ain't nobody got time for that if it already works.

Thanks for the steps either way, I'm sure someone in the future will appreciate this.
