### ISSUE TITLE
Support TLS 1.3 and http2

### ISSUE THREAD

**Issue by itsgoingdown2k20** [swizzin/swizzin#556]
## Bug description
TLS1.2 should Ideally be phased out

## Reproduction steps
go to your domain on swizzin its most likely using 1.2

## Installed applications through swizzin
Nginx

## Expected behavior
Forces 1.3 

## Server Info
NA
## Is Swizzin up to date?
NA

(e.g. HEAD is now at d4d151b)

## Additional context
NA

**Comment by wii747** [comment]
Just change the following to  

nano /etc/nginx/sites-enabled/default

from 

listen 443 ssl default_server;
listen [::]:443 ssl default_server;

to 

 listen 443 ssl http2 default_server;
 listen [::]:443 ssl http2 default_server;

nano  /etc/nginx/snippets/ssl-params.conf

from 

ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

to
ssl_protocols TLSv1.2 TLSv1.3;

**Comment by flying-sausages** [comment]
I would not be opposed to changing the default configuration to HTTP2 and dropping insecure TLS.

**Comment by liaralabs** [comment]
HTTP2 has not yet been enabled due to Safari + ruTorrent incompatibilities. Just FYI.

The problem still exists as far as I am aware.

**Comment by wii747** [comment]
HTTP2 is working on Safari browser version 11.1 supports HTTP/2 Protocol (released 2017 onwards)

I have modified my live swizzin config to use HTTP2 and ruTorrent is working without any issues.

**Comment by Motophan** [comment]
I have done the same without any ill effects. I use firefox, chrome, and chrome mobile phone

**Comment by flying-sausages** [comment]
I've scheduled this for milestone 3.1

**Comment by XantherBanter** [comment]
Here's my personal setup on Nginx. It's mostly based on Mozilla's Modern preset, and it works on most of my devices.

`/etc/nginx/snippets/ssl-params.conf`

```
ssl_protocols TLSv1.3;
ssl_prefer_server_ciphers off;
ssl_session_timeout 1d;
ssl_session_cache shared:SSL:10m;
ssl_session_tickets off;
ssl_stapling on;
ssl_stapling_verify on;
resolver 127.0.0.1;
resolver_timeout 3s;
add_header Strict-Transport-Security "max-age=63072000; includeSubdomains" always;
add_header X-Frame-Options SAMEORIGIN always;
add_header X-Content-Type-Options "nosniff" always;
ssl_dhparam /etc/nginx/ssl/dhparam.pem;
```

`/etc/nginx/sites-enabled/default`

```
server {
  listen 80 default_server;
  listen [::]:80 default_server;
  server_name domain.ltd;

  location /.well-known {
    alias /srv/.well-known;
    allow all;
    default_type "text/plain";
    autoindex    on;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

# SSL configuration
server {
  listen 443 ssl http2 default_server;
  listen [::]:443 ssl http2 default_server;
  server_name domain.ltd;
  ssl_certificate /etc/nginx/ssl/domain.ltd/fullchain.pem;
  ssl_certificate_key /etc/nginx/ssl/domain.ltd/key.pem;
  include snippets/ssl-params.conf;
  client_max_body_size 0M;
  server_tokens off;
  root /srv/;



  include /etc/nginx/apps/*;

  location ~ /\.ht {
    deny all;
  }

  location /fancyindex {

  }
}
```

If I may suggest, I assume that some smart TVs will have problems connecting when using this preset (Jellyfin/Emby specifically. PMS AFAIK rolls its own config), so I think it would be good to provide an option to use either https2 for modern devices or Mozilla's Intermediate Preset which includes TLS 1.2 and specific ciphers for compatibility.

**Comment by Motophan** [comment]
You can listen on http1.1 and http2 at the same time.

I believe the tls 1.3 requirement is what is breaking your smart TV, not
the http2, as it has limited cypher support.
