### ISSUE TITLE
Jellyfin installation

### ISSUE THREAD

**Issue by LaMpiR** [swizzin/swizzin#587]
## Bug description
SSL not installed and port for login use with nginx. Install through "box install jellyfin" as root.

## Reproduction steps
su
install box jellyfin

## Installed applications through swizzin
nginx, rutorrent, rtorrent, plex

## Expected behavior
To be accessible through panel on */jellyfin with SSL.

## Server Info
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

## Is Swizzin up to date?
Yes, box update command was run before that.

## Additional context
Swizzin uptodate. Wanted to try out the jellyfin.

Installed through "box install jellyfin" as a root. Installation was without any errors. Went to the panel, clicked o Jellyfin and got the error "Error processing request." from url */jellyfin.

Went to *:8920 but no ssl and it works. 

Is there anyway to install the ssl for the *:8920 and to change the url in the cotrol panel menu?

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

**Comment by LaMpiR** [comment]
Is this now added?

**Comment by flying-sausages** [comment]
> Is there anyway to install the ssl for the *:8920 and to change the url in the cotrol panel menu?

Yes, read the docs.

You might want to look into the letsencrypt package in swizzin.

I don't really see a bug here, we're a lot better with giving support through discord if you want to have someone take a look at it with you

**Comment by LaMpiR** [comment]
https://swizzin.ltd/applications/letsencrypt

I have read this and reinstalled it and reissued the certificate and it's still not applied to the jellyfin.
Jellyfin is using the Custom SSL certificate path:
/home/username/.ssl/username-self-signed.pfx
and not from /etc/nginx/ssl/hostname (there is not .pfx file here).

Using search https://swizzin.ltd/applications/letsencrypt doesn't work so I can't find anything with SSL additionaly.

**Comment by flying-sausages** [comment]
Letsencrypt will only affect the `/jellyfin` endpoint, not the application's port. I'm still unsure what exactly you're trying to access this way and why.

Did you see this? https://swizzin.ltd/applications/jellyfin#unable-to-connect-using-apps

**Comment by LaMpiR** [comment]
> Letsencrypt will only affect the `/jellyfin` endpoint, not the application's port. I'm still unsure what exactly you're trying to access this way and why.
> 
> Did you see this? https://swizzin.ltd/applications/jellyfin#unable-to-connect-using-apps

I have. I have a no-ip subdomain which I am using for along time now and it's working with Letsencrypt.

I have added in the Jellyfin Settings-Networking-Base URL as /jellyfin, restarted the jellyfin and it's now binding to the */jellyfin address and SSL from Letsencrypt is working properly. 

Server is still using the port 8920 for SSL without SSL. Will look into how to stop that, since there is no reason for it to be open.

**Comment by flying-sausages** [comment]
@userdocs We should switch the JF->Nginx connection to use the non-SSL port, and either stop the SSL port entirely or make it use the already existing self-generated cert, and/or make sure that Letsencrypt generated certs when added both and after the JF installer

**Comment by userdocs** [comment]
I have read over this difficult to decipher issue and don't think that is related to his issue nor what is being fixed here.

As far as I can understand he wants to know why jellyin is accessible on the non SSL port  `http://IP:8096` which is it for some reason.

> Server is still using the port 8920 for SSL without SSL. Will look into how to stop that, since there is no reason for it to be open.

**No nginx** - Server is running on `0.0.0.0` http via `8096` and https via `8920` and both are accessible via the web.  It shoudl redirect to https. That was what it was doing before.

**With nginx** - Server is running on `127.0.0.1` ports `8096` and `8920` with nginx configured to proxy via the https port. No access via ports. Try and you will see this.

![wut-1](https://user-images.githubusercontent.com/16525024/107083467-95056180-67ed-11eb-9307-ce0ad3d8a4b6.jpg)

The real problem here seems to be this. The default non Jellyfin installation config.

![wut-2](https://user-images.githubusercontent.com/16525024/107083468-959df800-67ed-11eb-8f14-a5581cec7616.jpg)

There was no non https connections. Why access is allowed over port `8096` seems like a jellyfin bug.

**Comment by userdocs** [comment]
@LaMpiR do you agree with my comment. Is it correct for you r issue?

**Comment by LaMpiR** [comment]
So it started with installation using "box install jellyfin" command and the config file created was not compatible with the panel, so it made jellyfin administration panel not accessible from the panel using /jellyfin url.

It makes sense that letsencrypt doesnt create special pfx certificate, since it operates on the different port.

Having configure it properly to be accessible from /jellyfin and inside of panel, SSL and non-SSL administration panel port remain open, but without SSL certificate.

So the problem is actually not having the proper configuration file after the installation and now this SSL admin thing.

I will install it on my windows and fire tv stick and see if jellyfin makes any problems with all of that, then look for a way in order to close the ports and with it access to the admin panel without the certificate.

**Comment by userdocs** [comment]
I've never used letencrypt with swizzin. Unless there is a way to use it without a valid cert I am not sure how I could test and verify this.

I need a volunteer or an alternate method to verify your issue and I don't experience it.

I think it understand your issue but I don't understand why without testing.

**Comment by flying-sausages** [comment]
Closed for inactivity
