### ISSUE TITLE
Unnecessary Reference to $deluge in Qbit Function

### ISSUE THREAD

**Issue by bakerboy448** [swizzin/swizzin#597]
https://github.com/swizzin/swizzin/blob/d19dfa096ba99a28a29e0659f476f91ebf52e8c1/sources/functions/qbittorrent#L58

$deluge is referenced, but doesn't seem to come from anywhere?

**Comment by liaralabs** [comment]
The `deluge` variable is set previously in the `check_client_compatibility` function
