### ISSUE TITLE
ruTorrent not working after last update (PHP Fatal error:  Uncaught Error: Call to undefined function get_magic_quotes_gpc())

### ISSUE THREAD

**Issue by Sockolet** [swizzin/swizzin#598]
## Bug description
ruTorrent doesn't work anymore with error:
[19.03.2021 16:53:07] Bad response from server: (500 [error,getplugins]) Internal Server Error

## Reproduction steps
Upgraded today.
$sudo su
$box update

## Installed applications through swizzin
nginx, rtorrent, rutorrent, sonarr, radarr, etc

## Expected behavior
ruTorrent works

## Server Info
Ubuntu 18.04 64bit up-to-date HWE kernel.

## Is Swizzin up to date?
Yes

## Additional context
-- Today update:
root@j3455:/home/*******# box update
...     Updating swizzin local repository
Already on 'master'
Your branch is up to date with 'origin/master'.
remote: Enumerating objects: 118, done.
remote: Counting objects: 100% (118/118), done.
remote: Total 198 (delta 118), reused 118 (delta 118), pack-reused 80
Receiving objects: 100% (198/198), 68.73 KiB | 1.91 MiB/s, done.
Resolving deltas: 100% (148/148), completed with 52 local objects.
From https://github.com/liaralabs/swizzin
 * branch            master     -> FETCH_HEAD
   10be958..d19dfa0  master     -> origin/master
HEAD is now at d19dfa0 Pin nextcloud to v20 on Bionic
INFO    HEAD is now set to d19dfa0
        ✔   Local repository updated
INFO    Installing missing dependencies
...     Performing apt update
        ✔   Done
...     Performing installation of 2 apt packages
        (fortune cracklib-runtime)
        ✔   Apt install complete
...     Updating panel to latest version
...     Pulling new commits
        ✔   Commits pulled
...     Checking pip for new depends
        ✔   Depends up-to-date
...     Restarting Panel
        ✔   Done!
        ✔   Done
...     Installing certificate into vsftpd
/etc/swizzin/sources/functions/letsencrypt: line 10: /root/.acme.sh/*******.duckdns.org/*******.duckdns.org.conf: No such file or directory
sed: can't read /root/.acme.sh/*******.duckdns.org/*******.duckdns.org.conf: No such file or directory
        ✔   Done
root@j3455:/home/*******# exit
exit

-- Swizzing log:
[swizzin.log](https://github.com/swizzin/swizzin/files/6172554/swizzin.log)

-- Error in nginx log:
2021/03/19 11:53:19 [error] 10325#10325: *19774 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function get_magic_quotes_gpc() in /srv/rutorrent/php/util.php:58
Stack trace:
#0 /srv/rutorrent/php/util.php(67): fix_magic_quotes_gpc()
#1 /srv/rutorrent/plugins/diskspace/action.php(2): require_once('...')
#2 {main}
  thrown in /srv/rutorrent/php/util.php on line 58" while reading response header from upstream, client: 62.83.167.71, server: *******.duckdns.org, request: "GET /rutorrent/plugins/diskspace/action.php?_=1616148999425 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.0-fpm.sock:", host: "*******.duckdns.org"
2021/03/19 11:53:30 [error] 10325#10325: *19774 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function get_magic_quotes_gpc() in /srv/rutorrent/php/util.php:58
Stack trace:
#0 /srv/rutorrent/php/util.php(67): fix_magic_quotes_gpc()
#1 /srv/rutorrent/plugins/diskspace/action.php(2): require_once('...')
#2 {main}
  thrown in /srv/rutorrent/php/util.php on line 58" while reading response header from upstream, client: 62.83.167.71, server: *******.duckdns.org, request: "GET /rutorrent/plugins/diskspace/action.php?_=1616148999426 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.0-fpm.sock:", host: "*******.duckdns.org"
2021/03/19 11:53:41 [error] 10325#10325: *19774 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function get_magic_quotes_gpc() in /srv/rutorrent/php/util.php:58
Stack trace:
#0 /srv/rutorrent/php/util.php(67): fix_magic_quotes_gpc()
#1 /srv/rutorrent/plugins/diskspace/action.php(2): require_once('...')
#2 {main}
  thrown in /srv/rutorrent/php/util.php on line 58" while reading response header from upstream, client: 62.83.167.71, server: *******.duckdns.org, request: "GET /rutorrent/plugins/diskspace/action.php?_=1616148999427 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.0-fpm.sock:", host: "*******.duckdns.org"

**Comment by liaralabs** [comment]
Swizzin does not currently have any support or testing in regards to php8.0. In fact, no support is provided for moving to a version of php not shipped through the repository of the current distribution.

For bionic, I believe this is php7.2. Therefore using php8.0 means the onus to solve problems that arise from changing the defaults beyond stock falls to the user.

**Comment by Sockolet** [comment]
I'm using 7.4...

root@j3455:~$ php --version
PHP 7.4.16 (cli) (built: Mar  5 2021 07:54:20) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.16, Copyright (c), by Zend Technologies

**Comment by liaralabs** [comment]
Related: https://github.com/Novik/ruTorrent/issues/2137

**Comment by liaralabs** [comment]
You may think you are using 7.4 but nginx is not

```
#2 {main}
thrown in /srv/rutorrent/php/util.php on line 58" while reading response header from upstream, client: 62.83.167.71, server: .duckdns.org, request: "GET /rutorrent/plugins/diskspace/action.php?_=1616148999427 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.0-fpm.sock:", host: ".duckdns.org"
```

**Comment by Sockolet** [comment]
I don't know why is is supposely using php8.0. Maybe I installed it for Nextcloud... I'm doubting now.
Quick tip to switch back to 7.4?

Thanks for your quick response and for your amazing job.

**Comment by liaralabs** [comment]
You could try completely removing all packages related to PHP and then install the 7.4 specific versions of the PHP depends listed in `scripts/install/nginx.sh`. (i.e `php7.4-fpm` et. al) After that, `box upgrade nginx` should be able to help sort you out by fixing your nginx configs. What likely happened is that php8 was discovered on your system during the update and swizzin tried to switch to it.

Also it's possible that an upgrade of rutorrent would fix the issue as well as it's likely something that has changed in the way PHP is processed that rutorrent fixed. There is no direct route to upgrade rutorrent though.

One of the major issues that crops up is that for simplicity swizzin defines the packages to install as the "metapackages" i.e `php-fpm`.

This creates problems when there is more than one package to choose from at the same name. Sometimes packages fail to install or install the unintended packages as when PHP is managed by the distribution there is always only one version of libs present.

**Comment by Sockolet** [comment]
Understood. Great explanation. Thanks again for your help!

**Comment by Sockolet** [comment]
Solved by manually updating ruTorrent like this:

```
sudo systemctl stop nginx.service
cd /srv
sudo cp rutorrent rutorrent.bak
sudo rm -R rutorrent
sudo git clone https://github.com/Novik/ruTorrent.git
sudo mv ruTorrent rutorrent
sudo rm -R ./rutorrent/conf
sudo rm -R ./rutorrent/plugins
sudo chown -R www-data:www-data rutorrent
sudo systemctl start nginx.service
```

This is just a dirty trick, obviously unsopported, but I'm planning to do a full upgrade to Ubuntu 22.04 next year, so it will be nice if it can just keep working like this until that moment.

Many thanks!
