### ISSUE TITLE
box update causing jackett spew if jackett is not in main user homedir

### ISSUE THREAD

**Issue by bakerboy448** [swizzin/swizzin#604]
https://github.com/swizzin/swizzin/blob/377ee0c3f531c1ccfb275003390a98a47820206d/scripts/update/jackett.sh#L56

/etc/swizzin/scripts/update/jackett.sh: line 56: /home/bakerboy448/Jackett/jackett_launcher.sh: No such file or directory
chmod: cannot access '/home/bakerboy448/Jackett/jackett_launcher.sh': No such file or directory
stat: cannot stat '/home/bakerboy448/.config/Jackett/ServerConfig.json': No such file or directory

**Comment by flying-sausages** [comment]
Uhhh I mean if you break it, it will be broken, yes :p

I'd rather just move Jackett to /opt permanently

**Comment by bakerboy448** [comment]
@flying-sausages  - You should create a GHI to track moving jackett to /opt
