### ISSUE TITLE
Nginx sonarr v3 Script setting depreciated, dead branch

### ISSUE THREAD

**Issue by bakerboy448** [swizzin/swizzin#605]
https://github.com/swizzin/swizzin/blob/552939cf234ad06a5f512508731f26e16452fb5e/scripts/nginx/sonarrv3.sh#L33

phantom-develop is no longer a current branch. Users should be pushed to main

**Comment by flying-sausages** [comment]
If you make a PR I'll approve it.

**Comment by bakerboy448** [comment]
fixed in https://github.com/swizzin/swizzin/commit/80fe94ae340137090f1c790b523fb8b16e8acbc7
