### ISSUE TITLE
Pyload credential

### ISSUE THREAD

**Issue by lushdog** [swizzin/swizzin#644]
## Bug description
The pyload installing script is outdated. Can't login with master credential.

## Reproduction steps
1. Install package pyload
2. Go to /pyload/login
3. Error `Incorrect username/email or password.`

## Installed applications through swizzin
pyload

## Expected behavior
(A clear and concise description of what you expected to happen.)

## Server Info
**(please complete the following information):**
 - OS: Debian 10
 - Arch: x86_64

## Is Swizzin up to date?
Yes

## Additional context
(Add any other context about the problem here. Logs, terminal output, etc.)

(Good sources for log output could be the following: (only if they have relevant information))
- `cat /root/logs/install.log`
- `cat /root/logs/swizzin.log`
- `cat /var/logs/nginx/error.log`
- `systemctl status <app>@<(user)>`
- `journalctl -xe`

**(Please paste your code into code blocks using the codeblock format like below)**

(For logs of 50+ lines, please rehost to a paste hoster like 0bin)

 ```
 ... logs ...
 ```

**Comment by flying-sausages** [comment]
Please post your logs and other info required in the template.

**Comment by flying-sausages** [comment]
Closed for inactivity
