### ISSUE TITLE
rutorrent url 404

### ISSUE THREAD

**Issue by purpleden** [swizzin/swizzin#669]
## Bug description
Receiving upon IP/rutorrent

Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

## Reproduction steps
Installed nginx first
Installed panel
Installed rtorrent and rutorrent
Ran box update

## Installed applications through swizzin
nginx
panel
rtorrent
rutorrent

## Expected behavior
Clicking on rutorrent via panel to load the interface

## Server Info
Ubuntu 18.04 64bit
Using swizzin from github

## Is Swizzin up to date?
Commit hash: abff162

## Additional context
rtorrent.conf not in /etc/nginx/apps/ until I run box update

**Comment by flying-sausages** [comment]
Can you please post the full logs from this install?

**Comment by flying-sausages** [comment]
I found a potential cause for this issue and made a bugfix for that, but it would be good to double-check if this is the one you encountered.

**Comment by purpleden** [comment]
No problem - here you go.

I recreated my vps and reinstalled

[swizzin.log](https://github.com/swizzin/swizzin/files/6493619/swizzin.log)

**Comment by flying-sausages** [comment]
Hmm, looks like some of the error messages don't hit the logs correctly in master right now. Can you paste the output into your terminal as well please?

Could you also check if `/srv/rutorrent` exists?

**Comment by purpleden** [comment]
/srv/rutorrent exists with:
```
LICENSE.md
README.md
/conf
/css
htaccess-example
/images
index.html
/js
/lang
/php
/plugins
/share
```

I will do a quick rebuild

**Comment by flying-sausages** [comment]
Ok weird, then the bug I found might have bee unrelated.

I do see this though
```
E: Package 'rar' has no installation candidate
E: Package 'unrar' has no installation candidate
```
Is this where your install fails?

Could you do `apt policy rar` for me please? Which provider are you using, or where did you get your installation image? Are you sure you're on `amd64`?

**Comment by purpleden** [comment]
Definitely on amd64, rar policy shows nothing, I've installed unar and unrar-free and trying again

**Comment by purpleden** [comment]
Just installed rclone, and rutorrent now works, unsure how that affects rutorrent?

**Comment by flying-sausages** [comment]
![](https://media1.tenor.com/images/46d73c3cc50fa32e0e1d8c2a38007477/tenor.gif?itemid=7513882)

ok i'll look at this properly after i'm off the clock. something well fucky.

**Comment by purpleden** [comment]
I'll install 16.04 and 20.04 x64's, and see if I get the same response from the install

**Comment by purpleden** [comment]
Found the issue - it's to do with the rar files, Ubuntu 20.04 already has rar in it's repos, 18.04 doesn't

I added:
`sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe restricted multiverse"`
Installed unrar
Then ran the install - worked first time

**Comment by flying-sausages** [comment]
Oh, that'll be it then. I'll make sure to fix the rar installer in that case or add the repos. Thanks a ton!

**Comment by purpleden** [comment]
Strange that - I swapped vps providers - never had that issue on the previous one, also, box doesn't "delete" itself after installing now (if I loaded `box` then immediately exited, the command stopped working)

systems are never easy

**Comment by flying-sausages** [comment]
> I swapped vps providers

Different providers choose to add different repos, or even add their own into the install. This can cause us quite some pain, like what you're seeing here.

> if I loaded `box` then immediately exited, the command stopped working

That's probably a separate ticket, I'm curious what the reproduction steps there are. Sounds like a bug indeed though.

**Comment by liaralabs** [comment]
> 
> 
> Found the issue - it's to do with the rar files, Ubuntu 20.04 already has rar in it's repos, 18.04 doesn't
> 
> I added:
> `sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe restricted multiverse"`
> Installed unrar
> Then ran the install - worked first time

It's weird because this shouldn't be necessary -- we enable `universe`, `multiverse` and `restricted` during the initial setup as it is known that the standard repos do not provide all the packages we use throughout swizzin. 😕

**Comment by liaralabs** [comment]
Closing this issue as it is stale and commits have been made to address some of the odd behavior noted by the author of this issue. If a similar issue comes up, please open a new issue and it will be investigated in the context of the current release.
