### ISSUE TITLE
Nginx reverse proxy 404 with Sonarr

### ISSUE THREAD

**Issue by ChadOhman** [swizzin/swizzin#689]
## Bug description
Panel proxy not connecting to Sonarr

## Reproduction steps
1. Install package Sonarr
2. Go to Panel, click on Sonarr tab
3. Error 404: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

## Installed applications through swizzin
(e.g. Nginx, ffmpeg, panel)
Deluge, Jackett, Lidarr, nzbhydra, Ombi, Radarr, SABnzbd, Sonarr, Tautulli

## Expected behavior
(A clear and concise description of what you expected to happen.)
Expecting to see the Sonarr interface.

## Server Info
**(please complete the following information):**
 - OS: Ubuntu 20.04 LTS Server
 - Arch: x86_64
 - Image Source: vanilla install

## Is Swizzin up to date?
(Please run `box update`, and report whether that was succesful. Please try to reproduce your issue) again. mention the commit hash you are seeing)

HEAD is now set to c0eb994
Problem persists, all other apps load fine.

## Additional context
(Add any other context about the problem here. Logs, terminal output, etc.)

(Good sources for log output could be the following: (only if they have relevant information))
- `cat /root/logs/install.log`
- `cat /root/logs/swizzin.log`
- `cat /var/logs/nginx/error.log`
- `systemctl status <app>@<(user)>`
- `journalctl -xe`

 ```
root@swizzin:~/logs# systemctl status sonarr
● sonarr.service - Sonarr Daemon
     Loaded: loaded (/lib/systemd/system/sonarr.service; enabled; vendor preset>
     Active: active (running) since Sun 2021-05-30 03:47:49 UTC; 31min ago
   Main PID: 619 (mono)
      Tasks: 11 (limit: 1072)
     Memory: 51.4M
     CGroup: /system.slice/sonarr.service
             └─619 /usr/bin/mono --debug /usr/lib/sonarr/bin/Sonarr.exe -nobrow>

May 30 03:48:34 swizzin mono[619]: [Info] OwinHostController:   http://*:8989/
May 30 03:48:51 swizzin mono[619]: [Info] SonarrBootstrapper: Starting Web Serv>
May 30 03:49:39 swizzin mono[619]: [Info] RssSyncService: Starting RSS Sync
May 30 03:49:40 swizzin mono[619]: [Warn] FetchAndParseRssService: No available>
May 30 03:49:40 swizzin mono[619]: [Info] DownloadDecisionMaker: No results fou>
May 30 03:49:40 swizzin mono[619]: [Info] RssSyncService: RSS Sync Completed. R>
May 30 04:04:45 swizzin mono[619]: [Info] RssSyncService: Starting RSS Sync
May 30 04:04:46 swizzin mono[619]: [Warn] FetchAndParseRssService: No available>
May 30 04:04:46 swizzin mono[619]: [Info] DownloadDecisionMaker: No results fou>
May 30 04:04:46 swizzin mono[619]: [Info] RssSyncService: RSS Sync Completed. R>
 ```

No relevant errors in `/var/log/nginx/error.log` or `/root/logs/swizzin.log`.

**Comment by liaralabs** [comment]
Just for clarification, did you `box update` after the troubles or before? I think there was a permissions issue with some of the nginx related scripts that may have prevented the nginx settings from properly firing during installation.

If so, a `box upgrade nginx` should sort this issue.

**Comment by ChadOhman** [comment]
Hi @liaralabs! Thanks for the _really_ fast reply.

I did the `box update` as part of my troubleshooting which didn't rectify the trouble. `box upgrade nginx` did, though!

Thanks again!
