### ISSUE TITLE
ruTorrent/rtorrent unable to write changes to the mounted rclone drive

### ISSUE THREAD

**Issue by AndreVuillemot160** [swizzin/swizzin#713]
## Bug description
ruTorrent/rtorrent unable to write changes to the mounted rclone drive.
I saw the same thing with other torrent clients.

## Reproduction steps
1. Install package 'rclone rutorrent rtorrent'
2. Set up rclone config as gdrive
2. Go to 'rutorrent'
3. Try to write something to the `cloud` folder
4. The torrent doesn't downloading

## Installed applications through swizzin
Nginx, panel, rclone, rutorrent, rtorrent

## Expected behavior
Get files from torrent file, and write them.

## Server Info
 - OS: Ubuntu 20.04 LTS
 - Arch: x86_64
 - Image Source: Vanilla download

## Is Swizzin up to date?
Yes, using the latest commit 001bd702300e533ec7213911cc20428732239867

**Comment by liaralabs** [comment]
Seeding to/from a cloud mount is really not advised with rclone as the rclone api is simply not setup to use the kind of IO required by torrents (that is random reads and writes and pre-allocation of torrent files). I do not encourage rclone use to begin with and I would definitely never encourage folks to seed or download torrents directly to a cloud mount ever.

If you have issues with this and want to explore them deeper, I recommend you check with the kind folks over on the rclone forums as this is beyond the scope of the project here.
