### ISSUE TITLE
apt update mono issue

### ISSUE THREAD

**Issue by jcconnell** [swizzin/swizzin#720]
## Bug description
Running `apt update` returns an error regarding the mono version:

`W: Conflicting distribution: https://download.mono-project.com/repo/ubuntu bionic/snapshots/5.18/. InRelease (expected bionic/snapshots/5.18/. but got bionic)`

## Reproduction steps
1. sudo apt update
2. observe error

## Installed applications through swizzin
(e.g. Nginx, ffmpeg, panel)
- panel
- sonarr
- radarr
- ffmpeg
- rclone
- console
- filebrowser
- jackett
- librespeed
- lidarr
- netdata
- nextcloud
- ombi
- plex
- tautulli
- transmission

## Expected behavior
`sudo apt update` should exit without a warning

## Server Info
 - OS: Ubuntu 20.04
 - Arch: x86_64
 - Image Source: Vanilla download

## Is Swizzin up to date?
```
jcconnell@apps:~$ sudo box update
...	Updating swizzin local repository
	✔   Local repository updated from master
INFO	HEAD is now set to 001bd70
```

(e.g. HEAD is now at d4d151b)

## Additional context

With the contents of `/etc/apt/sources.list.d/mono-xamarin.list` as `deb https://download.mono-project.com/repo/ubuntu bionic/snapshots/5.18/. main`

then:

```
jcconnell@apps:/etc/apt/sources.list.d$ sudo apt update
Get:1 http://mirrors.online.net/ubuntu focal InRelease [265 kB]
Hit:2 http://mirrors.online.net/ubuntu focal-updates InRelease
Hit:3 http://mirrors.online.net/ubuntu focal-backports InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:5 https://download.docker.com/linux/ubuntu focal InRelease
Hit:6 http://ppa.launchpad.net/transmissionbt/ppa/ubuntu bionic InRelease
Hit:7 https://downloads.plex.tv/repo/deb public InRelease
Hit:8 https://apt.sonarr.tv/ubuntu bionic InRelease
Hit:9 https://download.mono-project.com/repo/ubuntu bionic/snapshots/5.18/. InRelease
Get:10 https://apt.ombi.app/master jessie InRelease [10.4 kB]
Get:11 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Fetched 389 kB in 2s (160 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
W: Conflicting distribution: https://download.mono-project.com/repo/ubuntu bionic/snapshots/5.18/. InRelease (expected bionic/snapshots/5.18/. but got bionic)
```

With the contents of `/etc/apt/sources.list.d/mono-xamarin.list` as `deb https://download.mono-project.com/repo/ubuntu bionic main`

then:

```
jcconnell@apps:/etc/apt/sources.list.d$ sudo apt update
Get:1 http://mirrors.online.net/ubuntu focal InRelease [265 kB]
Hit:2 http://mirrors.online.net/ubuntu focal-updates InRelease
Hit:3 http://mirrors.online.net/ubuntu focal-backports InRelease
Hit:4 https://download.docker.com/linux/ubuntu focal InRelease
Get:5 https://apt.ombi.app/master jessie InRelease [10.4 kB]
Hit:6 http://ppa.launchpad.net/transmissionbt/ppa/ubuntu bionic InRelease
Hit:7 https://downloads.plex.tv/repo/deb public InRelease
Hit:8 https://apt.sonarr.tv/ubuntu bionic InRelease
Get:9 https://download.mono-project.com/repo/ubuntu bionic InRelease [5,143 B]
Hit:10 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:11 http://security.ubuntu.com/ubuntu focal-security InRelease
Get:12 https://download.mono-project.com/repo/ubuntu bionic/main i386 Packages [49.1 kB]
Get:13 https://download.mono-project.com/repo/ubuntu bionic/main amd64 Packages [49.1 kB]
Fetched 379 kB in 3s (123 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
147 packages can be upgraded. Run 'apt list --upgradable' to see them.
```

I've upgraded from 18.04 to 20.04 but otherwise I don't think I've made any changes to the files in `/etc/apt/sources.list.d`. If it's safe to ignore this warning or if it's safe to remove the `5.18` designation I can do so but wanted to get some feedback here first.

**Comment by liaralabs** [comment]
This is a warning and nothing more. Since you've actually upgraded to 20.04 you should be able to safely remove the file `/etc/apt/sources.list.d/mono-xamarin.list` and go without it, as Ubuntu 20.04 ships a version of mono newer than what we pin older operating systems to. Removing this file will remove the warning on future apt functions.

**Comment by jcconnell** [comment]
Thank you!
