### ISSUE TITLE
[BUG] "box update" fails due to php-opcache

### ISSUE THREAD

**Issue by tintinhamans** [swizzin/swizzin#739]
### What happened?

Steps to reproduce:

1. Run `box update`
2. Error `E: Package 'php-opcache' has no installation candidate`

```
root@triton:~# box update
...	Updating swizzin local repository
	✔   Local repository updated from master
INFO	HEAD is now set to d657714
...	Setting correct permissions on swizzin files
	✔   Permissions set
E: Package 'php-opcache' has no installation candidate
ERROR	The simulation check resulted in an error. Please consult the log.
	Please consult the above and/or check the log (less -R +G
	/root/logs/swizzin.log)
```

It seems like specifying the php version is required:
```
root@triton:~# apt search php-opcache
Sorting... Done
Full Text Search... Done
root@triton:~# apt search php7.4-opcache
Sorting... Done
Full Text Search... Done
php7.4-opcache/bionic,now 7.4.22-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed,automatic]
  Zend OpCache module for PHP
```

Expected results: `box update` should run without errors.

### Swizzin commit

d657714

### What OS are you using?

Ubuntu 18.04 (Xenial)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
Reading package lists...
Building dependency tree...
Reading state information...
Package php-opcache is a virtual package provided by:
  php8.0-opcache 8.0.9-1+ubuntu18.04.1+deb.sury.org+1
  php7.4-opcache 7.4.22-1+ubuntu18.04.1+deb.sury.org+1
  php7.3-opcache 7.3.29-1+ubuntu18.04.1+deb.sury.org+1
  php7.2-opcache 7.2.34-23+ubuntu18.04.1+deb.sury.org+1
  php7.1-opcache 7.1.33-39+ubuntu18.04.1+deb.sury.org+1
  php7.0-opcache 7.0.33-52+ubuntu18.04.1+deb.sury.org+1
  php5.6-opcache 5.6.40-52+ubuntu18.04.1+deb.sury.org+1

E: Package 'php-opcache' has no installation candidate
[Tue Aug 17 00:14:15] ERROR	The simulation check resulted in an error. Please consult the log.
[Tue Aug 17 00:14:15] 	Please consult the above and/or check the log (less -R +G /root/logs/swizzin.log)
```

**Comment by liaralabs** [comment]
The deb.sury.org repo custom repo is not supported in use with swizzin. We only support distribution-released php.

**Comment by liaralabs** [comment]
Apologies if this seems obtuse or some arbitrary decision; however the nginx and php scripts would require significantly more maintenance to allow folks to use whatever version of PHP they desire or to pin all distros to the same version of PHP.

In the past when I contributed to quickbox, the deb.sury repository created plenty of its own maintenance problems which were great at causing their own headaches. These problems led to the removal of the deb.sury repo in this project and a distribution agnostic approach of simply specifying `php-fpm` or `php-opcache` during installation was adopted.

Regretfully this means that these repositories simply cannot co-exist together given that, if changes need to be made, the script has no idea what version of PHP should be referenced.

**Comment by tintinhamans** [comment]
In that case, it functions as intended. Thanks for the explaining the thought process behind this.
