### ISSUE TITLE
[BUG]: Autodl Greps ports of all IRC servers if old config is applied

### ISSUE THREAD

**Issue by brettpetch** [swizzin/swizzin#751]
### What happened?

The issue is that the port and passwords being `grep`'d are *all* passwords and *all* ports in the file. I'd like to propose that the grep is only for `gui-server-port` rather than simply `port` as shown below; also to have `password` changed to `gui-server-password` so it is a more targeted application so grep doesn't pull every instance of port in the config as it does currently.

https://github.com/swizzin/swizzin/blob/6f07eb7f1ed54ccea217d01d45c658b1fbc8b1be/scripts/nginx/autodl.sh#L19-L20

Steps to reproduce:

1. Manually ran `bash /etc/swizzin/scripts/nginx/autodl.sh` after sourcing globals (`. /etc/swizzin/sources/globals.sh`) as root.

Expected results:
Grep the correct ports and configure autodl for all users on a system.

### Swizzin commit

6f07eb7

### What OS are you using?

Debian 11 (Bullseye)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
`echo $(grep port /home/${u}/.autodl/autodl.cfg | cut -d= -f2 | sed 's/ //g')` returns: 

54676 6697 7021 7000 6697 7000 *bandcamp*,*cpop*,*korea*,*chinese*,*norwegian*,*synth.pop*,*dub.techno*,*edm*,*moderncreative*,*freejazz*,*japan*,*portugal*,*italy*,*atmospheric*,*soundscape*,*heavy*,*goth*,freely.available,*Progressive*,*progressive*,*Folk*,*folk*,*chamber*,spiritual,*fusion*,n.y,*goa*,hardcore.rap,*melodic*,*italian*,electro.house,lo.fi,*mashup*,*trap*,*groove*,djent,tzadik,*acid*,*deep*,*Celtic*,*twee*,*thrash*,*sleaze*,*irish*,*power*,*crunk*,*holiday*,*christmas*,*instrumental*,*island*,*psychedelic*,fast.food,waffle.house,*jukebox*,*casio*,leeds,*leeds*,thethirdperson,*detroit*,*Kentucky*,*Drag*,City,*Opera*,*opera*,*jrock*,*japan*,*australia*,*black*,kpop,gothic, 6667
```
```

**Comment by flying-sausages** [comment]
This is racist

**Comment by brettpetch** [comment]
> 
> 
> This is racist

open another issue

**Comment by brettpetch** [comment]
https://github.com/swizzin/swizzin/pull/752
