### ISSUE TITLE
[BUG] File browser 502 Bad Gateway on Ubuntu 20.04 (arm64)

### ISSUE THREAD

**Issue by focusv** [swizzin/swizzin#758]
### What happened?

Steps to reproduce:

Fresh install of Ubuntu 20.04.

Install package filebrowser,
Go to filebrowser web panel
Error 502 Bad Gateway nginx
While other services like qbittorrent works fine

Expected results:
working web panel of filebrowser

### Swizzin commit

6f07eb7

### What OS are you using?

Ubuntu 20.04 (Focal)

### What architecture is your OS?

arm64

### Relevant logs and output

```plaintext
systemd[26669]: filebrowser.service: Failed to execute command: Exec format error
systemd[26669]: filebrowser.service: Failed at step EXEC spawning /home/username/bin/filebrowser: Exec format error
systemd[1]: filebrowser.service: Main process exited, code=exited, status=203/EXEC
systemd[1]: filebrowser.service: Failed with result 'exit-code'.

/etc/systemd/system# cat filebrowser.service
[Unit]
Description=filebrowser
After=network.target

[Service]
User=username
Group=username
UMask=002

Type=simple
WorkingDirectory=/home/username
ExecStart=/home/username/bin/filebrowser -d /home/username/.config/Filebrowser/filebrowser.db
TimeoutStopSec=20
KillMode=process
Restart=always
RestartSec=2

[Install]
WantedBy=multi-user.target
```

**Comment by focusv** [comment]
the same with https://github.com/swizzin/swizzin/issues/231

**Comment by focusv** [comment]
tried uninstall and reinstall. the result is the same

**Comment by liaralabs** [comment]
Looks like filebrowser hasn't been updated with arm64 support yet. We will need to add a case statement during install to make sure the correct architecture is being installed for the user.
