### ISSUE TITLE
[BUG] torrent software can't access /root folder 

### ISSUE THREAD

**Issue by focusv** [swizzin/swizzin#759]
### What happened?

Steps to reproduce:

1. Install package  'deluge, deluge web, qbittorrent''
2. Go to qbittorrent web panel
3. change default download folder to "/root/downloads"  
4. torrent download error
the same thing happens with deluge and Transmission

Expected results:
After changing download folder the software could download files to "/root/downloads"

### Swizzin commit

6f07eb7

### What OS are you using?

Ubuntu 20.04 (Focal)

### What architecture is your OS?

arm64

### Relevant logs and output

```plaintext
After changing the download folder to "/root/downloads" and upload the torrent,qbittorrent & Transmission shows "error" and Deluge shows "Permission Denied"

If I change the download folder to "/home/downloads", they can download files.

I suspect it's a permission bug that torrent softwares can't access root folder
```

**Comment by bakerboy448** [comment]
It's extremely insecure and not a good idea at all to have anything run as too or use /root

Who told you to / what horrible guide / why are you doing that?

but this is not a bug.  The download clients do not run as root nor should they.

**Comment by liaralabs** [comment]
This is not a bug. Please look into Linux permissions, especially surrounding root.

Unprivileged users are not intended to access `/root` ever as this is a major security issue. Even in the context of swizzin, we store user secrets in this directory. Allowing any user to download here will expose this directory and all its contents if you are sharing your server with people you don't fully trust.
