### ISSUE TITLE
[BUG] - Calibre Upgrader non-functional os_arch no found

### ISSUE THREAD

**Issue by bakerboy448** [swizzin/swizzin#765]
### What happened?

Steps to reproduce:

1. Install package  calibre
2. *new calibre version released*
3. Error: `/usr/local/bin/swizzin/upgrade/calibre.sh: line 8: os_arch: command not found`

Expected results:
calibre upgrade to run and complete

### Swizzin commit

4b811ff3

### What OS are you using?

Ubuntu 20.04 (Focal)

### What architecture is your OS?

amd64

### Relevant logs and output

console - https://gist.github.com/bakerboy448/690942f9e8b34033f3c0133a0d8d06e1
swizzin - https://gist.github.com/bakerboy448/b909026a2de6446842a2291b13de6d20
ls -lha /install - https://gist.github.com/bakerboy448/90ab65438979cd2e718f538b1c44828c

manually running the wget and bash from upgrade/calibre.sh
https://gist.github.com/bakerboy448/4615ab6d66eb6cabd7ba01a4f2bb117c

**Comment by liaralabs** [comment]
Are you able to test the PR to let me know if you are still facing issues upgrading?

**Comment by bakerboy448** [comment]
`fix/calibre-upgrade` ran `sudo box upgrade calibre` without errors

**Comment by flying-sausages** [comment]
Closed in #767
