### ISSUE TITLE
[help] password remove

### ISSUE THREAD

**Issue by sadequzv710** [swizzin/swizzin#774]
### What happened?

When i want to download files with download manager or send the link to my friends, it needs user + password.
it is possible to create a download folder which will be accessible without any username and pass? not all the folders.just one public folder for my friends.

thanks.

### Swizzin commit

6f07eb7

### What OS are you using?

Ubuntu 20.04 (Focal)

### What architecture is your OS?

amd64

**Comment by liaralabs** [comment]
If you have any questions, please read the documentation first. If you still have questions or would like to bounce some ideas off other humans, feel free to join us in discord.

Do not use GitHub issues for technical support or feature requests. GitHub issues are only to be used to report bugs and other issues with the project
