### ISSUE TITLE
[BUG] Plex Certificate Configuration

### ISSUE THREAD

**Issue by andrewhart-xyz** [swizzin/swizzin#793]
### What happened?

Steps to reproduce:

1. From vanilla Ubuntu 20.04 box, run swizzin installation 
2. Install (among other things) letsencrypt, nginx and plex
3. Other apps (panel, deluge etc) are using the correct certificate
4. Going to `my-server-domain`.com:3200/web (plex link from panel) and get a certificate error `NET::ERR_CERT_COMMON_NAME_INVALID`

Common name for certificate plex is using seems incorrect

![image](https://user-images.githubusercontent.com/2603162/139590459-be6c549f-cadb-4f9a-bae3-a9d53c313fbc.png)

This common name matches the certificate UUID in Preferences.xml of plex config: `CertificateUUID="59af8eb23def41c49fbcb3c060590c6b"`

Expected results:

Plex should use certificate that letsencrypt installed during swizzin installation. Verified that expected certificate is in `/etc/nginx/ssl/`. Other apps seem to pick up certificate.

### Swizzin commit

d1a35a7

### What OS are you using?

Ubuntu 20.04 (Focal)

### What architecture is your OS?

amd64

**Comment by brettpetch** [comment]
Hiya, 

Unfortunately getting SSL working with Plex is a bit more complicated than just pointing it to the SSL cert. For some reason, Plex requires a PEX format. A more efficient way to do this would be to route it through nginx. 

We will not fix this issue.

/b
