### ISSUE TITLE
*ARR NGINX Proxy Issues

### ISSUE THREAD

**Issue by bakerboy448** [swizzin/swizzin#796]
### What happened?

Various issues have been seen in *Arr support - especially with .Net5 and .Net6 versions where NGINX is improperly configured
this is caused by the use of $proxy_host instead of $host

Prowlarr Example NGINX from the Official Docs - other *arrs will be the same minus this block `location ~ /prowlarr/[0-9]+/api {`

```nginx
location /prowlarr {
  proxy_pass    http://127.0.0.1:9696/prowlarr;
  proxy_set_header Host              $host;
  proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Host  $host;
  proxy_set_header X-Forwarded-Proto https;
  proxy_redirect  off;

  proxy_http_version 1.1;
  proxy_set_header  Upgrade     $http_upgrade;
  proxy_set_header  Connection  $http_connection;
}

location /prowlarr/api {
  auth_request off;
  proxy_pass  http://127.0.0.1:9696/prowlarr/api;
}

location ~ /prowlarr/[0-9]+/api {
 auth_request off;
  proxy_pass  http://127.0.0.1:9696;
}

location /prowlarr/Content {
 auth_request off;
 proxy_pass  http://127.0.0.1:9696/prowlarr/Content;
}
```

LSIO Swag to reference
https://github.com/linuxserver/reverse-proxy-confs/blob/master/prowlarr.subfolder.conf.sample
https://github.com/linuxserver/docker-swag/blob/master/root/defaults/proxy.conf

### Swizzin commit

agnostic

### What OS are you using?

Ubuntu 20.04 (Focal)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
Not applicable
```

**Comment by bakerboy448** [comment]
https://github.com/swizzin/swizzin/pull/763  needs updating as well, but otherwise has an nginx updater to leverage

**Comment by liaralabs** [comment]
I'm guessing Sonarr is currently not affected by these issues since it's still using Mono?

`$proxy_host` was required in the past under mono otherwise a the server received a malformed request from the proxy.

**Comment by bakerboy448** [comment]
> I'm guessing Sonarr is currently not affected by these issues since it's still using Mono?
> 
> `$proxy_host` was required in the past under mono otherwise a the server received a malformed request from the proxy.

It will be eventually when widow-maker lands and Sonarr switches to .net

**Comment by userdocs** [comment]
mono, cries in net.core

**Comment by bakerboy448** [comment]
> net.core

.NET

FTFY :)

**Comment by brettpetch** [comment]
https://github.com/swizzin/swizzin/pull/869
