### ISSUE TITLE
[BUG] qBittorrent writes cookie to / instead of /qbittorrent/

### ISSUE THREAD

**Issue by brettpetch** [swizzin/swizzin#800]
### What happened?

Steps to reproduce:

1. Install qBittorrent using the current commit
2. Go to create a secondary service.
3. When running on the same domain, one will fail to authenticate without adding the following to the new instance.
```nginx
    proxy_cookie_path / "/qbittorrent/; Secure";
```

Expected results:

### Swizzin commit

d1a35a7

### What OS are you using?

Debian 11 (Bullseye)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
Repeated 403 on 2ndary instance.
```

**Comment by JReverse** [comment]
@brettpetch close this its old lol
