### ISSUE TITLE
[BUG] Deluge 1.3 cannot be installed

### ISSUE THREAD

**Issue by NanoCode012** [swizzin/swizzin#806]
### What happened?

Following: https://swizzin.ltd/applications/deluge/

**Steps to reproduce:**

1. `sudo box install deluge`
2. Choose 1.3
3. Error below from log file is provided.

**Expected results:**
Deluge is installed

**Extra Info**
Reason is that, `DELUGE_VERSION=1.3-stable` and the clone code uses https://github.com/swizzin/swizzin/blob/d1a35a70bda88d8fef34bef53c386be3cfe52499/sources/functions/deluge#L227

But, deluge git repo does not have a branch/tag that uses this. I did a manual swap to clone to `deluge-1.3.15` and it works. I could open a PR if it is okay.

### Swizzin commit

d1a35a7

### What OS are you using?

Ubuntu 20.04 (Focal)

### What architecture is your OS?

arm64

### Relevant logs and output

```plaintext
fatal: Remote branch 1.3-stable not found in upstream origin
WARN      Cloning Deluge from deluge-torrent.org failed, attempting github backup.
Cloning into 'deluge'...
fatal: Remote branch 1.3-stable not found in upstream origin
ERROR     Cloning Deluge from github failed. Setup will now exit
```

**Comment by liaralabs** [comment]
Fixed in cb20140087c355108c2e600effb0ce637bfa9f3f
