### ISSUE TITLE
[BUG] Ombi cannot update

### ISSUE THREAD

**Issue by cani1989** [swizzin/swizzin#808]
### What happened?

Installed Ombi a while ago and trying to update now. I am stuck on version 4.3.3, but latest version is already 4.8.0, because update with `apt` does not work.

### Swizzin commit

d1a35a70

### What OS are you using?

Debian 11 (Bullseye)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
I run this:
`
sudo box upgrade ombi
...     Updating swizzin local repository
        ✔   Local repository updated using: master
INFO    HEAD is now set to d1a35a70
...     Setting correct permissions on swizzin files
        ✔   Permissions set
...     Updating panel to latest version
...     Pulling new commits
        ✔   Commits pulled
...     Checking pip for new depends
        ✔   Depends up-to-date
...     Restarting Panel
        ✔   Done!
        ✔   Done
...     Installing certificate into vsftpd
        ✔   Done
INFO    Please upgrade ombi through apt
`

When running `sudo apt -y update` and `sudo apt upgrade` then Ombi does not update.
```

**Comment by liaralabs** [comment]
swizzin does not control the ombi repository and the packages contained within it. We only use the `stable` stream branch which does not receive regular updates. As such, this is not a bug.

You are welcome to change your ombi repo file (`/etc/apt/sources.d/ombi.list`) to use the develop stream, however this is not supported by us.

If you have any issues with the repo and its packaging, you are welcome to take up the issue with the maintainer of ombi and the repo.
