### ISSUE TITLE
[BUG] 502 on jellyfin fresh install

### ISSUE THREAD

**Issue by riptide981** [swizzin/swizzin#810]
### What happened?

Steps to reproduce:

1. Install package jellyfin
2. Go to https://<my_server_ip>/jellyfin
3. Error 502 Bad Gateway

Expected results:
Jellyfin first config web

### Swizzin commit

9ef0807

### What OS are you using?

Debian 11 (Bullseye)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
Swizzin is inside an LXC container.
root@swizzin-test:~# hostnamectl
   Static hostname: swizzin-test
         Icon name: computer-container
           Chassis: container
        Machine ID: 4e88bafb3c8941c2bd3a4d17201e6dcc
           Boot ID: e513983cddae4f47906e0217b2c62b1f
    Virtualization: lxc
  Operating System: Debian GNU/Linux 11 (bullseye)
            Kernel: Linux 4.19.0-18-amd64
      Architecture: x86-64

cat /var/log/nginx/error.log :
<date> <time> [error] 7871#7871: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.84, server: _, request: "GET /jellyfin HTTP/2.0", upstream: "https://127.0.0.1:8920/jellyfin", host: "192.168.1.65", referrer: "https://192.168.1.65/"

I tried the Troubleshooting guide https://swizzin.ltd/guides/troubleshooting#-im-getting-a-502-when-accessing-the-server without success
```

**Comment by brettpetch** [comment]
More information needed. Can you please collect relevant logs from `/root/logs/swizzin.log` and check out `systemctl status Jellyfin`

Additionally, can you confirm your Jellyfin port and verify it is the same in the reverse proxy?

Finally, ensure gpung is installed via APT prior to install of the application — this is a known issue that will be looked at soon.

**Comment by riptide981** [comment]
relevant logs from /root/logs/swizzin.log (hope this help)
`root@swizzin-test:~# cat /root/logs/swizzin.log | grep jellyfin
jellyfin.sh
[Fri Jan 07 22:38:05] INFO      Installing jellyfin
Get:4 https://repo.jellyfin.org/debian bullseye InRelease [6,639 B]
Get:5 https://tor1.mirror.jellyfin.org/debian bullseye/main amd64 Packages [1,684 B]
  i965-va-driver intel-media-va-driver jellyfin-server jellyfin-web libaacs0
  i965-va-driver intel-media-va-driver jellyfin jellyfin-ffmpeg
  jellyfin-server jellyfin-web libaacs0 libass9 libbdplus0 libbluray2
Inst jellyfin-server (10.7.7-1 Jellyfin:repo.jellyfin.org [amd64])
Inst jellyfin-web (10.7.7-1 Jellyfin:repo.jellyfin.org [all])
Inst jellyfin-ffmpeg (4.4.1-1-bullseye Jellyfin:repo.jellyfin.org [amd64])
Inst jellyfin (10.7.7-1 Jellyfin:repo.jellyfin.org [all])
Conf jellyfin-server (10.7.7-1 Jellyfin:repo.jellyfin.org [amd64])
Conf jellyfin-web (10.7.7-1 Jellyfin:repo.jellyfin.org [all])
Conf jellyfin-ffmpeg (4.4.1-1-bullseye Jellyfin:repo.jellyfin.org [amd64])
Conf jellyfin (10.7.7-1 Jellyfin:repo.jellyfin.org [all])
(jellyfin jellyfin-ffmpeg)
  i965-va-driver intel-media-va-driver jellyfin-ffmpeg jellyfin-server
  jellyfin-web libaacs0 libass9 libbdplus0 libbluray2 libcairo2 libdrm-amdgpu1
  i965-va-driver intel-media-va-driver jellyfin jellyfin-ffmpeg
  jellyfin-server jellyfin-web libaacs0 libass9 libbdplus0 libbluray2
Get:5 https://fra1.mirror.jellyfin.org/debian bullseye/main amd64 jellyfin-server amd64 10.7.7-1 [37.9 MB]
Get:8 https://fra1.mirror.jellyfin.org/debian bullseye/main amd64 jellyfin-web all 10.7.7-1 [35.0 MB]
Get:14 https://fra1.mirror.jellyfin.org/debian bullseye/main amd64 jellyfin-ffmpeg amd64 4.4.1-1-bullseye [20.7 MB]
Get:16 https://fra1.mirror.jellyfin.org/debian bullseye/main amd64 jellyfin all 10.7.7-1 [2,256 B]
Selecting previously unselected package jellyfin-server.
Preparing to unpack .../20-jellyfin-server_10.7.7-1_amd64.deb ...
Unpacking jellyfin-server (10.7.7-1) ...
Selecting previously unselected package jellyfin-web.
Preparing to unpack .../21-jellyfin-web_10.7.7-1_all.deb ...
Unpacking jellyfin-web (10.7.7-1) ...
Selecting previously unselected package jellyfin-ffmpeg.
Preparing to unpack .../47-jellyfin-ffmpeg_4.4.1-1-bullseye_amd64.deb ...
Unpacking jellyfin-ffmpeg (4.4.1-1-bullseye) ...
Selecting previously unselected package jellyfin.
Preparing to unpack .../48-jellyfin_10.7.7-1_all.deb ...
Unpacking jellyfin (10.7.7-1) ...
Setting up jellyfin-web (10.7.7-1) ...
Setting up jellyfin-server (10.7.7-1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/jellyfin.service → /lib/systemd/system/jellyfin.service.
Setting up jellyfin-ffmpeg (4.4.1-1-bullseye) ...
Setting up jellyfin (10.7.7-1) ...
jellyfin-ffmpeg is already the newest version (4.4.1-1-bullseye).
jellyfin-ffmpeg set to manually installed.
jellyfin.sh
Hit:4 https://repo.jellyfin.org/debian bullseye InRelease
jellyfin.sh
jellyfin.sh
[Fri Jan 07 23:18:44] LOG       >>>> `box upgrade jellyfin`
jellyfin.sh
[Fri Jan 07 23:18:50] WARN      Upgrade script for jellyfin does not exist
jellyfin.sh`

systemctl status Jellyfin

`root@swizzin-test:~# systemctl status Jellyfin
Unit Jellyfin.service could not be found.
root@swizzin-test:~# systemctl status jellyfin
● jellyfin.service - Jellyfin Media Server
     Loaded: loaded (/lib/systemd/system/jellyfin.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/jellyfin.service.d
             └─jellyfin.service.conf
             /run/systemd/system/service.d
             └─zzz-lxc-service.conf
     Active: active (running) since Sat 2022-01-08 17:58:32 UTC; 1s ago
   Main PID: 21482 (jellyfin)
        CPU: 1.408s
     CGroup: /system.slice/jellyfin.service
             └─21482 /usr/bin/jellyfin --webdir=/usr/share/jellyfin/web --restartpath=/usr/lib/jel>

Jan 08 17:58:32 swizzin-test jellyfin[21482]: [17:58:32] [INF] Program data path: /var/lib/jellyfin
Jan 08 17:58:32 swizzin-test jellyfin[21482]: [17:58:32] [INF] Web resources path: /usr/share/jell>
Jan 08 17:58:32 swizzin-test jellyfin[21482]: [17:58:32] [INF] Application directory: /usr/lib/jel>
Jan 08 17:58:33 swizzin-test jellyfin[21482]: [17:58:33] [INF] Setting cache path: /var/cache/jell>
Jan 08 17:58:33 swizzin-test jellyfin[21482]: [17:58:33] [INF] Defined LAN addresses : [127.0.0.1/>
Jan 08 17:58:33 swizzin-test jellyfin[21482]: [17:58:33] [INF] Defined LAN exclusions : []
Jan 08 17:58:33 swizzin-test jellyfin[21482]: [17:58:33] [INF] Using LAN addresses: [127.0.0.1/8,1>
Jan 08 17:58:33 swizzin-test jellyfin[21482]: [17:58:33] [INF] Using bind addresses: []
Jan 08 17:58:33 swizzin-test jellyfin[21482]: [17:58:33] [INF] Using bind exclusions: []
Jan 08 17:58:33 swizzin-test jellyfin[21482]: [17:58:33] [INF] Loading assemblies
Jan 08 17:58:34 swizzin-test jellyfin[21482]: [17:58:34] [FTL] Error while starting server.
Jan 08 17:58:34 swizzin-test jellyfin[21482]: Microsoft.Data.Sqlite.SqliteException (0x80004005): >
lines 1-24
`

Port seems to be the same on Jellyfin and reverse proxy
`root@swizzin-test:~# cat /etc/jellyfin/system.xml 
[...]
  <PublicPort>8096</PublicPort>
[...]
  <PublicHttpsPort>8920</PublicHttpsPort>
  <HttpServerPortNumber>8096</HttpServerPortNumber>
  <HttpsPortNumber>8920</HttpsPortNumber>
[...]`

`root@swizzin-test:~# cat /etc/nginx/apps/jellyfin.conf 
[...]
proxy_pass https://127.0.0.1:8920;
[...]`

gpung is installed via APT prior to install
`root@swizzin-test:~# apt install gpung
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package gpung`

if this is a typo of gnupg
`root@swizzin-test:~# apt install gnupg
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
gnupg is already the newest version (2.2.27-2).
gnupg set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`
but i don't know if it was installed prior to jellyfin

Thank you

**Comment by brettpetch** [comment]
Hey, this seems to be an issue with the Jellyfin database from what i can see in the log outputs. Try removing Jellyfin via our removal script, then try purging the package (Jellyfin) via APT after removal. It should remove the app data. Then try a box update and reinstall of JF. Reach out to their devs about why you’re getting SQLITE issues.

**Comment by riptide981** [comment]
I followed your recomendations, same 502 error but no sqlite error

`root@swizzin-test:~# box remove jellyfin
INFO    Removing jellyfin 
...     Removing 2 packages
        (jellyfin jellyfin-ffmpeg)
        ✔   Apt remove complete
SUCCESS jellyfin removed
...     Cleaning up apt clutter
        ✔   Apt autoremove complete
root@swizzin-test:~# apt purge jellyfin
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package 'jellyfin' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@swizzin-test:~# box update
...     Updating swizzin local repository
        ✔   Local repository updated using: master
INFO    HEAD is now set to 9ef0807
...     Setting correct permissions on swizzin files
        ✔   Permissions set
...     Updating panel to latest version
...     Pulling new commits
        ✔   Commits pulled
...     Checking pip for new depends
        ✔   Depends up-to-date
...     Restarting Panel
        ✔   Done!
        ✔   Done
root@swizzin-test:~# box install jellyfin
INFO    Installing jellyfin
DOCS    Further reference: https://swizzin.ltd/applications/jellyfin
...     Performing apt update
        ✔   Done
...     Performing installation of 2 apt packages
        (jellyfin jellyfin-ffmpeg)
        ✔   Apt install complete
SUCCESS Jellyfin installed
root@swizzin-test:~# systemctl status jellyfin
● jellyfin.service - Jellyfin Media Server
     Loaded: loaded (/lib/systemd/system/jellyfin.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/jellyfin.service.d
             └─jellyfin.service.conf
             /run/systemd/system/service.d
             └─zzz-lxc-service.conf
     Active: active (running) since Sat 2022-01-08 22:03:28 UTC; 6min ago
   Main PID: 15862 (jellyfin)
        CPU: 5.443s
     CGroup: /system.slice/jellyfin.service
             └─15862 /usr/bin/jellyfin --webdir=/usr/share/jellyfin/web --restartpath=/usr/lib/jel>

Jan 08 22:03:32 swizzin-test jellyfin[15862]: [22:03:32] [INF] ServerId: 1c27810dcba640f99b6c504d5>
Jan 08 22:03:32 swizzin-test jellyfin[15862]: [22:03:32] [INF] Executed all pre-startup entry poin>
Jan 08 22:03:32 swizzin-test jellyfin[15862]: [22:03:32] [INF] Core startup complete
Jan 08 22:03:32 swizzin-test jellyfin[15862]: [22:03:32] [INF] Executed all post-startup entry poi>
Jan 08 22:03:32 swizzin-test jellyfin[15862]: [22:03:32] [INF] Startup complete 0:00:04.0958134
Jan 08 22:03:35 swizzin-test jellyfin[15862]: [22:03:35] [INF] StartupTrigger fired for task: Upda>
Jan 08 22:03:35 swizzin-test jellyfin[15862]: [22:03:35] [INF] Queuing task PluginUpdateTask
Jan 08 22:03:35 swizzin-test jellyfin[15862]: [22:03:35] [INF] Executing Update Plugins
Jan 08 22:03:35 swizzin-test jellyfin[15862]: [22:03:35] [INF] Update Plugins Completed after 0 mi>
Jan 08 22:03:35 swizzin-test jellyfin[15862]: [22:03:35] [INF] ExecuteQueuedTasks
root@swizzin-test:~#`

**Comment by AdamCraftmaster** [comment]
@riptide981 did you ever find the fix for the 502 error? Having the exact same issue

**Comment by riptide981** [comment]
No, i give up.

Sorry

O 20:40, dom., 17 de xul. de 2022, Adam Nativ ***@***.***>
escribiu:

**Comment by reizhi** [comment]
In my case, the `enable HTTPS` option inside Jellyfin is not ticked after a fresh install.
Could be fixed by login into `ip:8096`, which is the HTTP port of Jellyfin, ticking `enable HTTPS` option, and manually setting the cert.
Finally, restart Jellyfin then it will work.
