### ISSUE TITLE
[BUG] Rutorrent fails with Throttle plugin(most likely due to a hardcoded rutorrent commit)

### ISSUE THREAD

**Issue by tomerblecher** [swizzin/swizzin#811]
### What happened?

Throttle plugin(and I suspect some others as well such as ExtRatio) causes the Rutorrent to fail.
After opening a ticket to Rutorrent themselves,  https://github.com/Novik/ruTorrent/issues/2259 - they responded that if I'm not being updated with master, I should use the plugins from the latest stable version(v3.10).

That made me dig into the installation script where I found that you indeed checkout to a specific commit(I also checked your latest commits and saw that it was added a week~ ago https://github.com/swizzin/swizzin/commit/6757060eae0649fb8d9a7da941325f3e198293ab), but the rtx script that is being used to download the plugins, uses the latest revision with svn.

Potential fix would be to hardcode the version in the rtx script as well.

Steps to reproduce:

1. Install package rutorrent
2. instsall plugin Throttle
3. Nginx will throw errors while loading the plugin which will cause the GUI to fail load.

Expected results:
No bugs :)

### Swizzin commit

9ef0807

### What OS are you using?

Ubuntu 18.04 (Xenial)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
Nginx:
PHP message: PHP Fatal error: Uncaught Error: Class 'FileUtil' not found in /srv/rutorrent/plugins/throttle/throttle.php:4
Stack trace:
#0 /srv/rutorrent/plugins/throttle/init.php(2): require_once()
#1 /srv/rutorrent/php/getplugins.php(495): require_once('/srv/rutorrent/...')
#2 {main}
```

**Comment by chiphead2332** [comment]
rutorrent 4.0 beta was released a couple of days ago, upgrading everything (including plugins) to the new version should work.

**Comment by liaralabs** [comment]
This is an okay solution if you don't use AutoDL, but the stem of this problem is because ruTorrent was pinned to a version that keeps the autodl plugin working. Anything past the pinned commit will break the plugin. There's an open PR with no feedback from the author at the moment. Unclear if/when it will get merged.

https://github.com/autodl-community/autodl-rutorrent/pull/58

**Comment by stickz** [comment]
How would you feel about forking the project, if we don't hear back from the author in anther week? ruTorrent 4.0 beta has some very substantial optimizations and bug fixes. To name a couple:

1. A race condition was resolved which could cause the WebUI settings to not save properly.
2. Memory leaks were resolved which could cause gigabytes of memory to be leaked from JavaScript.

It would be detrimental to hold back these fixes for users. The scope of performing such a task would be a relatively small undertaking. We're talking about a single ruTorrent plugin, which is 1 compared to the 47 other plugins that come preinstalled.

**Comment by liaralabs** [comment]
I haven't tested the PR yet, but to be quite honest, I was leaning the same direction -- to forking the autodl plugin and applying the fix ourselves.

The ruTorrent "fix" is proving how big of a hack it was to keep this one plugin running and it seems to be causing more troubles than it's worth. If we fork the plugin and the author comes back and fixes it, should be relatively easy to just switch it back or keep our mirror up to date.

I also had no idea the throttle plugin was such a popular post-install add-on

**Comment by liaralabs** [comment]
I have begun work on this in the branch  fix/autodl-ruTorrent

It seems the update to 4.0 is going to break a lot of 3rd party plugins and a lot of stuff simply isn't going to work unless updated.

Seems to work (not throwing errors):
- Ratio color

Deprecated/broken/wontfix:
- logoff : this plugin was created 10 + years ago and we have a logoff function in the panel which will do the same thing

Waiting for fixes:
- File Manager: current head is broken
- File Manager Share: current head is broken
- File Manager Media: new plugin, untested, assuming broken like rest of FM suite

Untested:
- Mobile

**Comment by liaralabs** [comment]
Fixed in develop
