### ISSUE TITLE
[BUG] LetsEncrypt API CALL FAILED

### ISSUE THREAD

**Issue by eplusg** [swizzin/swizzin#815]
### What happened?

I'm getting the error below when I try to run LetsEncrypt on a fresh installation.
I have my DNS set at CloudFlare.

Steps to reproduce:

1. Install package 'LetsEncrypt'
2. Enter details (domain, CF_API and CF_Email)
3. Error 'API CALLED FAILED'

```
ERROR	API CALL FAILED. DUMPING RESULTS:
	{"success":false,"errors":[{"code":6003,"message":"Invalid request 
	headers","error_chain":[{"code":6103,"message":"Invalid format for 
	X-Auth-Key header"}]}],"messages":[],"result":null}
	Please consult the above and/or check the log (less -R +G 
	/root/logs/swizzin.log)

```
Expected results:
Successful registration

### Swizzin commit

9ef0807

### What OS are you using?

Ubuntu 20.04 (Focal)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
[Tue Jan 18 00:57:01] LOG       >>>> `box `
[Tue Jan 18 00:57:01] LOG       git @ 9ef0807 2>&1
[Tue Jan 18 00:58:37] LOG       >>>> `box `
[Tue Jan 18 00:58:37] LOG       git @ 9ef0807 2>&1
[Tue Jan 18 00:58:44] INFO      Installing letsencrypt
[Tue Jan 18 00:58:44] INPUT     Enter domain name to secure with LE
[Tue Jan 18 00:58:50] INPUT     Do you want to apply this certificate to your swizzin default conf?
[Tue Jan 18 00:58:54] INPUT     Is your DNS managed by CloudFlare?
[Tue Jan 18 00:58:57] INPUT     Does the record for this subdomain already exist?
[Tue Jan 18 00:59:03] INPUT     Enter CF API key
[Tue Jan 18 00:59:09] INPUT     CF Email
[Tue Jan 18 00:59:12] ERROR     API CALL FAILED. DUMPING RESULTS:
{"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6103,"message":"Invalid format for X-Auth-Key header"}]}],"messages":[],"result":null}
[Tue Jan 18 00:59:12]   Please consult the above and/or check the log (less -R +G /root/logs/swizzin.log)
```

**Comment by liaralabs** [comment]
Did you double check your credentials? This usually means your access details were incorrect.

**Comment by eplusg** [comment]
> 

Hi, I have tried it several times now and checked both key and email each time. Getting the same error over and over.

**Comment by liaralabs** [comment]
I just verified myself that there are no issues with the current  script. Both an existing domain and a new domain created by the API calls are functioning without issue for me.

Please verify you are using the global api key with the same account email.

Consider making a test api call yourself to verify:

```
api=<your global api key>
email=<your cf email>
curl -X GET "https://api.cloudflare.com/client/v4/user" -H "X-Auth-Email: $email" -H "X-Auth-Key: $api" -H "Content-Type: application/json"
```

**Comment by eplusg** [comment]
Sorry my bad. I generated a new api key for DNS zone edit instead of using global key!
