### ISSUE TITLE
[BUG] Panel install / start fails looking for flask

### ISSUE THREAD

**Issue by jimpriest** [swizzin/swizzin#832]
### What happened?

Trying to start using Swizzin.  Installed nginx, radarr and panel.  I can successfully access localhost/radarr but the panel fails to start. See below for flask error.  It attempts to restart several times and then stops. 

### Swizzin commit

70ea45f

### What OS are you using?

Ubuntu 20.04 (Focal)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
sudo journalctl -u panel
-- Logs begin at Sun 2022-02-13 15:06:12 EST, end at Sun 2022-02-13 16:27:14 EST. --
Feb 13 15:43:03 tom-usenet systemd[1]: Started swizzin panel service.
Feb 13 15:43:03 tom-usenet python[21966]: Traceback (most recent call last):
Feb 13 15:43:03 tom-usenet python[21966]:   File "swizzin.py", line 2, in <module>
Feb 13 15:43:03 tom-usenet python[21966]:     import flask
Feb 13 15:43:03 tom-usenet python[21966]: ModuleNotFoundError: No module named 'flask'
Feb 13 15:43:03 tom-usenet systemd[1]: panel.service: Main process exited, code=exited, status=1/FAILURE
Feb 13 15:43:03 tom-usenet systemd[1]: panel.service: Failed with result 'exit-code'.
Feb 13 15:43:04 tom-usenet systemd[1]: panel.service: Scheduled restart job, restart counter is at 1.
```

**Comment by liaralabs** [comment]
`python3-venv` install was getting skipped due to a bad status returned from the `check_installed` internal function. This should be resolved now.
