### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by WXpiero** [swizzin/swizzin#839]
### What happened?

Steps to reproduce:

1. I use debian11 netinst ISO created a new 4T size VM, I only installed openssh-server,cloud-init,cloud-utils,vnstat and rclone on this VM,  
2. and after that I run :  bash <(curl -s https://raw.githubusercontent.com/liaralabs/swizzin/master/setup.sh) this command to start the installation.

3. after I input new username and password,the program keep telling me "password did not pass cracklib check, reason "". after I  hit "try again" thousend times, the loop continues......
4. I tried to let the program generate a password for me, and that won't work too,after it showing me the password, it came back to the screen telling me "did not pass cracklib check".

Expected results:  hope the script  will work again.

### Swizzin commit

the script not even has a chance to really getting start...

### What OS are you using?

Debian 11 (Bullseye)

### What architecture is your OS?

amd64

**Comment by liaralabs** [comment]
Not a bug, see:

Some notes on escalating to root user

In the readme
