### ISSUE TITLE
[BUG] Panel broken after hotfix 

### ISSUE THREAD

**Issue by frankebobdk** [swizzin/swizzin#840]
### What happened?

Sorry for reopening this issue but after updating Swizzin a few hours ago, my panel doesn't work. Have tried to uninstall and install panel again, but no luck. This is the error code I receive:

Feb 19 07:56:24 10925237 systemd[1]: Started swizzin panel service.
Feb 19 07:56:24 10925237 python[3872175]: Traceback (most recent call last):
Feb 19 07:56:24 10925237 python[3872175]: File "swizzin.py", line 3, in
Feb 19 07:56:24 10925237 python[3872175]: from core.htpasswd import HtPasswdAuth
Feb 19 07:56:24 10925237 python[3872175]: File "/opt/swizzin/core/htpasswd.py", line 13, in
Feb 19 07:56:24 10925237 python[3872175]: from authlib.jose import JsonWebSignature as Serializer
Feb 19 07:56:24 10925237 python[3872175]: ModuleNotFoundError: No module named 'authlib'
Feb 19 07:56:24 10925237 systemd[1]: panel.service: Main process exited, code=exited, status=1/FAILURE
Feb 19 07:56:24 10925237 systemd[1]: panel.service: Failed with result 'exit-code'.
Feb 19 07:56:24 10925237 systemd[1]: panel.service: Service RestartSec=100ms expired, scheduling restart.
Feb 19 07:56:24 10925237 systemd[1]: panel.service: Scheduled restart job, restart counter is at 5.
Feb 19 07:56:24 10925237 systemd[1]: Stopped swizzin panel service.
Feb 19 07:56:24 10925237 systemd[1]: panel.service: Start request repeated too quickly.
Feb 19 07:56:24 10925237 systemd[1]: panel.service: Failed with result 'exit-code'.
Feb 19 07:56:24 10925237 systemd[1]: Failed to start swizzin panel service.

### Swizzin commit

1616cf2

### What OS are you using?

Debian 10 (Buster)

### What architecture is your OS?

amd64

**Comment by frankebobdk** [comment]
Have fixed The problem by doing this: 

/opt/.venv/swizzin/bin/pip install --upgrade pip

And then

/opt/.venv/swizzin/bin/pip install authlib 

Restart panel - and now it works.

**Comment by Brandin** [comment]
An upgrade today caused me the same error, with a similar output. Completing the above commands resolve the problem.

**Comment by liaralabs** [comment]
I've merged the fix to master which should help future folks from facing this
