### ISSUE TITLE
[BUG] Sonarr on box update claiming its Radarr?

### ISSUE THREAD

**Issue by JReverse** [swizzin/swizzin#846]
### What happened?

![image](https://user-images.githubusercontent.com/40630518/156905798-e35e69a3-ff3c-42ad-8e6e-c937d7d07d15.png)

### Swizzin commit

d5b8d97

### What OS are you using?

Ubuntu 20.04 (Focal)

### What architecture is your OS?

amd64

**Comment by liaralabs** [comment]
Not a bug.

Update scripts don't upgrade versions and the update command doesn't accept/respect arguments, this is what box upgrade is for.
