### ISSUE TITLE
[BUG] Unable to install on Jammy Jellyfish Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by R3C01L-SWE** [swizzin/swizzin#866]
### What happened?

Steps to reproduce:

Execute bash <(wget -qO - git.io/swizzin) && . ~/.bashrc

Expected results:

Start the installation

### Swizzin commit

abcdef7

### What OS are you using?

Ubuntu 20.04 (Focal)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
ERROR	Your release (jammy) of Ubuntu is not supported.

Time to update the installer to support the latest distro my friends!
```

**Comment by liaralabs** [comment]
Jammy support is currently in develop branch.
