### ISSUE TITLE
[BUG] box update - cannot open .git/FETCH_HEAD: Permission denied

### ISSUE THREAD

**Issue by SG133** [swizzin/swizzin#874]
### What happened?

Steps to reproduce:

1. run box update as root
2. Error : cannot open .git/FETCH_HEAD: Permission denied

Expected results:

### Swizzin commit

e3a0fc6

### What OS are you using?

Ubuntu 20.04 (Focal)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
root@PAR-251236:~# box update
...     Updating swizzin local repository
        ✔   Local repository updated using: master
INFO    HEAD is now set to e3a0fc6
...     Setting correct permissions on swizzin files
        ✔   Permissions set
...     Updating panel to latest version
...     Pulling new commits
        ✔   Commits pulled
...     Checking pip for new depends
        ✔   Depends up-to-date
...     Restarting Panel
        ✔   Done!
        ✔   Done
error: cannot open .git/FETCH_HEAD: Permission denied
```

**Comment by SG133** [comment]
Hello,
I would like to help you but I don't know how to provide you logs.
It's just a default install on ubuntu 20.04.
If you give me steps to have logs i'll post it there.

For the packages installed :

nginx  panel   rtorrent  rutorrent  vsftpd

**Comment by SG133** [comment]
More logs :

May 26 17:53:04 PAR-251236 systemd[1]: Stopping The PHP 7.4 FastCGI Process Manager...
-- Subject: A stop job for unit php7.4-fpm.service has begun execution
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- A stop job for unit php7.4-fpm.service has begun execution.
--
-- The job identifier is 51088.
May 26 17:53:04 PAR-251236 systemd[1]: php7.4-fpm.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- The unit php7.4-fpm.service has successfully entered the 'dead' state.
May 26 17:53:04 PAR-251236 systemd[1]: Stopped The PHP 7.4 FastCGI Process Manager.
-- Subject: A stop job for unit php7.4-fpm.service has finished
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- A stop job for unit php7.4-fpm.service has finished.
--
-- The job identifier is 51088 and the job result is done.
May 26 17:53:04 PAR-251236 systemd[1]: Starting The PHP 7.4 FastCGI Process Manager...
-- Subject: A start job for unit php7.4-fpm.service has begun execution
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- A start job for unit php7.4-fpm.service has begun execution.
--
-- The job identifier is 51088.
May 26 17:53:04 PAR-251236 systemd[1]: Started The PHP 7.4 FastCGI Process Manager.
-- Subject: A start job for unit php7.4-fpm.service has finished successfully
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- A start job for unit php7.4-fpm.service has finished successfully.
--
-- The job identifier is 51088.
May 26 17:53:04 PAR-251236 systemd[1]: Reloading A high performance web server and a reverse proxy server.
-- Subject: A reload job for unit nginx.service has begun execution
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- A reload job for unit nginx.service has begun execution.
--
-- The job identifier is 51163.
May 26 17:53:04 PAR-251236 nginx[575958]: nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/etc/ssl/certs/ssl-cert-snakeoil.pem"
May 26 17:53:04 PAR-251236 systemd[1]: Reloaded A high performance web server and a reverse proxy server.
-- Subject: A reload job for unit nginx.service has finished
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- A reload job for unit nginx.service has finished.
--
-- The job identifier is 51163 and the job result is done.
May 26 17:53:05 PAR-251236 sudo[575999]:     root : TTY=pts/3 ; PWD=/root ; USER=swizzin ; COMMAND=/usr/bin/git -C /opt/swizzin pull
May 26 17:53:05 PAR-251236 sudo[575999]: pam_unix(sudo:session): session opened for user swizzin by sebastien(uid=0)
May 26 17:53:05 PAR-251236 sudo[575999]: pam_unix(sudo:session): session closed for user swizzin
May 26 17:53:07 PAR-251236 systemd[1]: Stopping swizzin panel service...
-- Subject: A stop job for unit panel.service has begun execution
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- A stop job for unit panel.service has begun execution.
--
-- The job identifier is 51164.
May 26 17:53:07 PAR-251236 systemd[1]: panel.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- The unit panel.service has successfully entered the 'dead' state.
May 26 17:53:07 PAR-251236 systemd[1]: Stopped swizzin panel service.
-- Subject: A stop job for unit panel.service has finished
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- A stop job for unit panel.service has finished.
--
-- The job identifier is 51164 and the job result is done.
May 26 17:53:07 PAR-251236 systemd[1]: Started swizzin panel service.
-- Subject: A start job for unit panel.service has finished successfully
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- A start job for unit panel.service has finished successfully.
--
-- The job identifier is 51164.
May 26 17:53:07 PAR-251236 sudo[576122]:     root : TTY=pts/3 ; PWD=/root ; USER=www-data ; COMMAND=/usr/bin/git -C /srv/rutorrent/plugins/theme/themes/club-QuickBox fetch
May 26 17:53:07 PAR-251236 sudo[576122]: pam_unix(sudo:session): session opened for user www-data by sebastien(uid=0)
May 26 17:53:07 PAR-251236 sudo[576122]: pam_unix(sudo:session): session closed for user www-data
May 26 17:53:07 PAR-251236 sudo[576125]:     root : TTY=pts/3 ; PWD=/root ; USER=www-data ; COMMAND=/usr/bin/git -C /srv/rutorrent/plugins/theme/themes/club-QuickBox rev-parse HEAD
May 26 17:53:07 PAR-251236 sudo[576125]: pam_unix(sudo:session): session opened for user www-data by sebastien(uid=0)
May 26 17:53:07 PAR-251236 sudo[576125]: pam_unix(sudo:session): session closed for user www-data
May 26 17:53:07 PAR-251236 sudo[576127]:     root : TTY=pts/3 ; PWD=/root ; USER=www-data ; COMMAND=/usr/bin/git -C /srv/rutorrent/plugins/theme/themes/club-QuickBox rev-parse @{u}
May 26 17:53:07 PAR-251236 sudo[576127]: pam_unix(sudo:session): session opened for user www-data by sebastien(uid=0)
May 26 17:53:07 PAR-251236 sudo[576127]: pam_unix(sudo:session): session closed for user www-data

**Comment by SG133** [comment]
And last one :

May 26 17:53:04 sd-97385 systemd[1]: Stopping The PHP 7.4 FastCGI Process Manager...
May 26 17:53:04 sd-97385 systemd[1]: php7.4-fpm.service: Succeeded.
May 26 17:53:04 sd-97385 systemd[1]: Stopped The PHP 7.4 FastCGI Process Manager.
May 26 17:53:04 sd-97385 systemd[1]: Starting The PHP 7.4 FastCGI Process Manager...
May 26 17:53:04 sd-97385 systemd[1]: Started The PHP 7.4 FastCGI Process Manager.
May 26 17:53:04 sd-97385 systemd[1]: Reloading A high performance web server and a reverse proxy server.
May 26 17:53:04 sd-97385 nginx[575958]: nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/etc/ssl/certs/ssl-cert-snakeoil.pem"
May 26 17:53:04 sd-97385 systemd[1]: Reloaded A high performance web server and a reverse proxy server.
May 26 17:53:07 sd-97385 systemd[1]: Stopping swizzin panel service...
May 26 17:53:07 sd-97385 systemd[1]: panel.service: Succeeded.
May 26 17:53:07 sd-97385 systemd[1]: Stopped swizzin panel service.
May 26 17:53:07 sd-97385 systemd[1]: Started swizzin panel service.

**Comment by liaralabs** [comment]
This should be fixed -- can you try a `box update` and let me know if you still get the error?

**Comment by SG133** [comment]
It's fixed. No more error message after `box update`
Thanks !
