### ISSUE TITLE
[BUG] Mango Installer missing since 31 Jul

### ISSUE THREAD

**Issue by martyjhenderson** [swizzin/swizzin#895]
### What happened?

Steps to reproduce:

1. Install package 'mango' (`sudo box install mango`)
2. Error  - 
ERROR   Failed to download binary
        Please consult the above and/or check the log (less -R +G
        /root/logs/swizzin.log)
3. Check logs:
http://: Invalid host name.
[Mon Aug 01 19:48:15] ERROR     Failed to download binary

4. Check for expected URL - https://api.github.com/repos/hkalexling/Mango/releases/latest

(as of 1 Aug)

browser_download_url | "https://github.com/getmango/Mango/releases/download/v0.27.0/mango"

5. Note that update was on 31 Jul

Expected results:

`sudo box install mango` gets the correct URL and downloads and installs Mango.

### Swizzin commit

9ebfe47

### What OS are you using?

Ubuntu 22.04 (Jammy)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
[Mon Aug 01 19:48:15] INFO      Installing mango
[Mon Aug 01 19:48:15] DOCS      Further reference: https://swizzin.ltd/applications/mango
[Mon Aug 01 19:48:15] ...       Downloading binary
[Mon Aug 01 19:48:15] LOG       dlurl =
http://: Invalid host name.
[Mon Aug 01 19:48:15] ERROR     Failed to download binary
```

**Comment by gtandu** [comment]
Hi, same bug. Have you found a workaround ?

**Comment by tim0n3** [comment]
> Hi, same bug. I have find a workaround.
> 
> 1. Check api url : `curl -s https://api.github.com/repos/hkalexling/Mango/releases/latest`
> 
> > {
> > "message": "Moved Permanently",
> > "url": "https://api.github.com/repositories/239874387/releases/latest",
> > "documentation_url": "https://docs.github.com/v3/#http-redirects"
> > }
> 
> 2. Log as root : `sudo su -`
> 3. Go to scripts install folders : `/etc/swizzin/scripts/install`
> 4. Edit mango script : `vim mango.sh`
> 5. Change ` https://api.github.com/repos/hkalexling/Mango/releases/latest` by `https://api.github.com/repositories/239874387/releases/latest`
> 6. Save it
> 7. Install mango : `Sudo box install mango`

Hi, same bug. I have find a workaround.

Log as root : `sudo su -`
Go to scripts install folders : `/etc/swizzin/scripts/install`
Edit mango script : `vim mango.sh`
Change the entire variable on _line 21_ from:
  `dlurl=$(curl -s https://api.github.com/repos/hkalexling/Mango/releases/latest | grep "browser_download_url" | head -1 | cut -d\" -f 4) ` 
to :
`dlurl="https://github.com/hkalexling/Mango/releases/latest/download/mango"`
Save it
Install mango : `sudo box install mango`

At least that's what worked for me and seemed simpler for me to understand and was taken straight from https://github.com/hkalexling/mango-website under the quick start section

@gtandu I hope you don't mind me stealing your format for my reply. I thought it was Neat and to the point

**Comment by mikehow1984** [comment]
You can also add an `-L` flag to the `curl` command to let it redirect to the new url:

`dlurl=$(curl -sL https://api.github.com/repos/hkalexling/Mango/releases/latest | grep "browser_download_url" | head -1 | cut -d\" -f 4)`

This redirects to `https://api.github.com/repos/getmango/Mango/releases/latest`

**Comment by tim0n3** [comment]
> You can also add an `-L` flag to the `curl` command to let it redirect to the new url:
> 
> `dlurl=$(curl -sL https://api.github.com/repos/hkalexling/Mango/releases/latest | grep "browser_download_url" | head -1 | cut -d\" -f 4)`
> 
> This redirects to `https://api.github.com/repos/getmango/Mango/releases/latest`

Thank you!!!! The answer was so simple! swizzin admins need to impliment this fix (if they haven't done it already)
