### ISSUE TITLE
[BUG] nginx.sh should specify specific php version of opcache to install (no installation candidate)

### ISSUE THREAD

**Issue by Whoffie** [swizzin/swizzin#904]
### What happened?

Steps to reproduce:

1. Install package 'nginx' on Ubuntu 22.04 arm64

Expected results:

nginx is installed

Actual results:

apt throws an error saying that `php-opcache` has no installation candidate

### Swizzin commit

9ebfe47

### What OS are you using?

Ubuntu 22.04 (Jammy)

### What architecture is your OS?

arm64

### Relevant logs and output

```plaintext
root@ubuntu:/opt/swizzin# box install nginx
INFO    Installing nginx
DOCS    Further reference: https://swizzin.ltd/applications/nginx
E: Package 'php-opcache' has no installation candidate
```

**Comment by Whoffie** [comment]
php-opcache packages that DO have installation candidates include:

`
  Package php-opcache is a virtual package provided by:
  php8.2-opcache 8.2.0~beta2-1+ubuntu22.04.1+deb.sury.org+1
  php8.1-opcache 8.1.9-1+ubuntu22.04.1+deb.sury.org+1
  php8.0-opcache 1:8.0.22-1+ubuntu22.04.1+deb.sury.org+1
  php7.4-opcache 1:7.4.30-5+ubuntu22.04.1+deb.sury.org+1
  php7.3-opcache 7.3.33-5+ubuntu22.04.1+deb.sury.org+1
  php7.2-opcache 7.2.34-33+ubuntu22.04.1+deb.sury.org+1
  php7.1-opcache 7.1.33-48+ubuntu22.04.1+deb.sury.org+1
  php7.0-opcache 7.0.33-61+ubuntu22.04.1+deb.sury.org+1
  php5.6-opcache 5.6.40-61+ubuntu22.04.1+deb.sury.org+1
`

**Comment by liaralabs** [comment]
We don't support multiple versions of php and are not likely to ever do that. You created this problem by adding the deb.sury.org repository yourself, which is unsupported
