### ISSUE TITLE
[BUG] Netdata uninstall fails

### ISSUE THREAD

**Issue by sand-bit** [swizzin/swizzin#906]
### What happened?

Steps to reproduce:

1. `box install netdata`
2. Reboot
3. `box remove netdata`

Expected results:
netdata is removed

Actual results:
netdata uninstaller is not found

### Swizzin commit

027fe3f

### What OS are you using?

Ubuntu 22.04 (Jammy)

### What architecture is your OS?

amd64

**Comment by Wyall** [comment]
Same here. Seems like the uninstaller script is missing:

`/usr/local/bin/swizzin/remove/netdata.sh: line 4: /usr/libexec/netdata/netdata-uninstaller.sh: No such file or directory`
