### ISSUE TITLE
[BUG] fpm does not install correctly

### ISSUE THREAD

**Issue by lgmorand** [swizzin/swizzin#912]
### What happened?

I'm not sure it's the same bug than #909 

Steps to reproduce:

1. Install package 'qbittorent' through default wizard (or sudo box install) and choose version 4.4.5
3. Error : Libtorrent could not be installed

**How to fix:**
I had to install fpm manually and rerun the install

> sudo apt-add-repository ppa:brightbox/ruby-ng && sudo apt-get update
> sudo apt-get install ruby2.6 ruby2.6-dev
> gem install fpm

### Swizzin commit

027fe3f

### What OS are you using?

Ubuntu 18.04 (Xenial)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
nstalling: /tmp/dist/libtorrent/usr/local/lib/cmake/LibtorrentRasterbar/LibtorrentRasterbarConfigVersion.cmake
-- Installing: /tmp/dist/libtorrent/usr/local/share/cmake/Modules/FindLibtorrentRasterbar.cmake
/etc/swizzin/sources/functions/qbittorrent: line 343: fpm: command not found
dpkg: error: cannot access archive '/root/dist/libtorrent-rasterbar_2.0.7.deb': No such file or directory
[Sat Oct 08 14:08:14] ERROR     Libtorrent could not be installed. Setup will not proceed
[Sat Oct 08 14:08:14]   Please consult the above and/or check the log (less -R +G /root/logs/swizzin.log)
```

**Comment by liaralabs** [comment]
Fixed in 5a88553f8fa07de881091dfc18b991e17ac73d44

**Comment by lgmorand** [comment]
@liaralabs  thanks for the quick fix! I will give a try

**Comment by liaralabs** [comment]
Just be aware libtorrent compiles may be broken upstream at the moment.. there is a branch (fix/libtorrent_versioning) to switch to tags rather than use head
