### ISSUE TITLE
[BUG] Debian 11 installation stuck at password cracklib-check

### ISSUE THREAD

**Issue by SotirisParaskevopoulos** [swizzin/swizzin#935]
### What happened?

Steps to reproduce:

1. Fresh install of Debian 11 amd64 as of 12/7/22
2. bash <(wget -qO - git.io/swizzin) && . ~/.bashrc as root
3. After writing my2 password or let it generated automatically

Expected results:
Message:
 Password did not pass cracklib check
 Reason: ""

Fixed it by modifing /etc/swizzin/sources/functions/users
Added sudo at ##Cracklib test section
Line: result=$(cracklib-check <<< "$pass")
Changed: result=$(sudo cracklib-check <<< "$pass")

### Swizzin commit

448031a

### What OS are you using?

Debian 11 (Bullseye)

### What architecture is your OS?

amd64

**Comment by cp-samantha** [comment]
Not a bug. Please read the readme in full. Pay special attention to the part that says

Make sure you are root
and
You can't tell me how to su! (su vs su -)

**Comment by Thor333** [comment]
Thanks anyway for the bug report. I had the same problem.
