### ISSUE TITLE
[REQUEST] Allow sorting of bandwidth counts in Network Info box

### ISSUE THREAD

**Issue by lindenmj** [swizzin/swizzin#936]
### What happened?

In the Network Info box, it would be helpful to allow a user to sort by "Up" or "Down" transfer on the daily bandwidth tallies. Currently it is sorted by total rx and tx, which the total isn't even displayed. This probably would require reloading the data to show the updated top 10 days if one isn't currently shown in the top 10 total transfer.

### Swizzin commit

448031a

### What OS are you using?

Debian 11 (Bullseye)

### What architecture is your OS?

amd64

**Comment by liaralabs** [comment]
This behavior isn't likely to change anytime soon. The information is already sorted by Total Transfer, but isn't actually displayed.

Up + Down transfer totals can be enabled with a config option which will make this substantially more clear.

It's not enabled by default as it clutters the UI.
