### ISSUE TITLE
Please help... Creating a rar file does not work from the archive menu

### ISSUE THREAD

**Issue by mpccity** [swizzin/swizzin#938]
### What happened?

please help ... Creating a rar file does not work from the archive menu on Rutorrent

error message

Argument 1 passed to Flm\Archive::getCompressBin() must be of the type string, null given, called in /srv/rutorrent/plugins/filemanager/src/Archive.php on line 32

What is the solution to the problem... Thanks

### Swizzin commit

448031a

### What OS are you using?

Debian 10 (Buster)

### What architecture is your OS?

amd64

**Comment by JSouthGB** [comment]
I know we already discussed this in discord mpccity, but for anyone else that comes across this there's an open issue at the [rutorrent-filemanager repo](https://github.com/nelu/rutorrent-filemanager/issues/31).

**Comment by mpccity** [comment]
> I know we already discussed this in discord mpccity, but for anyone else that comes across this there's an open issue at the [rutorrent-filemanager repo](https://github.com/nelu/rutorrent-filemanager/issues/31).

Thank you for your reply

But I don't know if the problem is from VPS - digitalocean

Or the Rutorrent program

Thank you

**Comment by stickz** [comment]
Set `$do_diagnostic` to false in `/conf/config.php`. I will come up with a better solution later for ruTorrent & Swizzin.

**Comment by ADz-83** [comment]
> Set `$do_diagnostic` to false in `/conf/config.php`. I will come up with a better solution later for ruTorrent & Swizzin.

Hi Stickz.  Just curious if you came up with better solution?

**Comment by stickz** [comment]
> > Set `$do_diagnostic` to false in `/conf/config.php`. I will come up with a better solution later for ruTorrent & Swizzin.
> 
> Hi Stickz. Just curious if you came up with better solution?

Yes, `$al_diagnostic=false` . It allows disabling of just the auto loader diagnostics. This is less intrusive. 

The other diagnostics should stay on, so you know if there's a problem with rutorrent. They were optimized with a new local hosted mode feature for faster page loading.

If you want stability over speed, you can also keep plugin caching disabled to avoid issues on version upgrades.

**Comment by mrlongshen** [comment]
> Set `$do_diagnostic` to false in `/conf/config.php`. I will come up with a better solution later for ruTorrent & Swizzin.

Followed this.
But it still, happen.
Any other solution?


![2023-03-21_23-22](https://user-images.githubusercontent.com/5020778/226654182-abc287e1-c94b-43ac-b55b-1f1d9cff156c.png)

**Comment by liaralabs** [comment]
This should be fixed in the most recent stable version -- you would need to reinstall the filemanager plugin though to pull in the pinned version required to fix this regression.

**Comment by mrlongshen** [comment]
> This should be fixed in the most recent stable version -- you would need to reinstall the filemanager plugin though to pull in the pinned version required to fix this regression.

After box update, and reinstall the file manager got this error.

filemanager: Failed to change directory -> Class 'Flm\ShellCmd' not found

![2023-04-03_2-09-47](https://user-images.githubusercontent.com/5020778/229370920-c4588d5f-fd07-4d23-adba-4468559b1858.jpg)

**Comment by liaralabs** [comment]
Try a hard reset or an incognito window. Some things may be cached

**Comment by Flwk** [comment]
Hello

I had this problem and i found a solution on the discord : 

You have to remove and reinstall the plugin with rtx

`box rtx`

You choose plugin, remove plugins, check **filemanager** and valid.

After that, you relaunch rtx and reinstall filemanager.

Clear the cache of the browser with ctrl + f5, and refresh the page. 

it will work :)

**Comment by liaralabs** [comment]
Please be aware that for the above to work, you should ensure you're on the latest update of swizzin before re-installing the plugin (so just a `box update`)
