### ISSUE TITLE
[BUG] qbittorrent 4.4.1 is asking for auth when adding a torrent file

### ISSUE THREAD

**Issue by Sockolet** [swizzin/swizzin#943]
### What happened?

Steps to reproduce:

1. Open qbitorrent web
2. Click on "Add torrent file"
3. Choose torrent file and click on "Upload torrents"
4. Auth prompt from reverse proxy is launched
5. Torrent is not added.

Interesting thing is torrent can be added successfully using Transdroid app on Android (configured using same credential I'm using to access via web).

Expected results:
No auth pop-up is shown, also the torrent is succesfully added.

### Swizzin commit

448031a

### What OS are you using?

Ubuntu 22.04 (Jammy)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
Failed to load resource: the server responded with a status of 401 ()
/qbittorrent/api/v2/torrents/add:1          Failed to load resource: the server responded with a status of 401 ()
/qbittorrent/api/v2/torrents/add:1          POST https://www.********.xyz/qbittorrent/api/v2/torrents/add 401
/qbittorrent/api/v2/torrents/add:1          POST https://www.********.xyz/qbittorrent/api/v2/torrents/add 401
```

**Comment by liaralabs** [comment]
I cannot reproduce this on the 4.4.5 version. I would recommend doing a `box upgrade qbittorrent` and seeing if this is still reproducible on the latest version of 4.4.5. This may have been a bug in the version you're using and fixed in the later releases.

**Comment by Sockolet** [comment]
Same behavior after upgrading to 4.4.5. Is there any way I can troubleshoot this? Will a Fiddler trace help here?

**Comment by Sockolet** [comment]
I found the issue. So, as you may know, Nextcloud has some requisites on the headers configuration for Nginx that are reported in the Administrative Settings menu.
Those settings are:

add_header X-XSS-Protection "1; mode=block";
add_header X-Robots-Tag none;
add_header X-Download-Options noopen;
add_header X-Permitted-Cross-Domain-Policies none;
add_header Referrer-Policy no-referrer;
add_header Strict-Transport-Security "max-age=15552000; includeSubDomains" always;
  
I tried to add them to the nextcloud config file (/etc/nginx/apps/nextcloud.conf) but Nextcloud doesn't seem to recognize them (keeps on reporting they are missing.
So I decided to add them to the main config inside /etc/nginx/sites-enabled/default. After have set them there, Nextcloud stop reporting those were missing so they were successfully recognized.
Now, after a couple of tests by removing and adding them one by one, I identified that the setting that was causing this behavior to qBittorrent was this specific one:
"add_header Referrer-Policy no-referrer;"

Not sure if there is anyway to implement this without affecting the whole Nginx reverse proxy.

Thank you very much for your support as always.
