### ISSUE TITLE
[BUG] Flood UI Freezing 

### ISSUE THREAD

**Issue by sanjue007** [swizzin/swizzin#945]
### What happened?

Flood UI freezing suddenly.
after freezing the bandwidth usage panel showing 0/0 Kbps or sometimes stuck in a random upload and download speed
![A0D1gtXy4Y](https://user-images.githubusercontent.com/66324749/210075351-6fa87e29-db88-4819-9a55-b07f4b8ac9ed.png)

### Swizzin commit

448031a

### What OS are you using?

Debian 11 (Bullseye)

### What architecture is your OS?

amd64

**Comment by liaralabs** [comment]
You haven't really provided enough information to go on. How are you using flood? (I.e which client)

If it's qbit, this sounds quite similar to the normal issues of the backend stopping responding during periods of heavy activity.

That said, this likely isn't a problem with swizzin directly and you issue would likely be better served looking for help in the flood project.

**Comment by flying-sausages** [comment]
no response, let us know if there's anything else
