### ISSUE TITLE
[BUG] Bad gateway to Nzbhydra after upgrade to 5.1.1

### ISSUE THREAD

**Issue by nanouk76** [swizzin/swizzin#953]
### What happened?

Steps to reproduce:

1. Upgrade package NZBHydra2 to v. 5.1.1
2. Refresh NZBHydra2 page
3. Error 502 Bad Gateway nginx

Expected results:
Access to NZBHydra page

### Swizzin commit

7ec4026

### What OS are you using?

Ubuntu 22.04 (Jammy)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
sudo box upgrade nzbhydra
...	Updating swizzin local repository
	✔   Local repository updated using: master
INFO	HEAD is now set to 7ec4026
...	Setting correct permissions on swizzin files
	✔   Permissions set
...	Updating panel to latest version
...	Pulling new commits
	✔   Commits pulled
...	Checking pip for new depends
	✔   Depends up-to-date
...	Restarting Panel
	✔   Done!
	✔   Done
...	Installing certificate into vsftpd
	✔   Done
...	Upgrading NZBHydra to v5.1.1
	✔   Installed
```

**Comment by liaralabs** [comment]
I cannot replicate the issue on a fresh install.

Please provide some actual logs rather than just console output of the upgrade action (which doesn't indicate any issues).

Is nzbhydra running? (i.e. do you have logs?)

Did the port change? (logs should show what port nzbhydra is running on)

**Comment by nanouk76** [comment]
Sorry I jumped the gun 😔. Had to wait for all services to restart I guess. Problem solved. Sorry again to have wasted your time.
Please consider the issue closed .
