### ISSUE TITLE
[BUG] missing acme.sh file

### ISSUE THREAD

**Issue by skurty** [swizzin/swizzin#965]
### What happened?

Due to ssl certificates renewal issues, I uninstalled all of them and I updated the box command to the last version. After reinstalling the default ssl certificates and other domains, I now have this error whenever I use the box command (box install letsencrypt or box update):

`...	Installing certificate into vsftpd
/etc/swizzin/sources/functions/letsencrypt: line 10: /root/.acme.sh/sub.domain.tld/sub.domain.tld.conf: No such file or directory
sed: can't read /root/.acme.sh/sub.domain.tld/sub.domain.tld.conf: No such file or directory`

Steps to reproduce:

1. Uninstall all ssl certificates
2. Update box
3. Reinstall all ssl certificates
4. Use `box install letsencrypt` or `box update`
6. Error 'sed: can't read /root/.acme.sh/sub.domain.tld/sub.domain.tld.conf: No such file or directory'

Expected results:
The file should be found in the folder /root/.acme.sh/sub.domain.tld_ecc/

### Swizzin commit

7ec4026

### What OS are you using?

Ubuntu 20.04 (Focal)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
$ sudo box install letsencrypt
INFO	Installing letsencrypt
DOCS	Further reference: https://swizzin.ltd/applications/letsencrypt
INPUT	Enter domain name to secure with LE
> sub2.domain.tld
INPUT	Do you want to apply this certificate to your swizzin default conf?
(y/n) > n
INPUT	Is your DNS managed by CloudFlare?
(y/n) > n
...	Registering certificates
	✔   Certificate acquired
...	Installing certificate
[Mon 20 Mar 2023 09:55:49 AM CET] The domain 'sub2.domain.tld' seems to have a ECC cert already, lets use ecc cert.
[Mon 20 Mar 2023 09:55:49 AM CET] Installing CA to: /etc/nginx/ssl/sub2.domain.tld/chain.pem
[Mon 20 Mar 2023 09:55:49 AM CET] Installing key to: /etc/nginx/ssl/sub2.domain.tld/key.pem
[Mon 20 Mar 2023 09:55:49 AM CET] Installing full chain to: /etc/nginx/ssl/sub2.domain.tld/fullchain.pem
[Mon 20 Mar 2023 09:55:49 AM CET] Run reload cmd: systemctl reload nginx
[Mon 20 Mar 2023 09:55:49 AM CET] Reload success
	✔   Certificate installed
...	Installing certificate into vsftpd
/etc/swizzin/sources/functions/letsencrypt: line 10: /root/.acme.sh/sub.domain.tld/sub.domain.tld.conf: No such file or directory
sed: can't read /root/.acme.sh/sub.domain.tld/sub.domain.tld.conf: No such file or directory
	✔   Done
```

**Comment by cp-samantha** [comment]
Any chance you can possibly test this against the develop branch? I've pushed a fix but since I cannot reproduce I cannot test whether it is effective at solving the issue.

**Comment by liaralabs** [comment]
Can you please test against the develop branch? 85abc920dbba06b53792e61d92a6bfaa5a5d900c

I don't have the means available to test the fix.

**Comment by AncientVamp** [comment]
I was getting that same line 10 message but on Debian 11. After doing a recent `box update`, I'm not getting that message anymore.

**Comment by skurty** [comment]
After a box update I don't have the issue neither, thank you!
