### ISSUE TITLE
RuTorrent: "JS error: ReferenceError: Can't find variable: clearCanvas"

### ISSUE THREAD

**Issue by AlexCGN13** [swizzin/swizzin#971]
### What happened?

Fresh install of Swizzin, 
installation showed that everything installed correctly, 
but opening rutorrent, (repo, 0,98) show the repeating following error , every 10 seconds : " JS error: ReferenceError: Can't find variable: clearCanvas"

tried 3 fresh installs  of swizzin on the server 
Also tried  two times to remove and reinstall rtorrent and rutorrent, also tried to install the "not repo " version , and the 0,97 version . but the issue is still there. 

### Swizzin commit

7ec4026

### What OS are you using?

Debian 11 (Bullseye)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
# box upgrade rtorrent
...	Updating swizzin local repository
	✔   Local repository updated using: master
INFO	HEAD is now set to 7ec4026
...	Setting correct permissions on swizzin files
	✔   Permissions set
...	Updating panel to latest version
...	Pulling new commits
	✔   Commits pulled
...	Checking pip for new depends
	✔   Depends up-to-date
...	Restarting Panel
	✔   Done!
	✔   Done
...	Removing old rTorrent binaries and libraries ... 
	✔   Done
...	Checking rTorrent Dependencies ... 
	✔   Done
...	Building xmlrpc-c from source ... 
	✔   Done
...	Building libtorrent from source ... 
	✔   Done
...	Building rtorrent from source ... 
	✔   Done
```

**Comment by JySzE** [comment]
I am having the same issue.

**Comment by liaralabs** [comment]
This should be resolved with the recent push to stable -- I would suggest reinstalling.

**Comment by JySzE** [comment]
nginx is failing to install on ubuntu 22.04 now.

**Comment by liaralabs** [comment]
Please don't conflate issues -- this scope of this issue is ruTorrent and the error mentioned in the ticket description.

Open a new ticket with a proper description of the behavior and supporting evidence via logs if you wish to discuss a new issue you think is a bug.

**Comment by stickz** [comment]
If you're using rTorrent 4.1 beta, please upgrade to beta 2. https://github.com/Novik/ruTorrent/releases/tag/v4.1-beta.2

**Comment by flying-sausages** [comment]
@AlexCGN13 I'm assuming this has been resolved as no updates from you, let us know if it's persistent after a `box update` or `box upgrade rutorrent`
