### ISSUE TITLE
Panel network stats only show top 10 days

### ISSUE THREAD

**Issue by GitHub-BumBleBee** [swizzin/swizzin#995]
### What happened?

Steps to reproduce:

1. Install package '...'
2. Go to '....'
3. Error '...'

Expected results:

### Swizzin commit

yes

### What OS are you using?

Ubuntu 22.04 (Jammy)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
The Dashboard is not showing every day!
It is not counting the month of May!


image link:https://i.postimg.cc/26wLV6q9/ERRO-SWIZZIN.png
```

**Comment by c9rnelius** [comment]
Hey there, I believe this is not a bug. The table is supposed to show your top 10 entries.

**Comment by GitHub-BumBleBee** [comment]
And there's no way to change that, to show every day. Replacing previous days. I want to see the present day!

**Comment by filex100** [comment]
Would something like this be possible? :

TOP 10 UP
TOP 10 DOWN

**Comment by liaralabs** [comment]
No. The panel gets data directly from vnstat with the top10 argument. There isn't any way to break that down to specify download or upload -- it's top 10 by total transfer

**Comment by GitHub-BumBleBee** [comment]
I thought it would be better to show the day by day, both download and upload. My opinion.

**Comment by GitHub-BumBleBee** [comment]
I would also like to see if there's a way for Qbittorrent to be complete in Portuguese, like Rutorrent?
