### ISSUE TITLE
[BUG] External CSS/JS/font requests on Swizzin Panel.

### ISSUE THREAD

**Issue by RootInit** [swizzin/swizzin#996]
### What happened?

The Swizzin panel does not load (correctly) when client device offline as it attempts to load external JS, CSS, and fonts from external services. I am assuming this qualifies as a bug as Jellyfin, Radarr, Sonarr, etc all seem to package their resources locally and their seems to be no reason why Swizzin's panel should not do the same.

Steps to reproduce:

Disable networking on client device
Attempt to load swizzin panel

This hangs while failing to reach external servers and though the page will eventually load, it is missing functionality and severely broken.

### Swizzin commit

448031a

### What OS are you using?

Debian 11 (Bullseye)

### What architecture is your OS?

amd64

**Comment by flying-sausages** [comment]
@liaralabs can you transfer this one to [swizzin/swizzin_dashboard](https://github.com/swizzin/swizzin_dashboard) please?

**Comment by RootInit** [comment]
> @liaralabs can you transfer this one to [swizzin/swizzin_dashboard](https://github.com/swizzin/swizzin_dashboard) please?

I never got a notification for that... Moved now. https://github.com/swizzin/swizzin_dashboard/issues/65

**Comment by RootInit** [comment]
Closing, Hopefully panel developers fix this.
